### ISSUE TITLE
undefined method `metrics' for Sidekiq::Pro:Module

### ISSUE THREAD

**Issue by mbajur** [sidekiq/sidekiq#5783]
Ruby version: 2.7.7
Rails version: 5.2.4.6
Sidekiq / Pro / Enterprise version(s): 5.5.8 (and `~> 7.0` + Sidekiq `~> 7.0`)

### Initializer
```
require 'sidekiq'
require 'sidekiq-status'

unless Rails.env.test?
  if Figaro.env.redis_url?
    uri = URI(Figaro.env.redis_url)
    host = uri.host
    port = uri.port
  else
    host = Figaro.env.redis_host || 'localhost'
    port = Figaro.env.redis_port || '6379'
  end

  namespace = Figaro.env.redis_namespace || 'cuseum'

  Sidekiq.configure_server do |config|
    config.super_fetch!
    config.reliable_scheduler!

    config.redis = { :url => "redis://#{host}:#{port}", :namespace => namespace }

    config.server_middleware do |chain|
      chain.add Sidekiq::Middlewares::LoggerContext, logger: Rails.logger
      chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes
    end

    config.client_middleware do |chain|
      chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes
    end

    Sidekiq::Status.configure_server_middleware config, expiration: 30.minutes

    # accepts :expiration (optional)
    Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes
  end

  Sidekiq.configure_client do |config|
    config.redis = { :url => "redis://#{host}:#{port}", :namespace => namespace }

    Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes

    config.client_middleware do |chain|
      chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes
    end
  end
end

Sidekiq::Client.reliable_push! unless Rails.env.test?
```

## sidekiq.yml
```
:timeout: 300
:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
development:
  :concurrency: 10
production:
  :concurrency: 5

```

## Error
```
 NoMethodError:
       undefined method `metrics' for Sidekiq::Pro:Module
     # /Users/mbajur/.rvm/gems/ruby-2.7.7/gems/sidekiq-pro-5.5.8/lib/sidekiq/batch.rb:216:in `jobs'
     # ./app/workers/pass_books/batch_generate_v2_worker.rb:18:in `perform'
     # ./spec/workers/pass_books/batch_generate_v2_worker_spec.rb:16:in `block (3 levels) in <top (required)>'
```

**Comment by mperham** [comment]
Sidekiq Pro 5 works with Sidekiq 6. Please use Pro 7 with Sidekiq 7. The major version numbers are now sync'd to denote which versions are designed to work together.

**Comment by mbajur** [comment]
I'm getting the exact same error for Sidekiq Pro 7.0.6 and Sidekiq 7.0.4

**Comment by mperham** [comment]
I don't know why you are getting that. The method is clearly defined at lib/sidekiq/pro/metrics.rb line 56.

Are you actually requiring `sidekiq-pro`?

**Comment by mbajur** [comment]
Oh...not sure why was it working before and stopped but indeed changing `gem 'sidekiq-pro', require: ['sidekiq/pro/web']` to `gem 'sidekiq-pro', require: ['sidekiq-pro', 'sidekiq/pro/web']` fixed the issue for me. Thank you!
