### ISSUE TITLE
Bad cron causes Sidekiq to initialize but not execute periodic jobs

### ISSUE THREAD

**Issue by markedmondson** [sidekiq/sidekiq#5832]
Ruby version: 3.1.2
Rails version: 6.1.7.3
Sidekiq / Pro / Enterprise version(s): ent-2.5.3, pro-5.5.5, sidekiq-6.5.8

If Sidekiq is configured with a bad cron record, such as:

```yml
bad_job:
  cron: "1 31 * * *"
  class: "BadJob"
another_job:
  cron: "0 0 * * *"
  class: "GoodJob"
```

Sidekiq comes up and executes normally (periodic jobs even show in the interface correctly) but no periodic jobs are queued or executed. It would be nice if the cron parsing could rescue the ArgumentError and still raise the exception but still keep other jobs running as the exception is easily missed (especially when someone deploys it right at daylight savings and you just make the bad assumption it's related! 😨)

```
ArgumentError: hour out of range
  from <internal:timev>:310:in `initialize'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/cron.rb:51:in `new'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/cron.rb:51:in `to_time'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/cron.rb:128:in `next'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/static_loop.rb:33:in `block in next_occurrence'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/static_loop.rb:32:in `loop'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/static_loop.rb:32:in `next_occurrence'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/config.rb:107:in `block in queue_for'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/config.rb:106:in `each'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/config.rb:106:in `queue_for'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/config.rb:99:in `finish!'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic/manager.rb:56:in `persist'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/periodic.rb:95:in `block (2 levels) in <top (required)>'
  from sidekiq (6.5.8) lib/sidekiq/component.rb:57:in `block in fire_event'
  from sidekiq (6.5.8) lib/sidekiq/component.rb:56:in `each'
  from sidekiq (6.5.8) lib/sidekiq/component.rb:56:in `fire_event'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/senate.rb:85:in `stage_coup!'
  from sidekiq-ent (2.5.3) lib/sidekiq-ent/senate.rb:93:in `cycle'
  from sidekiq (6.5.8) lib/sidekiq/component.rb:8:in `watchdog'
  from sidekiq (6.5.8) lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**Comment by mperham** [comment]
👍🏼 I'm working on a new test helper for periodic job verification.

> the exception is easily missed

This is why I recommend using an error service which handles notifications to the team. No one should be crawling through logs.

**Comment by markedmondson** [comment]
> 👍🏼 I'm working on a new test helper for periodic job verification.

Great! Thank you :)

> This is why I recommend using an error service which handles notifications to the team. No one should be crawling through logs.

Agreed! It hit Sentry, and honestly, it was right after a deploy so you'd have thought we'd have caught it but you know sometimes resources are stretched and exceptions are ignored or put off before the full impact is truly understood.
