### ISSUE TITLE
Redis timeout changes causing RedisClient::ReadTimeoutError in Sidekiq::Limiter

### ISSUE THREAD

**Issue by jdelStrother** [sidekiq/sidekiq#5838]
Ruby version: 3.1.2
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s):  7.0.7 /  7.0.8 /  7.0.6

With sidekiq-ent 7.0.5, Sidekiq::Limiter.concurrent raises Sidekiq::Limiter::OverLimit when the wait timeout is exceeded.
In 7.0.6, it raises RedisClient::ReadTimeoutError (which, I assume, is bypassing the rescue where `job["overrated"]` is incremented).

7.0.5:
```
irb(main):007:0> l = Sidekiq::Limiter.concurrent("test", 2, wait_timeout: 5); 3.times.map { Thread.new { l.within_limit { sleep 6 } } }.map(&:join)
#<Thread:0x000000010c23d4c8 (irb):7 run> terminated with exception (report_on_exception is true):
$GEMS/sidekiq-ent-7.0.5/lib/sidekiq-ent/limiter/concurrent.rb:213:in `block in lock': test (Sidekiq::Limiter::OverLimit)
	from $GEMS/sidekiq-ent-7.0.5/lib/sidekiq-ent/limiter.rb:92:in `block in redis'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
	from $GEMS/sidekiq-ent-7.0.5/lib/sidekiq-ent/limiter.rb:89:in `redis'
	from $GEMS/sidekiq-ent-7.0.5/lib/sidekiq-ent/limiter/concurrent.rb:194:in `lock'
	from $GEMS/sidekiq-ent-7.0.5/lib/sidekiq-ent/limiter/concurrent.rb:61:in `within_limit'
	from (irb):7:in `block (2 levels) in <main>'
$GEMS/sidekiq-ent-7.0.5/lib/sidekiq-ent/limiter/concurrent.rb:213:in `block in lock': test (Sidekiq::Limiter::OverLimit)
```

7.0.6:
```
irb(main):002:0> l = Sidekiq::Limiter.concurrent("test", 2, wait_timeout: 5); 3.times.map { Thread.new { l.within_limit { sleep 6 } } }.map(&:join)
#<Thread:0x000000011acbecb8 (irb):2 run> terminated with exception (report_on_exception is true):
$GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer': RedisClient::ReadTimeoutError (RedisClient::ReadTimeoutError)
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/buffered_io.rb:122:in `loop'
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/buffered_io.rb:122:in `fill_buffer'
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/buffered_io.rb:114:in `ensure_remaining'
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/buffered_io.rb:85:in `getbyte'
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/resp3.rb:113:in `parse'
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/resp3.rb:50:in `load'
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection.rb:96:in `block in read'
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/buffered_io.rb:48:in `with_timeout'
	from $GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection.rb:96:in `read'
	from $GEMS/redis-client-0.14.0/lib/redis_client/connection_mixin.rb:31:in `call'
	from $GEMS/redis-client-0.14.0/lib/redis_client.rb:272:in `block (2 levels) in blocking_call'
	from $GEMS/redis-client-0.14.0/lib/redis_client/middlewares.rb:16:in `call'
	from $GEMS/redis-client-0.14.0/lib/redis_client.rb:271:in `block in blocking_call'
	from $GEMS/redis-client-0.14.0/lib/redis_client.rb:626:in `ensure_connected'
	from $GEMS/redis-client-0.14.0/lib/redis_client.rb:270:in `blocking_call'
	from $GEMS/redis-client-0.14.0/lib/redis_client/decorator.rb:26:in `blocking_call'
	from $GEMS/sidekiq-ent-7.0.6/lib/sidekiq-ent/limiter/concurrent.rb:199:in `block in lock'
	from $GEMS/sidekiq-ent-7.0.6/lib/sidekiq-ent/limiter.rb:92:in `block in redis'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
	from $GEMS/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
	from $GEMS/sidekiq-ent-7.0.6/lib/sidekiq-ent/limiter.rb:89:in `redis'
	from $GEMS/sidekiq-ent-7.0.6/lib/sidekiq-ent/limiter/concurrent.rb:194:in `lock'
	from $GEMS/sidekiq-ent-7.0.6/lib/sidekiq-ent/limiter/concurrent.rb:61:in `within_limit'
	from (irb):2:in `block (2 levels) in <main>'
$GEMS/redis-client-0.14.0/lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer': RedisClient::ReadTimeoutError (RedisClient::ReadTimeoutError)
```

**Comment by mperham** [comment]
I'm not sure this is a Sidekiq bug.

@casperisfine I'm calling brpushlpop with two timeouts: A and B:

```ruby
wait_timeout = 5
wait_until = now + wait_timeout
loop do
  time_left = wait_until - now
  candidate = conn.blocking_call(wait_timeout, "brpoplpush", @free, @pend, time_left)
  if candidate ...
end
```

As you can see from the code, time_left (A) should be strictly less than wait_timeout (B). I am assuming that `brpoplpush` will return nil for candidate. If I see a ReadTimeoutError due to `wait_timeout`, I want that error to raise up as that seems like a network partition or similar issue. 

I think of the two timeouts as client-side and server-side timeouts. I don't want the client-side timeout (wait_timeout) to trigger unless there's really a network problem - like if I couldn't contact Redis. If the server-side timeout (time_left) triggers, that just means a lock wasn't returned in time, brpoplpush should timeout and return nil for candidate: totally normal.

What am I missing?

**Comment by casperisfine** [comment]
You assertion is correct, however there is one subtleties, you do want some leeway between the client timeout and the server timeout.

When you `brpoplpush` with a server side timeout of say, 5 seconds, with the network roundtrip, especially if there is an occasional packet loss or something, it will always appear as more than 5 seconds to the client.

So for client timeout of blocking commands, my recommendation is to use `server_side_timeout + generic_client_side_timeout`: https://github.com/redis/redis-rb/blob/e4f5299aa0109d1334564f20ae8522866ef554e9/lib/redis/client.rb#L79-L84

**Comment by mperham** [comment]
Ok, I adjusted it to be `blocking_call(timeout + 1, ...., timeout)` so the client-side timeout is one second more than the server-side timeout.
