### ISSUE TITLE
Jobs in Queue but not processing

### ISSUE THREAD

**Issue by foxstuart** [sidekiq/sidekiq#5842]
Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
Rails version: Rails 6.0.3.2
Sidekiq / Pro / Enterprise version(s): Ent Sidekiq 5.2.9

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
initializer:
```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://XXX.ng.0001.usw2.cache.amazonaws.com:6379/0' }
    config.periodic do |mgr|
        # mgr.register("* 16 * * *", "ActivityCheckJob")
        # mgr.register("* 17 * * *", "ReapplyCheckJob")
        # mgr.register("* * * * *", "ActivityCheckJob")
        # mgr.register("* * * * *", "ReapplyCheckJob")
        mgr.register("0 9 * * *", "RenewalCheckJob")
    end
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://XXX.0001.usw2.cache.amazonaws.com:6379/0' }
end
```

```
concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - normal
  - low
```

**Comment by mperham** [comment]
Your setup looks fine, although quite old. You will want to upgrade soon.

I need a TTIN dump from a stuck process. Can you get me that?

https://github.com/sidekiq/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes

**Comment by foxstuart** [comment]
Actually it appears Sidekiq isn't running even though I rebooted server and Elasticache:

```$ ps -aux | grep sidekiq ```

```ubuntu    5869  0.0  0.0  14860  1060 pts/0    S+   20:46   0:00 grep --color=auto sidekiq```

The dashboard is up, do I need to restart sidekiq and if so, how?

**Comment by mperham** [comment]
Yes, you need to start Sidekiq. I didn't implement your app so I don't know the "right" way to start Sidekiq in your app.

**Comment by foxstuart** [comment]
Got it up and running and the jobs were processed!
for anyone's future reference it was this on my server:

`sudo /usr/local/bin/bundler exec sidekiq -e production -d -L /home/ubuntu/sidekiq.log
`

I see in the logs it encountered connection issue and decided to die:

```
#<Thread:0x0000560b0e2782c8@/var/lib/gems/2.5.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
/var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:363:in `rescue in establish_connection': Error connecting to Redis on XXX.0001.usw2.cache.amazonaws.com:6379 (SocketError) (Redis::CannotConnectError)
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:344:in `establish_connection'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:106:in `block in connect'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:307:in `with_reconnect'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:105:in `connect'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:382:in `ensure_connected'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:231:in `block in process'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:320:in `logging'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:230:in `process'
	from /var/lib/gems/2.5.0/gems/appsignal-2.11.0/lib/appsignal/hooks/redis.rb:25:in `block in process'
	from /var/lib/gems/2.5.0/gems/appsignal-2.11.0/lib/appsignal/helpers/instrumentation.rb:429:in `instrument'
	from /var/lib/gems/2.5.0/gems/appsignal-2.11.0/lib/appsignal/hooks/redis.rb:24:in `process'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis/client.rb:125:in `call'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis.rb:2558:in `block in _eval'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis.rb:51:in `block in synchronize'
	from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis.rb:51:in `synchronize'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis.rb:2557:in `_eval'
	from /var/lib/gems/2.5.0/gems/redis-4.1.4/lib/redis.rb:2609:in `evalsha'
	from /var/lib/gems/2.5.0/gems/sidekiq-ent-1.8.1/lib/sidekiq-ent/scripting.rb:23:in `block in call'
	from /var/lib/gems/2.5.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
	from /var/lib/gems/2.5.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
	from /var/lib/gems/2.5.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
	from /var/lib/gems/2.5.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
	from /var/lib/gems/2.5.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
	from /var/lib/gems/2.5.0/gems/sidekiq-ent-1.8.1/lib/sidekiq-ent/scripting.rb:22:in `call'
	from /var/lib/gems/2.5.0/gems/sidekiq-ent-1.8.1/lib/sidekiq-ent/senate.rb:76:in `stop!'
	from /var/lib/gems/2.5.0/gems/sidekiq-ent-1.8.1/lib/sidekiq-ent/senate.rb:120:in `cycle'
	from /var/lib/gems/2.5.0/gems/sidekiq-5.2.9/lib/sidekiq/util.rb:16:in `watchdog'
	from /var/lib/gems/2.5.0/gems/sidekiq-5.2.9/lib/sidekiq/util.rb:25:in `block in safe_thread'
	from /var/lib/gems/2.5.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
** [Honeybadger] Error report failed: an unknown error occurred. code=error error="HTTP Error: SocketError" level=2 pid=16492
2023-03-17T01:21:58.224Z 16492 TID-grmjo59yw INFO: Pausing to allow workers to finish...
2023-03-17T01:21:59.726Z 16492 TID-grmjo59yw INFO: Bye!
```

**Comment by mperham** [comment]
I assume you need to add an s to your URL protocol: “rediss://…”

**Comment by foxstuart** [comment]
Thanks for the heads up on the TLS setup. Closing the issue as fixed.
