### ISSUE TITLE
NoMethodError: undefined method `ensure_connected' for #<RedisClient::Pipeline:0x...> when using limiter

### ISSUE THREAD

**Issue by NielsKSchjoedt** [sidekiq/sidekiq#5856]
Ruby version: 2.7.7
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s):
7.0.7 / 7.0.6 / 7.0.8

After upgrading from sidekiq 6.5 and redis 4.8 to 5.0 I get this: 

![Skærmbillede 2023-03-29 kl  09 41 34](https://user-images.githubusercontent.com/570755/228461833-0fa76659-0d21-4e87-a318-b688574dd3af.png)

**Comment by mperham** [comment]
I don't understand the error or cause. Can you supply the full backtrace text, not a screenshot?

**Comment by mperham** [comment]
That backtrace seems incomplete. There is no call to `ensure_connected` on line 20 of your job class. Backtrace cleaner?

**Comment by mperham** [comment]
What is this? `[PROJECT_ROOT]/config/initializers/sidekiq.rb:56 :in "call"`

**Comment by mperham** [comment]
I'm still mystified. Maybe @casperisfine knows what's wrong?

**Comment by casperisfine** [comment]
👀

**Comment by casperisfine** [comment]
Oh wow, that is a weird one.

Here's what I understand (braindumping to see if something hits me) :

```
NoMethodError: undefined method `ensure_connected' for #<RedisClient::Pipeline:0x...>
   [GEM_ROOT]/gems/redis-client-0.14.0/lib/redis_client.rb:209 :in `call`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/redis_client_adapter.rb:27 :in `method_missing`
  [GEM_ROOT]/gems/sidekiq-ent-7.0.6/lib/sidekiq-ent/limiter/bucket.rb:64 :in `block (3 levels) in within_limit`
   [GEM_ROOT]/gems/redis-client-0.14.0/lib/redis_client/decorator.rb:51 :in `block in pipelined`
   [GEM_ROOT]/gems/redis-client-0.14.0/lib/redis_client.rb:354 :in `pipelined`
   [GEM_ROOT]/gems/redis-client-0.14.0/lib/redis_client/decorator.rb:51 :in `pipelined`
  [GEM_ROOT]/gems/sidekiq-ent-7.0.6/lib/sidekiq-ent/limiter/bucket.rb:62 :in `block (2 levels) in within_limit`
```

So `within_limit` does a simple pipeline using the adapter API:

```ruby
            conn.pipelined do |p| # line 62
              p.incr(bkt)
              p.expire(bkt, data_ttl) # line 64
            end
```

`pipelined` is the method from `RedisClient::Decorator`, so we just wrap the regular `Redis::Pipeline` instance with a `Sidekiq::CompactClient::Pipeline`.


Somehow the `incr` call works fine, but then when we call `expire` it fails weirdly.

We hit `method_missing` here: https://github.com/sidekiq/sidekiq/blob/6192ed20b639990403f7ec03b5fd651114531368/lib/sidekiq/redis_client_adapter.rb#L27, which is expected, and forward to `@client.call()`.

Here we expect `self` to be a `Sidekiq::CompactClient::Pipeline` and `@client` to be a `RedisClient::Pipeline`.

But somehow:

  - The `call` implementation invoked is the one for `::RedisClient` (line 203)
  - That implementation tries to invoke `ensure_connected`, but that fails because `@client` isn't a `::RedisClient` but a `RedisClient::Pipeline`.

Which makes absolutely 0 sense.

Even if I wanted to hack around to create this situation with `define_method`, Ruby won't let me:

```ruby
    def test_wtf
      RedisClient::Pipeline.define_method(:call, RedisClient.instance_method(:call))

      assert_equal([true], @redis.pipelined { |p| p.exists?("key") })
    end
```

```
RedisClient::DecoratorTest#test_wtf:
TypeError: bind argument must be a subclass of RedisClient
    test/redis_client/decorator_test.rb:33:in `define_method'
    test/redis_client/decorator_test.rb:33:in `test_wtf'
```

At this stage I suspect it's a conflict with some gem doing some metaprograming, perhaps for instrumentation, but expecting Redis 4.x, not 5.x, or something like that.

But that will be hard to figure out without an actual repro so I can introspect the state of these classes to figure it out.

The fact that only the second call fails is also highly suspect. I'll re-read the bug report to see if I missed some details.

**Comment by mperham** [comment]
I would `bundle up newrelic_rpm` just in case.

**Comment by mperham** [comment]
Or run your app without newrelic_rpm and see if that fixes the issue.

**Comment by casperisfine** [comment]
> I would `bundle up newrelic_rpm` just in case.

Yeah, I looked at their `redis-client` instrumentation, and it's prepending a bunch of modules. But I don't see it in the backtrace so I assume `redis` instrumentation is turned off in this app?

**Comment by NielsKSchjoedt** [comment]
Hi again, I have upgraded to the latest version of newrelic RPM (9.1.0) and the issue is still there from time to time. Here is the latest backtrace: 

```
NoMethodError: undefined method `ensure_connected' for #<RedisClient::Pipeline:0x...>
   redis_client.rb:209  call(...)
   redis_client_adapter.rb:27  method_missing(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/redis_client_adapter.rb:27:in `method_missing'
   shared.rb:90  persist(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/shared.rb:90:in `persist'
   tracking.rb:74  block (3 levels) in flush(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:74:in `block (3 levels) in flush'
   tracking.rb:73  each(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:73:in `each'
   tracking.rb:73  block (2 levels) in flush(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:73:in `block (2 levels) in flush'
   decorator.rb:51  block in pipelined(...)
[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/decorator.rb:51:in `block in pipelined'
   redis_client.rb:354  pipelined(...)
[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client.rb:354:in `pipelined'
   decorator.rb:51  pipelined(...)
[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/decorator.rb:51:in `pipelined'
   tracking.rb:72  block in flush(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:72:in `block in flush'
   config.rb:156  block in redis(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/config.rb:156:in `block in redis'
   connection_pool.rb:107  block (2 levels) in with(...)
[GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:107:in `block (2 levels) in with'
   connection_pool.rb:106  handle_interrupt(...)
[GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `handle_interrupt'
   connection_pool.rb:106  block in with(...)
[GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `block in with'
   connection_pool.rb:103  handle_interrupt(...)
[GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `handle_interrupt'
   connection_pool.rb:103  with(...)
[GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `with'
   config.rb:153  redis(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/config.rb:153:in `redis'
   component.rb:28  redis(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:28:in `redis'
   tracking.rb:69  flush(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:69:in `flush'
   tracking.rb:134  block (2 levels) in (...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:134:in `block (2 levels) in <top (required)>'
   component.rb:60  block in fire_event(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:60:in `block in fire_event'
   component.rb:59  each(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:59:in `each'
   component.rb:59  fire_event(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:59:in `fire_event'
   launcher.rb:182  ❤(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:182:in `❤'
   launcher.rb:98  beat(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:98:in `beat'
   launcher.rb:90  block in start_heartbeat(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:90:in `block in start_heartbeat'
   launcher.rb:89  loop(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:89:in `loop'
   launcher.rb:89  start_heartbeat(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:89:in `start_heartbeat'
   component.rb:10  watchdog(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:10:in `watchdog'
   component.rb:19  block in safe_thread(...)
[GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:19:in `block in safe_thread'
```

**Comment by casperisfine** [comment]
@NielsKSchjoedt it's still just as puzzling. I think we'd need to print some extra info when this happens.

If I give you a custom `redis-client` branch, can you run it in production?

**Comment by NielsKSchjoedt** [comment]
@casperisfine sure :-)

**Comment by casperisfine** [comment]
Awesome, here you go: https://github.com/redis-rb/redis-client/tree/debug-ensure-connected

For context I just add a bit more info to the exception and re-raise it. I'm hopping to see where this method comes from.

**Comment by NielsKSchjoedt** [comment]
@casperisfine here are an updated example:

```
NoMethodError: method: #<Method: RedisClient::Pipeline(RedisClient::Multi)#call(*command, **kwargs, &block) /home/app_autouncle/autouncle/shared/bundle/ruby/2.7.0/bundler/gems/redis-client-9aa1234b67a5/lib/redis_client.rb:462>, self: #<RedisClient::Pipeline:0x00007f0f22eabc70 @command_builder=RedisClient::CommandBuilder, @size=0, @commands=[["bitfield", "WorkerJobs::Elasticsearch::IndexCarJob-13-12:30", "OVERFLOW", "SAT", "INCRBY", "u16", "#0", "9", "INCRBY", "u16", "#1", "31", "INCRBY", "u16", "#2", "20", "INCRBY", "u16", "#3", "6", "INCRBY", "u16", "#4", "4", "INCRBY", "u16", "#5", "1", "INCRBY", "u16", "#6", "1"]], @blocks=nil, @retryable=true, @timeouts=nil>, undefined method `flat_map' for #<RedisClient::Pipeline:0x...>
[GEM_ROOT]/bundler/gems/redis-client-9aa1234b67a5/lib/redis_client.rb:221 :in `rescue in call`
[GEM_ROOT]/bundler/gems/redis-client-9aa1234b67a5/lib/redis_client.rb:207 :in `call`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/redis_client_adapter.rb:27 :in `method_missing`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/shared.rb:90 :in `persist`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:74 :in `block (3 levels) in flush`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:73 :in `each`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:73 :in `block (2 levels) in flush`
[GEM_ROOT]/bundler/gems/redis-client-9aa1234b67a5/lib/redis_client/decorator.rb:51 :in `block in pipelined`
[GEM_ROOT]/bundler/gems/redis-client-9aa1234b67a5/lib/redis_client.rb:356 :in `pipelined`
[GEM_ROOT]/bundler/gems/redis-client-9aa1234b67a5/lib/redis_client/decorator.rb:51 :in `pipelined`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:72 :in `block in flush`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/config.rb:156 :in `block in redis`
  [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:107 :in `block (2 levels) in with`
  [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:106 :in `handle_interrupt`
  [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:106 :in `block in with`
  [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:103 :in `handle_interrupt`
  [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:103 :in `with`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/config.rb:153 :in `redis`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:28 :in `redis`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:69 :in `flush`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:134 :in `block (2 levels) in <top (required)>`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:60 :in `block in fire_event`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:59 :in `each`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:59 :in `fire_event`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:182 :in `❤`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:98 :in `beat`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:90 :in `block in start_heartbeat`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:89 :in `loop`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:89 :in `start_heartbeat`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:10 :in `watchdog`
  [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:19 :in `block in safe_thread`
```

**Comment by casperisfine** [comment]
> undefined method `flat_map' for #<RedisClient::Pipeline:0x...>

Hum, that's interesting. That's not the same error than before.

Other than that the debug info look ok. I'll see if I can find that flat_map.

**Comment by casperisfine** [comment]
Hum, I updated my modified branch so that it preserve the original exception backtrace. 

I'm sorry to ask this, but I'd appreciate if you could try that new commit, see if it gives up more info.

**Comment by NielsKSchjoedt** [comment]
@casperisfine latest output:

```
NoMethodError: method: #<Method: RedisClient::Pipeline(RedisClient::Multi)#call(*command, **kwargs, &block) /home/au/au/shared/bundle/ruby/2.7.0/bundler/gems/redis-client-59422bd21080/lib/redis_client.rb:462>, self: #<RedisClient::Pipeline:0x00007f31ea3b01c8 @command_builder=RedisClient::CommandBuilder, @size=0, @commands=[], @blocks=nil, @retryable=true, @timeouts=nil>, undefined method `flat_map' for #<RedisClient::Pipeline:0x...>
  [GEM_ROOT]/bundler/gems/redis-client-59422bd21080/lib/redis_client/command_builder.rb:49 :in `generate`
  [GEM_ROOT]/bundler/gems/redis-client-59422bd21080/lib/redis_client.rb:208 :in `call`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/redis_client_adapter.rb:27 :in `method_missing`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:90 :in `block (4 levels) in flush`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:89 :in `each_pair`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:89 :in `block (3 levels) in flush`
  [GEM_ROOT]/bundler/gems/redis-client-59422bd21080/lib/redis_client/decorator.rb:51 :in `block in pipelined`
  [GEM_ROOT]/bundler/gems/redis-client-59422bd21080/lib/redis_client.rb:356 :in `pipelined`
  [GEM_ROOT]/bundler/gems/redis-client-59422bd21080/lib/redis_client/decorator.rb:51 :in `pipelined`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:87 :in `block (2 levels) in flush`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:86 :in `each`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:86 :in `block in flush`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/config.rb:156 :in `block in redis`
   [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:107 :in `block (2 levels) in with`
   [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:106 :in `handle_interrupt`
   [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:106 :in `block in with`
   [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:103 :in `handle_interrupt`
   [GEM_ROOT]/gems/connection_pool-2.4.0/lib/connection_pool.rb:103 :in `with`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/config.rb:153 :in `redis`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:28 :in `redis`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:69 :in `flush`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/metrics/tracking.rb:134 :in `block (2 levels) in <top (required)>`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:60 :in `block in fire_event`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:59 :in `each`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:59 :in `fire_event`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:182 :in `❤`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:98 :in `beat`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:90 :in `block in start_heartbeat`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:89 :in `loop`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/launcher.rb:89 :in `start_heartbeat`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:10 :in `watchdog`
   [GEM_ROOT]/gems/sidekiq-7.0.7/lib/sidekiq/component.rb:19 :in `block in safe_thread`
```

**Comment by casperisfine** [comment]
Thanks, this is very interesting.

The `flat_map` call is here: https://github.com/redis-rb/redis-client/blob/54f82471ce8b9fb06f03d7b1d4a0710cd58e6524/lib/redis_client/command_builder.rb#L49

And `generate` is called from here: https://github.com/redis-rb/redis-client/blob/f10b5f45b15de67cd9d2c761f8b4a2b96fd23efc/lib/redis_client.rb#L208

The whole thing makes 0 sense:

```ruby
  def call(*command, **kwargs)
    command = @command_builder.generate(command, kwargs) # redis_client.rb:208 :in `call`
```

```ruby
      def generate(args, kwargs = nil)
        command = args.flat_map do |element| # command_builder.rb:49 :in `generate`
          case element
          when Hash
            element.flatten
          else
            element
          end
        end
```

The error an backtrace suggest that `args` would be a `RedisClient::Pipeline` instance, but that's impossible because we received it as `*command` in call...

This is terribly puzzling.

**Comment by mperham** [comment]
Bad monkey patch or old instrumentation?

**Comment by mperham** [comment]
Please move this over to redis-client if it continues to be a problem. Closing here as it appears to be an issue deep in there...
