### ISSUE TITLE
invalid option: --pidfile

### ISSUE THREAD

**Issue by amagasu** [sidekiq/sidekiq#5870]
Ruby version: 3.1.2
Rails version: 6.0.6
Sidekiq Pro: 5.5.5

hello! we use Sidekiq Pro.
when bump sidekiq-pro from 5.5.5 to 7.0.9, it hapen to error.
please help me.

error message 
```
invalid option: --pidfile
/usr/local/bundle/gems/sidekiq-7.0.7/lib/sidekiq/cli.rb:340:in `parse_options'
/usr/local/bundle/gems/sidekiq-7.0.7/lib/sidekiq/cli.rb:248:in `setup_options'
/usr/local/bundle/gems/sidekiq-7.0.7/lib/sidekiq/cli.rb:29:in `parse'
/usr/local/bundle/gems/sidekiq-7.0.7/bin/sidekiq:27:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<main>'
```

**Comment by mperham** [comment]
Remove that option, pid files have not been supported since Sidekiq 6 came out several years ago.
