### ISSUE TITLE
undefined method `logger' for {}:Hash

### ISSUE THREAD

**Issue by vtrduque** [sidekiq/sidekiq#5883]
Ruby version: 3.0.2
Rails version: 6.0.6
Sidekiq / Pro / Enterprise version(s): Siderkiq 7.0.8, Pro 7.0.8

Stacktrace:
```
undefined method `logger' for {:span_naming=>:queue, :propagation_style=>:link, :trace_launcher_heartbeat=>false, :trace_poller_enqueue=>false, :trace_poller_wait=>false, :trace_processor_process_one=>false, :peer_service=>nil}:Hash
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/component.rb:24:in `logger'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:39:in `initialize'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/manager.rb:36:in `new'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/manager.rb:36:in `block in initialize'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/manager.rb:35:in `times'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/manager.rb:35:in `initialize'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/launcher.rb:29:in `new'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/launcher.rb:29:in `block in initialize'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/launcher.rb:28:in `map'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/launcher.rb:28:in `initialize'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/cli.rb:119:in `new'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/cli.rb:119:in `launch'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/lib/sidekiq/cli.rb:111:in `run'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.8/bin/sidekiq:31:in `<top (required)>'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/bin/sidekiq:23:in `load'
/Users/vtrduque/dev/zippi/zippi-main/vendor/bundle/ruby/3.0.0/bin/sidekiq:23:in `<top (required)>'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/bin/bundle:23:in `load'
/Users/vtrduque/.rvm/gems/ruby-3.0.2/bin/bundle:23:in `<main>'
```
sidekiq.yml
```
---
:queues:
  - [high, 4]
  - [default, 2]
  - [low, 1]
:verbose: true
```

Initializer
```ruby
# frozen_string_literal: true

Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq.strict_args!(false)
Sidekiq.configure_server do |config|
  config.redis = {
    url: "redis://#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}/#{Rails.configuration.redis[:db]}",
  }
  config.super_fetch! do |jobstr, pill|
    # jobstr is a raw String of JSON. Sidekiq does not parse the JSON string
    # as this could have been the cause of the crash!
    Rails.logger.info do
      {
        message: pill ? 'Sidekiq killed a poison pill' : 'Sidekiq just recovered this job',
        jobstr: jobstr,
        pill: pill,
      }
    end
  end
  config.reliable_scheduler!

  config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new
end
```

Full log (the Sentry event is the stacktrace above)
```
{"ts":"2023-04-19T13:19:00.401Z","pid":65701,"tid":"2cp5","lvl":"INFO","msg":"Booted Rails 6.0.6 application in staging environment"}
{"ts":"2023-04-19T13:19:00.401Z","pid":65701,"tid":"2cp5","lvl":"INFO","msg":"Running in ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin21]"}
{"ts":"2023-04-19T13:19:00.401Z","pid":65701,"tid":"2cp5","lvl":"INFO","msg":"Sidekiq Pro 7.0.9, commercially licensed. Thanks for your support!"}
{"ts":"2023-04-19T13:19:00.401Z","pid":65701,"tid":"2cp5","lvl":"INFO","msg":"Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>\"internal\", :url=>\"redis://omitted:6379/\"}"}
{"ts":"2023-04-19T13:19:01.139Z","pid":65701,"tid":"2cp5","lvl":"WARN","msg":"\n\nWARNING: Your Redis instance will evict Sidekiq data under heavy load.\nThe 'noeviction' maxmemory policy is recommended (current policy: 'volatile-lru').\nSee: https://github.com/sidekiq/sidekiq/wiki/Using-Redis#memory\n\n"}
{"ts":"2023-04-19T13:19:01.142Z","pid":65701,"tid":"2cp5","lvl":"INFO","msg":"Sidekiq 7.0.8 connecting to Redis with options {:size=>10, :pool_name=>\"default\", :url=>\"redis://omitted:6379/\"}"}
{"ts":"2023-04-19T13:19:01.143Z","pid":65701,"tid":"2cp5","lvl":"DEBUG","msg":"Firing startup event"}
{"ts":"2023-04-19T13:19:01.143Z","pid":65701,"tid":"2cp5","lvl":"DEBUG","msg":"Client Middleware: Sidekiq::Batch::Client, Sentry::Sidekiq::SentryContextClientMiddleware, NewRelic::SidekiqInstrumentation::Client, OpenTelemetry::Instrumentation::Sidekiq::Middlewares::Client::TracerMiddleware"}
{"ts":"2023-04-19T13:19:01.143Z","pid":65701,"tid":"2k05","lvl":"INFO","msg":"SuperFetch[default] activated"}
{"ts":"2023-04-19T13:19:01.143Z","pid":65701,"tid":"2cp5","lvl":"DEBUG","msg":"Server Middleware: Sidekiq::Metrics::Middleware, Sidekiq::Batch::Server, Sentry::Sidekiq::SentryContextServerMiddleware, NewRelic::SidekiqInstrumentation::Server, OpenTelemetry::Instrumentation::Sidekiq::Middlewares::Server::TracerMiddleware"}
[Transport] Sending envelope with items [event] 3cb341db607e44a6be25e3ba67cfd844 to Sentry
[Transport] Sending envelope with items [event] 9b9b94c2496c4476a24e93be5ab9472d to Sentry
```

The error I'm facing happens after upgrading from 6.4.2 to 7.0.8

**Comment by mperham** [comment]
Update all of your instrumentation gems.

**Comment by vtrduque** [comment]
That worked man.

Thank you a lot.
