### ISSUE TITLE
Sidekiq 7x: Noisy logging in Rails console

### ISSUE THREAD

**Issue by weilandia** [sidekiq/sidekiq#5897]
Ruby version: 3.2
Rails version: edge
Sidekiq / Pro / Enterprise version(s): 7.0.8 / 7.0.10 / NA

Sidekiq 7.x has redis connection log that appears after opening the rails console, with a delay. I wouldn't usually post this as an issue, but many times already it has interfered with something I was already typing in the console:

```
[PRODUCTION] irb(main):001:0> a=ActionMailbox::InboundEmail.find n
[PRODUCTION] irb(main):003:0> 2023-04-26 16:34:00.845433 I [44:99740 redis_connection.rb:15] Sidekiq -- Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://..."}
[PRODUCTION] irb(main):001:0> ...
```

**Comment by mperham** [comment]
That message indicates your app is creating the Sidekiq client pool. If you see it and your code isn't doing anything with jobs, it's an indication that maybe your app configuration is less than optimal. You'd need to determine why your app is creating the pool prematurely.

**Comment by weilandia** [comment]
Do you see an issue with the below setup?

``` ruby
# config/initializers/sidekiq.rb
# frozen_string_literal: true

require "sidekiq/pro/expiry"

Sidekiq.strict_args!
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch("QUEUE_URL", nil) }

  config.reliable_scheduler!
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch("QUEUE_URL", nil) }
end

```

**Comment by weilandia** [comment]
AppSignal is causing it:

```
[DEV] irb(main):002:0> 2023-04-30 14:04:00.610795 I [36527:36120 sidekiq.rb:24] Sidekiq -- Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://localhost:6379/8"}
/Users/weilandia/repos/govly/config/initializers/sidekiq.rb:25:in `backtrace'
/Users/weilandia/repos/govly/config/initializers/sidekiq.rb:25:in `create'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.0.8/lib/sidekiq/config.rb:132:in `new_redis_pool'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.0.8/lib/sidekiq/config.rb:126:in `local_redis_pool'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.0.8/lib/sidekiq/config.rb:120:in `redis_pool'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.0.8/lib/sidekiq/config.rb:153:in `redis'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.0.8/lib/sidekiq.rb:73:in `redis'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/appsignal-3.4.1/lib/appsignal/probes/sidekiq.rb:11:in `redis_info'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/appsignal-3.4.1/lib/appsignal/probes/sidekiq.rb:78:in `track_redis_info'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/appsignal-3.4.1/lib/appsignal/probes/sidekiq.rb:68:in `call'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/appsignal-3.4.1/lib/appsignal/minutely.rb:139:in `block (3 levels) in start'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/appsignal-3.4.1/lib/appsignal/minutely.rb:137:in `each'
/Users/weilandia/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/appsignal-3.4.1/lib/appsignal/minutely.rb:137:in `block (2 levels) in start'

```
