### ISSUE TITLE
Sidekiq 7x: Noisy logging in Rails console

### ISSUE THREAD

**Issue by weilandia** [sidekiq/sidekiq#5907]
Redis pool logging noisy on test runs as will for integration tests using `Sidekiq::Testing.inline!`

Similar to #5897
```
Running 751 tests in parallel using 4 processes
Run options: -p --seed 61638

# Running:

.........2023-05-05T03:43:05.000Z pid=91489 tid=22il INFO: Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://localhost:6379/10"}
2023-05-05T03:43:05.000Z pid=91486 tid=22gy INFO: Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://localhost:6379/10"}
2023-05-05T03:43:05.000Z pid=91487 tid=22gz INFO: Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://localhost:6379/10"}
2023-05-05T03:43:06.000Z pid=91488 tid=22ik INFO: Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://localhost:6379/10"}
...
```

**Comment by mperham** [comment]
Please use the same trick to determine who is creating the pool.

**Comment by weilandia** [comment]
It's being created by jobs `process_async` in application code triggered in the integration tests.

**Comment by mperham** [comment]
Show me the full backtrace.

**Comment by weilandia** [comment]
```
RuntimeError: pool creation: {:size=>5, :logger=>#<Sidekiq::Logger:0x0000000119976818 @level=1, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000011835c7f8 @datetime_format=nil>, @formatter=#<Sidekiq::Logger::Formatters::JSON:0x0000000118355520 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x0000000119976728 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @binmode=false, @mon_data=#<Monitor:0x000000011835b290>, @mon_data_owner_object_id=19160>>, :pool_name=>"internal", :url=>"redis://localhost:6379/10"}
    config/initializers/sidekiq.rb:23:in `create'
    sidekiq (7.0.8) lib/sidekiq/config.rb:132:in `new_redis_pool'
    sidekiq (7.0.8) lib/sidekiq/config.rb:126:in `local_redis_pool'
    sidekiq (7.0.8) lib/sidekiq/config.rb:120:in `redis_pool'
    sidekiq (7.0.8) lib/sidekiq/job.rb:372:in `build_client'
    sidekiq (7.0.8) lib/sidekiq/job.rb:365:in `client_push'
    sidekiq (7.0.8) lib/sidekiq/job.rb:198:in `perform_async'
    app/models/event.rb:59:in `process_later'
```

**Comment by weilandia** [comment]
```
# app/models/event.rb:59:in `process_later'
def process_later(queue: "default")
    worker = "#{self.class.name}Worker".safe_constantize || EventWorker

    worker.set(
      queue:,
      tags: [self.class.name]
    ).perform_async(
      attributes
    )
  end
```

**Comment by davidwessman** [comment]
```ruby
  test "fake and perform_async" do
    Sidekiq::Testing.fake!
    Documents::ConvertDocumentToPdfWorker.perform_async(1)
  end
 ```

If I add the trick from the other issue I get this as well:

```ruby
Error:
DocumentTest#test_fake_and_perform_async:
RuntimeError: pool creation: {:size=>1, :logger=>#<Sidekiq::Logger:0x000000010bad7cd8 @level=1, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000010bad7b48 @datetime_format=nil>, @formatter=#<Sidekiq::Logger::Formatters::Pretty:0x000000010bad7800 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x000000010bad7a08 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @binmode=false, @mon_data=#<Monitor:0x000000010bad79b8>, @mon_data_owner_object_id=98360>>, :pool_name=>"internal", :ssl_params=>{:verify_mode=>0}}
    /Users/davidwessman/programming/project/config/initializers/sidekiq.rb:28:in `create'
    /Users/davidwessman/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/config.rb:136:in `new_redis_pool'
    /Users/davidwessman/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/config.rb:130:in `local_redis_pool'
    /Users/davidwessman/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/config.rb:124:in `redis_pool'
    /Users/davidwessman/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/job.rb:368:in `build_client'
    /Users/davidwessman/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/job.rb:361:in `client_push'
    /Users/davidwessman/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/job.rb:198:in `perform_async'
    /Users/davidwessman/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/job.rb:286:in `perform_async'
    /Users/davidwessman/programming/project/test/models/document_test.rb:307:in `block in <class:DocumentTest>'


rails test test/models/document_test.rb:305



Finished in 2.758148s, 0.3626 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

Sidekiq: 7.1.0
Rails 6.1

**Comment by mperham** [comment]
Unfortunately Sidekiq has to create the redis pool even when running fake or inline because it executes client middleware, which takes the pool as an argument. You can set the log level to Logger::WARN to avoid seeing the log output.

```ruby
# test/helper.rb
Sidekiq.configure_client do |cfg| 
  cfg.logger.level = ::Logger::WARN
end
```
