### ISSUE TITLE
Attempting to connect to local redis during tests related to Sidekiq::Web

### ISSUE THREAD

**Issue by maurercw** [sidekiq/sidekiq#5930]
Ruby: 3.1.2
Rails: 7.0.4.3
Sidekiq: 7.1.0

I've seen similar issues brought up before (#1907, #5198, #5652)...

It seems like trying to do anything with the routes in Sidekiq::Web still require a running redis instance, despite any fake/inline/disable settings.

I've got a few "extra" things I'm trying to test around those sidekiq dashboard endpoints, such as a security constraint, as well as a few extra response headers I'm adding.
Looks like it's just trying to call INFO from redis, probably to display the server details in the page footer.

Relevant bit of the call stack:
```
2023-05-22T19:46:16.202Z pid=99862 tid=27y2 INFO: Sidekiq 7.1.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil, :password=>nil}

Minitest::UnexpectedError: RedisClient::CannotConnectError: Connection refused - connect(2) for 127.0.0.1:6379
    /Users/chmaurer/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock'
    /Users/chmaurer/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
    /Users/chmaurer/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
    /Users/chmaurer/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:137:in `connect'
    /Users/chmaurer/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
    /Users/chmaurer/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:227:in `each'
    /Users/chmaurer/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:227:in `foreach'
    /Users/chmaurer/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:632:in `tcp'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection.rb:111:in `connect'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection.rb:49:in `initialize'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client.rb:671:in `new'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client.rb:671:in `block in connect'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client/middlewares.rb:12:in `connect'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client.rb:670:in `connect'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client.rb:657:in `raw_connection'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client.rb:624:in `ensure_connected'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client.rb:209:in `call'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.14.1/lib/redis_client/decorator.rb:26:in `call'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/config.rb:141:in `block in redis_info'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/config.rb:160:in `block in redis'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:107:in `block (2 levels) in with'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `handle_interrupt'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `block in with'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `handle_interrupt'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `with'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/config.rb:157:in `redis'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/config.rb:140:in `redis_info'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/web/helpers.rb:183:in `redis_info'
    /Users/chmaurer/src/ess-lms-cqdm-app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.0/lib/sidekiq/web/application.rb:58:in `block in <class:WebApplication>'
```

Anything I can do to convince it that I don't care about a running redis for these tests?

**Comment by maurercw** [comment]
Yes, doing a `get "/sidekiq"`
I mocked my way around it, which I know that you discourage elsewhere.

If the fake mode could apply to the Web UI side of things, that'd be helpful, but I certainly understand that it might not be a large enough use case to justify it.

**Comment by mperham** [comment]
The purpose of the Web UI is to show you the job data within Redis. It doesn't make sense for Sidekiq::Web to have a fake mode. If you want to test it, you'll need to start Redis first.

**Comment by maurercw** [comment]
Well, I could argue that same point for any web ui.  But when I run tests, I don't expect it to try and talk to my live database.  A test database is provided.  I was just hoping that a test redis could be provided here as well.
It's no biggie as I worked around it.

**Comment by mperham** [comment]
You can configure your test environment to use a separate Redis database. It’s just not automatic.

**Comment by kamil-kudra** [comment]
@mperham So how is it possible that in Sidekiq 6 I had a test that checked the authorization of the web dashboard and it passed without any problems, and after updating to Sidekiq 7, only this one test fails because it cannot connect to Redis, which was never present in the test environment?
