### ISSUE TITLE
7.1.2 JSON ParserError - enqueued_at regex

### ISSUE THREAD

**Issue by pineman** [sidekiq/sidekiq#5937]
Ruby version: 3.2.2
Rails version: 7.0.5
Sidekiq / Pro / Enterprise version(s): 7.1.1 / 7.1.2 / NA

Hi.
Since 7.1.2 we've been getting JSON ParserErrors occasionally: 
<details>
  <summary>JSON ParserError</summary>

  ```js
 JSON::ParserError: unexpected token at '{"job_class":"Searchkick::ReindexV2Job","job_id":"d6bd8fed-0a3b-4879-a52b-90b5737f51d3","provider_job_id":null,"queue_name":"searchkick","priority":null,"arguments":["Person","0ccc6884-1725-448a-905c-2913204b20b8",null,{"routing":null,"index_name":"people_production","_aj_ruby2_keywords":["routing","index_name"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":1685610004.3879483-05-23T19:58:15Z","metadata":[["traceparent","00-fa8d952f24b5ee23c2459552d14da20c-15acf7b98605295a-01"]]}],"jid":"3f19bbfe49300eb24d8e3a1f","created_at":1684871895.8769717,"unique_token":"ae532b53fe8be8b47c0387d91d9cef031565eb6e","unlocks_at":"1684873695.877006","traceparent":"00-fa8d952f24b5ee23c2459552d14da20c-5f62628196a8ab18-01","enqueued_at":1685610004.3879483,"error_message":"PG::QueryCanceled: ERROR:  canceling statement due to statement timeout\n","error_class":"ActiveRecord::QueryCanceled","failed_at":1684872396.355964,"retry_count":20,"retried_at":1685449796.5775888}'
	/opt/rbenv/versions/3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `parse'
	/opt/rbenv/versions/3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `parse'
	/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.1/lib/sidekiq.rb:53:in `load_json'
	/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.1/lib/sidekiq/processor.rb:159:in `process'
	/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.1/lib/sidekiq/processor.rb:82:in `process_one'
	/app/vendor/bundle/ruby/3.2.0/gems/opentelemetry-instrumentation-sidekiq-0.22.0/lib/opentelemetry/instrumentation/sidekiq/patches/processor.rb:21:in `block in process_one'
	/app/vendor/bundle/ruby/3.2.0/gems/opentelemetry-common-0.19.6/lib/opentelemetry/common/utilities.rb:87:in `block in untraced'
	/app/vendor/bundle/ruby/3.2.0/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace.rb:72:in `block in with_span'
	/app/vendor/bundle/ruby/3.2.0/gems/opentelemetry-api-1.1.0/lib/opentelemetry/context.rb:87:in `with_value'
	/app/vendor/bundle/ruby/3.2.0/gems/opentelemetry-api-1.1.0/lib/opentelemetry/trace.rb:72:in `with_span'
	/app/vendor/bundle/ruby/3.2.0/gems/opentelemetry-common-0.19.6/lib/opentelemetry/common/utilities.rb:87:in `untraced'
	/app/vendor/bundle/ruby/3.2.0/gems/opentelemetry-instrumentation-sidekiq-0.22.0/lib/opentelemetry/instrumentation/sidekiq/patches/processor.rb:21:in `process_one'
	/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.1/lib/sidekiq/processor.rb:72:in `run'
	/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.1/lib/sidekiq/component.rb:10:in `watchdog'
	/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.1/lib/sidekiq/component.rb:19:in `block in safe_thread' 
  ```
</details>

We note that in all cases of `JSON::ParserError`, the jobs were submitted via ActiveJob and the job failed because an error was raised; the error itself does not matter as we've seen a few variations.

This seems to be the relevant part of the malformed JSON: 
```
"enqueued_at":1685610004.3879483-05-23T19:58:15Z"
```
Note the missing quotes at the beginning & strange datetime format.

We tracked it down to this sidekiq-pro line in `lib/sidekiq/pro/scripting.rb:67`:

```
jobstr = string.gsub(jobstr, '("enqueued_at":)"?[1-9][0-9.]+"?', '%1' .. now)
```
we believe this was introduced in https://github.com/sidekiq/sidekiq/issues/4768#issuecomment-1561682780 to support Strings instead of just Floats. In 7.1.1, it was:
```
jobstr = string.gsub(jobstr, '("enqueued_at":)[1-9][0-9.]+', '%1' .. now)
```

Running some experiments in lua we reproduced the issue:
```lua
jobstr = "\"enqueued_at\":\"2023-06-01T10:12:23Z\""
now = 1685613787.3429854

jobstr=string.gsub(jobstr, '("enqueued_at":)[1-9][0-9.]+', '%1' .. now)
print(jobstr)
-- "enqueued_at":"2023-06-01T10:29:52Z"
jobstr=string.gsub(jobstr, '("enqueued_at":)"?[1-9][0-9.]+"?', '%1' .. now)
print(jobstr)
-- "enqueued_at":1685613787.343-06-01T10:29:52Z"
```

It seems to us like the regex is not working as intended, as it matches & replaces the first four digits of the year `2023`, but then keeps the rest of the string - trailing quote `"` included. (side note, it also seems like `now` was rounded to `1685613787.343`?)

Let me know if this is an oversight on our part or if more info is needed. Thank you!

**Comment by mperham** [comment]
Can you determine how the value is set to a timestamp string? It should only ever be a Float, eg 123456789.143546. The regexp change was to support String floats, eg "123456789.143546".

**Comment by pineman** [comment]
@mperham I believe it comes from active_job: https://github.com/rails/rails/blob/d026af43c35c25814b4d16511f1b8fc6d70a4569/activejob/lib/active_job/core.rb#L118

**Comment by mperham** [comment]
I don't know what to do about the conflict between Sidekiq and ActiveJob over the `enqueued_at` value. Sidekiq stores timestamps as Floats, i.e. `Time.now.to_f`. ActiveJob is using an ISO8601 timestamp. Both are reasonable choices and have their tradeoffs.

**Comment by pineman** [comment]
Thank you @mperham! We're rolling out 7.1.3 as we speak.
