### ISSUE TITLE
no implicit conversion of Sidekiq::Config into Hash

### ISSUE THREAD

**Issue by imarquezc** [sidekiq/sidekiq#5948]
Ruby version:` ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]`
Rails version: `Rails 6.1.7.2`
Sidekiq / Pro / Enterprise version(s): `sidekiq (7.1.2)`

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

Hello there, I'm trying to upgrade from sidekiq 6.5.7 to 7.1.2 and when I try to boot sidekiq I get the following error.
I'm trying to find something related to this but I'm out of luck. Any help would be very much appreciated.
Thanks.

Details:

redis.yml:
```
development: &default
  url: <%= ENV.fetch("REDIS_URL") %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

test:
  <<: *default

production: &deploy
  url: <%= ENV.fetch("REDIS_URL", "") %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
```

sidekiq.rb
```
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

redis_config = Rails.application.config_for(:redis)

Sidekiq.configure_client do |config|
  config.redis = redis_config
end
Sidekiq.configure_server do |config|
  config.redis = redis_config
end

if !Rails.env.development?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == ENV["SIDEKIQ_ADMIN_PASSWORD"]
  end
end
```

sidekiq.yml
```
:concurrency: <%= Integer(ENV.fetch("SIDEKIQ_CONCURRENCY", 20)) %>
:queues:
  - critical
  - high_priority
  - default
  - low_priority
```

error:
`❯ bundle exec sidekiq -C ./config/sidekiq/sidekiq.yml`

```
2023-06-23T20:53:31.989Z pid=70062 tid=1ofq INFO: Booted Rails 6.1.7.2 application in development environment
2023-06-23T20:53:31.989Z pid=70062 tid=1ofq INFO: Running in ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
2023-06-23T20:53:31.989Z pid=70062 tid=1ofq INFO: See LICENSE and the LGPL-3.0 for licensing details.
2023-06-23T20:53:31.989Z pid=70062 tid=1ofq INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2023-06-23T20:53:31.990Z pid=70062 tid=1ofq INFO: Sidekiq 7.1.2 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://127.0.0.1:55159/1"}
2023-06-23T20:53:32.031Z pid=70062 tid=1ofq INFO: Sidekiq 7.1.2 connecting to Redis with options {:size=>8, :pool_name=>"default", :url=>"redis://127.0.0.1:55159/1"}
2023-06-23T20:53:32.039Z pid=70062 tid=1ofq WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup","_config":{"labels":"#<Set: {}>","require":".","environment":"development","concurrency":8,"timeout":25,"poll_interval_average":null,"average_scheduled_poll_interval":5,"on_complex_arguments":"raise","error_handlers":["#<Proc:0x0000000104fc9f18 /Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.2/lib/sidekiq/config.rb:37 (lambda)>","#<Sentry::Sidekiq::ErrorHandler:0x0000000106525628>"],"death_handlers":[],"lifecycle_events":{"startup":["#<Proc:0x00000001071f0f88 /Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:14>"],"quiet":["#<Proc:0x00000001071f0f10 /Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:31>"],"shutdown":[],"heartbeat":[],"beat":["#<Proc:0x0000000104a7f0f8 /Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.2/lib/sidekiq/metrics/tracking.rb:133>"]},"dead_max_jobs":10000,"dead_timeout_in_seconds":15552000,"reloader":"#<Sidekiq::Rails::Reloader @app=Plutto::Application>","backtrace_cleaner":"#<Proc:0x00000001122ae078 /Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.2/lib/sidekiq/rails.rb:59 (lambda)>","queues":[["case_tracking_details",9],["case_tracking",1]],"config_file":"./config/sidekiq/sidekiq.yml","tag":"plutto-kyb","identity":"Ignacios-MacBook-Pro-3.local:70062:6d71df850d59","listened_queues_only":null}}
2023-06-23T20:53:32.039Z pid=70062 tid=1ofq WARN: TypeError: no implicit conversion of Sidekiq::Config into Hash
2023-06-23T20:53:32.039Z pid=70062 tid=1ofq WARN: 
no implicit conversion of Sidekiq::Config into Hash
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/manager.rb:40:in `merge'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/manager.rb:40:in `load_scheduler_options'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/manager.rb:21:in `initialize'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:21:in `new'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:21:in `block (2 levels) in <main>'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.2/lib/sidekiq/component.rb:60:in `block in fire_event'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.2/lib/sidekiq/component.rb:59:in `each'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.2/lib/sidekiq/component.rb:59:in `fire_event'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.2/lib/sidekiq/cli.rb:106:in `run'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sidekiq-7.1.2/bin/sidekiq:31:in `<top (required)>'
/Users/nacx/.rbenv/versions/3.1/bin/sidekiq:25:in `load'
/Users/nacx/.rbenv/versions/3.1/bin/sidekiq:25:in `<top (required)>'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `load'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:23:in `run'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:483:in `exec'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:31:in `dispatch'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:25:in `start'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/Users/nacx/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
/Users/nacx/.rbenv/versions/3.1/bin/bundle:25:in `load'
/Users/nacx/.rbenv/versions/3.1/bin/bundle:25:in `<main>'
```
If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by imarquezc** [comment]
Nevermind.. I needed to upgrate sidekiq-scheduler too.. Im sorry.
