### ISSUE TITLE
SIDEKIQ Time out on remote redis server. 

### ISSUE THREAD

**Issue by tooney92** [sidekiq/sidekiq#5963]
Ruby version: 3.0.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.1.2

I am trying to use Sidekiq and I keep getting this issue in the sidekiq logs: 

```
2023-07-06T21:56:35.610Z pid=4568 tid=1adc WARN: Your Redis network connection is performing extremely poorly.
Last RTT readings were [204478, 204233, 207602, 245868, 208387], ideally these should be < 1000.
Ensure Redis is running in the same AZ or datacenter as Sidekiq.
If these values are close to 100,000, that means your Sidekiq process may be
CPU-saturated; reduce your concurrency and/or see https://github.com/sidekiq/sidekiq/discussions/5039

2023-07-06T21:57:29.608Z pid=4568 tid=1adc WARN: Your Redis network connection is performing extremely poorly.
Last RTT readings were [204816, 203731, 205889, 262611, 206089], ideally these should be < 1000.
Ensure Redis is running in the same AZ or datacenter as Sidekiq.
If these values are close to 100,000, that means your Sidekiq process may be
CPU-saturated; reduce your concurrency and/or see https://github.com/sidekiq/sidekiq/discussions/5039

2023-07-06T21:58:23.307Z pid=4568 tid=1adc WARN: Your Redis network connection is performing extremely poorly.
Last RTT readings were [209074, 205709, 205650, 203779, 275402], ideally these should be < 1000.
Ensure Redis is running in the same AZ or datacenter as Sidekiq.
If these values are close to 100,000, that means your Sidekiq process may be
CPU-saturated; reduce your concurrency and/or see https://github.com/sidekiq/sidekiq/discussions/5039


```

I am comfortable exposing my redis-server host info, it's a free server on Redis labs. Yesterday I used the same server with no issues. Funny thing is everything runs fine on my local redis. 

Again when i use the web UI, selecting 'busy' tab breaks the app. This is my server log:

```
Started GET "/sidekiq/busy" for ::1 at 2023-07-06 23:02:44 +0100
  
NoMethodError (undefined method `each_pair' for []:Array
Did you mean?  each_slice):
  
sidekiq (7.1.2) lib/sidekiq/api.rb:1112:in `block in each'
sidekiq (7.1.2) lib/sidekiq/api.rb:1111:in `each'
sidekiq (7.1.2) lib/sidekiq/api.rb:1111:in `each'
sidekiq (7.1.2) lib/sidekiq/paginator.rb:51:in `to_a'
sidekiq (7.1.2) lib/sidekiq/paginator.rb:51:in `page_items'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:90:in `block in <class:WebApplication>'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:338:in `instance_exec'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:338:in `block in call'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:336:in `catch'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:336:in `call'
sidekiq (7.1.2) lib/sidekiq/web/csrf_protection.rb:52:in `admit'
sidekiq (7.1.2) lib/sidekiq/web/csrf_protection.rb:41:in `call'
rack (2.2.6.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.6.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/cookies.rb:704:in `call'
rack (2.2.6.2) lib/rack/static.rb:161:in `call'
rack (2.2.6.2) lib/rack/builder.rb:244:in `call'
sidekiq (7.1.2) lib/sidekiq/web.rb:105:in `call'
sidekiq (7.1.2) lib/sidekiq/web.rb:110:in `call'
actionpack (7.0.4.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.4.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:852:in `call'
bullet (7.0.7) lib/bullet/rack.rb:17:in `call'
rack (2.2.6.2) lib/rack/etag.rb:27:in `call'
rack (2.2.6.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.6.2) lib/rack/head.rb:12:in `call'
activerecord (7.0.4.2) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.4.2) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.4.2) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.6.2) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.6.2) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
rack-cors (2.0.0) lib/rack/cors.rb:102:in `call'
railties (7.0.4.2) lib/rails/engine.rb:530:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

```

This is my initializer: 

```

Sidekiq.configure_server do |config|
  if Rails.env.production?
    puts 'Using prod redis for sidekiq'
    config.redis = { url: "redis://#{ENV.fetch('REDIS_PROD_HOST')}:6379" }
  else
    puts 'Inside development block'
    # config.redis = { url: "redis://#{ENV.fetch('REDIS_DEV_HOST')}:6379"}
    # config.redis = {
    #   url: "redis://default:JK1merwMQEdDEu8vFQcgiOe0FGJ6O6cx@redis-13468.c84.us-east-1-2.ec2.cloud.redislabs.com:13468",
    #   protocol: 2
    # }
    config.redis = { url: "redis://default:JK1merwMQEdDEu8vFQcgiOe0FGJ6O6cx@redis-13468.c84.us-east-1-2.ec2.cloud.redislabs.com:13468",
                     network_timeout: 5,
                     pool_timeout: 5,
                     protocol: 2,
                     size: 22
    }
  end
end

Sidekiq.configure_client do |config|
  if Rails.env.production?
    puts 'Using prod redis for sidekiq'
    config.redis = { url: "redis://#{ENV.fetch('REDIS_PROD_HOST')}:6379" }
  else
    puts 'Inside development block'
    # config.redis = { url: "redis://#{ENV.fetch('REDIS_DEV_HOST')}:6379"}
    config.redis = {
      url: "redis://default:JK1merwMQEdDEu8vFQcgiOe0FGJ6O6cx@redis-13468.c84.us-east-1-2.ec2.cloud.redislabs.com:13468",
      protocol: 2
    }
  end
end

```

This is my sidekiq.yml:

```
:verbose: true
:concurrency: 5
:queues:
  - [og_erp_development_default, 5]
  - [og_erp_development_mailers, 5]
  - [og_erp_production_mailers, 5]
  - [og_erp_production, 7]
  - [default, 5]
```

I really need all the help I can get. I am supposed to prove to management why we need sidekiq so we can get the PRO version. But these issues are making it a hard sell.

**Comment by mperham** [comment]
I think the each_pair error can occur if you mix versions. Make sure all Sidekiq processes are using the same version.

As for performance, I think you answered it when you mentioned it was a free VM. There are many different environmental reasons for slow performance and that's one.

**Comment by tooney92** [comment]
@mperham Thanks for replying.  "Make sure all Sidekiq processes are using the same version." How do I do this? I am quite new to sidekiq. 

Also, Even on the redis-server hosted on AWS by my company, I still have this issue. 

The each-pair error doesn't happen when I use my local Redis. It's only the remote Redis.

**Comment by tooney92** [comment]
I have only 1 process with 5 worker threads.

**Comment by mperham** [comment]
How many connections does a free Redis allow?

I can't really debug environmental issues via GitHub and these kinds of performance issues are always environmental. I can't explain why that Redis takes 200ms to respond.

**Comment by tooney92** [comment]
I have only 1 process with 5 worker threads. 

Also, I connect to this same server with redis insight and the latency logs show it's well below 1000ms. Jobs are not even being enqueued. It's just strange how it worked fine the previous day. 
 
 This is how I create the jobs. 

```
module AttendanceManager
  class GenerateAttendance < ApplicationService

    def initialize(day = Date.today.prev_day.strftime('%Y-%m-%d'))
      @day = day
    end

    def call

      total_users = 0
      return if attendance_processed?

      deduction_types = Hr::DeductionType.all
      Hr::User.includes(employee: :salaries).where({status: 1, employee: { remote: false }}).find_in_batches(batch_size: 100) do |group|
        sleep(1)
        group.each do |user|
          json_arguments = { user: user.id, deduction_types: deduction_types, day: @day }
          ProcessAttendanceJob.perform_async(json_arguments.to_json)
          total_users += 1
        end
        ActiveRecord::Base.connection.clear_query_cache
      end

      ProcessedAttendance.create!({total_records: total_users, created_at: @day})

    end

    def attendance_processed?
      day =  Date.parse(@day)
      ProcessedAttendance.where(created_at: day.beginning_of_day..day.end_of_day).exists?
    end
  end
end

```
 This is the Job:
 
 ```
class ProcessAttendanceJob
  include Sidekiq::Job

  def perform(payload)

    payload = JSON.parse(payload)
    result = Struct.new(:id, :percentage, :title, :operation_office_id )
    payload['deduction_types'] = payload['deduction_types'].map do |deduction_type|
      result.new(
        deduction_type["id"],
        deduction_type["percentage"],
        deduction_type["title"],
        deduction_type["operation_office_id"],
      )
    end

    user = Hr::User.includes(employee: :salaries).find(payload['user'])

    AttendanceManager::ProcessAttendance.call(
      user,
      payload['day'],
      AttendanceManager::BiometricAttendanceFetcher.new(payload['day']),
      payload['deduction_types']
    )

  end
end

```

**Comment by tooney92** [comment]
> How many connections does a free Redis allow?
> 
> I can't really debug environmental issues via GitHub and these kinds of performance issues are always environmental. I can't explain why that Redis takes 200ms to respond.

It's strange because I tried the 2 redis-servers hosted on AWS. AZ in Europe(closer to me). Same issues.  Again, I had used this same free redis-server and it worked just fine.

**Comment by mperham** [comment]
I see you have size in your initializer. Remove it and let Sidekiq control the Redis pool size.

**Comment by tooney92** [comment]
Thanks @mperham I have removed the size. And now it's processing per the sidekiq logs. 

However the webUI isn't showing that any job is enqueued, but the processed section is increasing. Usually, it shows me enqueued jobs, the number of busy. Now those figures are Zero.

**Comment by tooney92** [comment]
What is even weird is that it logs SQL queures being made in my sidekiq logs. However running  ps aux | grep sidekiq shows this:

```
legal-debugger    6127   8.8  0.7 35901616 226988 s000  S+   10:05AM   0:15.52 sidekiq 7.1.2 OGTL-NEW-ERP-BACKEND [0 of 5 busy]     
legal-debugger    6394   0.0  0.0 33589096    292 s002  R+   10:10AM   0:00.00 grep sidekiq

```

**Comment by tooney92** [comment]
Also, navigating to busy still breaks the app with no each pair complaint.  Even when it shows 1 busy. 

```
NoMethodError (undefined method `each_pair' for []:Array
Did you mean?  each_slice):
  
sidekiq (7.1.2) lib/sidekiq/api.rb:1112:in `block in each'
sidekiq (7.1.2) lib/sidekiq/api.rb:1111:in `each'
sidekiq (7.1.2) lib/sidekiq/api.rb:1111:in `each'
sidekiq (7.1.2) lib/sidekiq/paginator.rb:51:in `to_a'
sidekiq (7.1.2) lib/sidekiq/paginator.rb:51:in `page_items'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:90:in `block in <class:WebApplication>'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:338:in `instance_exec'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:338:in `block in call'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:336:in `catch'
sidekiq (7.1.2) lib/sidekiq/web/application.rb:336:in `call'
sidekiq (7.1.2) lib/sidekiq/web/csrf_protection.rb:52:in `admit'
sidekiq (7.1.2) lib/sidekiq/web/csrf_protection.rb:41:in `call'
rack (2.2.6.2) lib/rack/static.rb:161:in `call'
rack (2.2.6.2) lib/rack/builder.rb:244:in `call'
sidekiq (7.1.2) lib/sidekiq/web.rb:105:in `call'
sidekiq (7.1.2) lib/sidekiq/web.rb:110:in `call'
actionpack (7.0.4.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.4.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:852:in `call'
bullet (7.0.7) lib/bullet/rack.rb:17:in `call'
rack (2.2.6.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.6.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/cookies.rb:704:in `call'
rack (2.2.6.2) lib/rack/etag.rb:27:in `call'
rack (2.2.6.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.6.2) lib/rack/head.rb:12:in `call'
activerecord (7.0.4.2) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.4.2) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.4.2) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.6.2) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.6.2) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
rack-cors (2.0.0) lib/rack/cors.rb:102:in `call'
railties (7.0.4.2) lib/rails/engine.rb:530:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

```

**Comment by mperham** [comment]
It’s because you are using protocol 2 which is not supported in Sidekiq 7.

**Comment by mperham** [comment]
The more you “tune” in the initializer, the bigger chance you have to break something.

**Comment by tooney92** [comment]
> It’s because you are using protocol 2 which is not supported in Sidekiq 7.

Could this be why I am getting the connection issues?

Without protocol 2 added I was getting a Hello command error. That's why I added it.

**Comment by tooney92** [comment]
> What is even weird is that it logs SQL queures being made in my sidekiq logs. However running ps aux | grep sidekiq shows this:
> 
> ```
> legal-debugger    6127   8.8  0.7 35901616 226988 s000  S+   10:05AM   0:15.52 sidekiq 7.1.2 OGTL-NEW-ERP-BACKEND [0 of 5 busy]     
> legal-debugger    6394   0.0  0.0 33589096    292 s002  R+   10:10AM   0:00.00 grep sidekiq
> ```
> 
> 0 of 5 busy. How is this possible?


Any idea why this is even possible?

**Comment by mperham** [comment]
The HELLO error is because RedisLabs does not yet support RESP3 and Sidekiq 7. You’ll need to use Sidekiq 6 if you want to use RedisLabs. They expect support this month afaik. There are numerous issues about this, please search.

**Comment by tooney92** [comment]
Thanks @mperham for the help. I will factor in all ur feedback.

**Comment by anthugny** [comment]
opk
