### ISSUE TITLE
SystemStackError in rails routes on upgrading to 7.1.2

### ISSUE THREAD

**Issue by krainboltgreene** [sidekiq/sidekiq#5964]
Ruby version: 3.1.2
Rails version: 7.0.6
Sidekiq / Pro / Enterprise version(s): 7.1.2

We upgraded recently from `~> 6.5`. We're bisecting backwards to find out. It *only* happens in production. I don't think you'll be able to assist, but I figure I might as well get some documentation started in case someone else runs into this.

``` ruby
bundler: failed to load command: sidekiq (/usr/local/bundle/ruby/3.1.0/bin/sidekiq)
/usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:167:in `visit': stack level too deep (SystemStackError)
	from /usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:110:in `binary'
	from /usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:112:in `visit_CAT'
	from /usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:106:in `visit'
	from /usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:167:in `visit'
	from /usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:120:in `unary'
	from /usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:122:in `visit_GROUP'
	from /usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:106:in `visit'
	from /usr/local/bundle/ruby/3.1.0/gems/actionpack-7.0.6/lib/action_dispatch/journey/visitors.rb:167:in `visit'
	... 10442 levels...
	from /usr/local/bundle/ruby/3.1.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/ruby/3.1.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
```

**Comment by mperham** [comment]
It would help to include relevant portions of routes.rb.

**Comment by krainboltgreene** [comment]
That's incredibly hard in the current environment. We've narrowed it down to: https://github.com/sidekiq/sidekiq/compare/v7.0.6...v7.0.7

**Comment by krainboltgreene** [comment]
I don't know how routes are involved, but it appears to be that on v7.0.7 and above when we have this custom logger logic it SystemStackError's:

``` ruby
  config.logger = ActiveSupport::Logger.new($stdout)
                                       .tap { |logger| logger.formatter = JSONLogFormatter.new }
                                       .then { |logger| TaggedLogging.new(logger) }
```

**Comment by krainboltgreene** [comment]
Alright I've narrowed it down. It's a combination of a few factors:

  1. https://github.com/sidekiq/sidekiq/commit/b74dee46fd2b98f0ef415a64bf2df5b42bdbc2d7#diff-0c49098f0471d2ffa897441bd05c7d24c04ce480e66cb534b194a4bb15e0b201R40 started logging
  2. My replacing whole sale of the logger wiped any log level changes, now sidekiq is trying to print out routes
  3. Infinite loop
