### ISSUE TITLE
Sidekiq scheduler not working after a unexpected database reboot

### ISSUE THREAD

**Issue by louman** [sidekiq/sidekiq#6004]
Ruby version: 2.7.8
Rails version: 4.2.11
Sidekiq / Pro / Enterprise version(s): 5.2.8

The other day we had an unexpected reboot of our RDS instances and after the databases went back up, we noticed that `sidekiq-cron` stopped working. We added several `Sidekiq.logger.error` throughout both gems and simulated a reboot again. What we found was that both sidekiq-cron's poller, which inherits from `Sidekiq::Scheduled::Poller` and sidekiq's own poller stopped working. 

You may ask how do we know that. Our debugging stopped coming out in the logs and failed jobs weren't being retried. We then rebooted sidekiq which solves the problem however it's not a feasible option for us. 

After the reboot, we sent a `-TTIN` signal to spit out the threads which showed up just fine on the logs, including a debug logger we added in:

```
SIGNAL_HANDLERS = {
      # Ctrl-C in terminal
      'INT' => ->(cli) { raise Interrupt },
      # TERM is the signal that Sidekiq must exit.
      # Heroku sends TERM and then waits 30 seconds for process to exit.
      'TERM' => ->(cli) { raise Interrupt },
      'USR1' => ->(cli) {
        Sidekiq.logger.info "Received USR1, no longer accepting new work"
        cli.launcher.quiet
      },
      'TSTP' => ->(cli) {
        Sidekiq.logger.info "Received TSTP, no longer accepting new work"
        cli.launcher.quiet
      },
      'USR2' => ->(cli) {
        if Sidekiq.options[:logfile]
          Sidekiq.logger.info "Received USR2, reopening log file"
          Sidekiq::Logging.reopen_logs
        end
      },
      'TTIN' => ->(cli) {
Sidekiq.logger.info("cliclicli")
        Thread.list.each do |thread|
          Sidekiq.logger.warn "Thread TID-#{(thread.object_id ^ ::Process.pid).to_s(36)} #{thread['sidekiq_label']}"
          if thread.backtrace
            Sidekiq.logger.warn thread.backtrace.join("\n")
          else
            Sidekiq.logger.warn "<no backtrace available>"
          end
        end
      },
    }
```

We then proceeded to reboot the db again to simulate the issue. We then sent a `TTIN` sign again however this time, nothing came out in the logs, not even the `cliclicli` info log.

We kinda exhausted all debug options so just wondering if anyone has seen this issue before or have any idea on how to further debug it.

**Comment by louman** [comment]
I can confirm that the threads are indeed being killed when the database connection is lost. Question, why isn't sidekiq designed to recreate the threads if they die?

```
#<Thread:0x000000010931ec50 /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/util.rb:25 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
  27: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/util.rb:28:in `block in safe_thread'
  26: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/util.rb:17:in `watchdog'
  25: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/scheduled.rb:72:in `block in start'
  24: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/scheduled.rb:93:in `wait'
  23: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:546:in `error'
  22: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:475:in `add'
  21: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:585:in `format_message'
  20: from /Users/****/Projects/****/config/initializers/sidekiq.rb:77:in `call'
  19: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/forwardable.rb:235:in `current'
  18: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/apartment-2.2.1/lib/apartment/adapters/abstract_adapter.rb:38:in `current'
  17: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:400:in `current_database'
  16: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:43:in `select_value'
  15: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:38:in `select_one'
  14: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
  13: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  12: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
  11: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:221:in `exec_query'
  10: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
   9: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
   8: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
   7: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
   6: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
   5: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
   4: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-3.1.0/lib/patches/db/mysql2/alias_method.rb:22:in `query'
   3: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
   2: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
   1: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query': MySQL server has gone away (Mysql2::Error::ConnectionError)
  27: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/util.rb:28:in `block in safe_thread'
  26: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/util.rb:17:in `watchdog'
  25: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/scheduled.rb:72:in `block in start'
  24: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/scheduled.rb:93:in `wait'
  23: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:546:in `error'
  22: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:475:in `add'
  21: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:585:in `format_message'
  20: from /Users/****/Projects/****/config/initializers/sidekiq.rb:77:in `call'
  19: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/forwardable.rb:235:in `current'
  18: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/apartment-2.2.1/lib/apartment/adapters/abstract_adapter.rb:38:in `current'
  17: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:400:in `current_database'
  16: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:43:in `select_value'
  15: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:38:in `select_one'
  14: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
  13: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  12: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
  11: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:221:in `exec_query'
  10: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
   9: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
   8: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
   7: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
   6: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
   5: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
   4: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-3.1.0/lib/patches/db/mysql2/alias_method.rb:22:in `query'
   3: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
   2: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
   1: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query': Mysql2::Error::ConnectionError: MySQL server has gone away: SELECT DATABASE() as db (ActiveRecord::StatementInvalid)
  28: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/util.rb:28:in `block in safe_thread'
  27: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/util.rb:17:in `watchdog'
  26: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/scheduled.rb:72:in `block in start'
  25: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/scheduled.rb:92:in `wait'
  24: from /Users/****/Projects/****/local_gems/sidekiq/lib/sidekiq/scheduled.rb:100:in `rescue in wait'
  23: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:546:in `error'
  22: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:475:in `add'
  21: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/logger.rb:585:in `format_message'
  20: from /Users/****/Projects/****/config/initializers/sidekiq.rb:77:in `call'
  19: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/2.7.0/forwardable.rb:235:in `current'
  18: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/apartment-2.2.1/lib/apartment/adapters/abstract_adapter.rb:38:in `current'
  17: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:400:in `current_database'
  16: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:43:in `select_value'
  15: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:38:in `select_one'
  14: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
  13: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  12: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
  11: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:221:in `exec_query'
  10: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
   9: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
   8: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
   7: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
   6: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
   5: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
   4: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-3.1.0/lib/patches/db/mysql2/alias_method.rb:22:in `query'
   3: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
   2: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
   1: from /Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/Users/****/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query': MySQL client is not connected (Mysql2::Error)
```

**Comment by louman** [comment]
I managed to figure out what was going on. 

We are using the `apartment` gem for multitenancy and `apartment-sidekiq` to inject the current tenant in the sidekiq jobs. The latter adds a middleware that invokes the database to retrieve the tenant information. If the connect has been lost, it will raise an error and cause the poller thread to die. 

The solution was to monkeypatch the middleware, rescue the error, attempt to reconnect and retry the operation. It's not perfect but it's a good workaround for a problem that has only occurred once in 10 years for us.
