### ISSUE TITLE
Sidekiq trying to connect to Redis even if 'sidekiq/testing' is required

### ISSUE THREAD

**Issue by devsheva** [sidekiq/sidekiq#6009]
Ruby version: 3.1.3
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): Standard

**sidekiq.rb initializer**
```ruby
# frozen_string_literal: true
require "sidekiq"
require "sidekiq-status"

redis_config = {
  url: "#{ENV["REDIS_URL"]}/#{REDIS_SIDEKIQ_DB}"
}

Sidekiq.configure_client do |config|
  config.redis = redis_config

  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes.to_i
end

Sidekiq.configure_server do |config|
  config.redis = redis_config

  Sidekiq::Status.configure_server_middleware config, expiration: 30.minutes.to_i
  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes.to_i
end
``` 
**spec_helper.rb**

```ruby
...
 require 'sidekiq-status/testing/inline'

  config.before(:each) do
    Sidekiq::Worker.clear_all
  end
```

my_file_spec.rb
```ruby
require 'rails_helper'
RSpec.describe ExpirationCartJob, type: :job, focus: true do
  it { should be_retryable(false) }

  it { should respond_to(:perform) }
  it "should be able to enqueue a job" do
    expect { described_class.perform_async }.to enqueue_sidekiq_job
  end
end

```

**Full backtrace**

```
2023-08-24T16:36:54.153Z pid=80056 tid=1kx0 INFO: Sidekiq 7.1.2 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"/2"}                        |  ETA: 00:00:01

  1) ExpirationCartJob should be able to enqueue a job
     Failure/Error: expect { described_class.perform_async }.to enqueue_sidekiq_job

     ArgumentError:
       Invalid URL: "/2"
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/redis-client-0.16.0/lib/redis_client/url_config.rb:16:in `initialize'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/redis-client-0.16.0/lib/redis_client/config.rb:165:in `new'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/redis-client-0.16.0/lib/redis_client/config.rb:165:in `initialize'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/redis-client-0.16.0/lib/redis_client.rb:144:in `new'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/redis-client-0.16.0/lib/redis_client.rb:144:in `config'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/redis_client_adapter.rb:52:in `initialize'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/redis_connection.rb:21:in `new'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/redis_connection.rb:21:in `create'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/config.rb:140:in `new_redis_pool'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/config.rb:134:in `local_redis_pool'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/config.rb:128:in `redis_pool'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/job.rb:368:in `build_client'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/job.rb:361:in `client_push'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/job.rb:198:in `perform_async'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/sidekiq-7.1.2/lib/sidekiq/job.rb:286:in `perform_async'
     # ./spec/sidekiq/expiration_cart_job_spec.rb:7:in `block (3 levels) in <main>'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-sidekiq-4.0.1/lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb:23:in `matches?'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-expectations-3.12.3/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-expectations-3.12.3/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-expectations-3.12.3/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-expectations-3.12.3/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-expectations-3.12.3/lib/rspec/expectations/expectation_target.rb:139:in `to'
     # ./spec/sidekiq/expiration_cart_job_spec.rb:7:in `block (2 levels) in <main>'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `instance_exec'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `block in run'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-rails-6.0.3/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `map'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/bin/rspec:25:in `load'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/bin/rspec:25:in `<main>'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/bin/ruby_executable_hooks:22:in `eval'
     # /Users/mateo/.rvm/gems/ruby-3.1.3/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by mperham** [comment]
How do you expect to verify it enqueues a job if it doesn't send that job to Redis?

**Comment by devsheva** [comment]
@mperham  i've already done a similar test in another project and it works fine, anyway in **rspec-sidekiq** docs it says that it already requires **sidekiq-testing**, so it should disable Redis. Also since this would lead to save jobs in an array, i guess the matcher will just check that array. Am i wrong?

**Comment by mperham** [comment]
Well, that error is obvious: you didn't set REDIS_URL for your process.

**Comment by devsheva** [comment]
@mperham I agree with you that I haven't set the REDIS_URL variable, but as I said in sidekiq wiki it's written that requiring sidekiq-testing should avoid Redis. Also as I said I've used the same approach in a different project, that relies on sidekiq 6.x though, so maybe something has changed and I can't find it out. Of course I didn't set the REDIS_URL in the other project.

**Comment by devsheva** [comment]
Just did it, nothing changed. Still same error.

**Comment by mperham** [comment]
Time to break out the debugger. 🤷🏻‍♂️

**Comment by mperham** [comment]
Simplify, start over from the basics:

https://github.com/sidekiq/sidekiq/wiki/Testing#setup

**Comment by devsheva** [comment]
Checked it out, already did and followed it first time I had to setup Sidekiq testing in this project. Nothing changed, I don't have complicated logics to run.

**Comment by davidgm0** [comment]
I'm having an apparently similar issue when updating from `6.5.11` to 7 (either `7.0.9` or `7.2.0`). Fake sidekiq seems to work well in testing in most cases. This passes:

```ruby
    it 'uses sidekiq testing' do
      expect(Sidekiq::Testing.fake?).to be(true)
    end
```

But in this specific piece of code, it tries to connect to redis when before it didn't:

```ruby
  def get_jobs(klass) # klass is Sidekiq::Queue. It can be Sidekiq::ScheduledSet, Sidekiq::RetrySet
    klass.new.to_a
  end
```

This is trying to get enqueued jobs to remove them later. Probably there may be better ways to do it, first time I saw this code. But anyway, `to_a` throws this error:

```
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/ruby_connection.rb:117:in `connect'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/ruby_connection.rb:49:in `initialize'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client.rb:720:in `new'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client.rb:720:in `block in connect'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/middlewares.rb:12:in `connect'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client.rb:719:in `connect'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client.rb:706:in `raw_connection'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client.rb:673:in `ensure_connected'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client.rb:254:in `call'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/redis_client_adapter.rb:36:in `block (2 levels) in <module:CompatMethods>'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/api.rb:252:in `block in size'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/config.rb:163:in `block in redis'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/config.rb:160:in `redis'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq.rb:73:in `redis'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/api.rb:252:in `size'
     # /Users/david/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/api.rb:277:in `each'
     # ./app/services/remove_jobs.rb:41:in `to_a'
```

**Comment by mperham** [comment]
The Sidekiq API always connects to Redis. There is no fake or stub mode for it.

**Comment by davidgm0** [comment]
Are jobs still pushed to redis, even after [sidekiq testing](https://github.com/sidekiq/sidekiq/wiki/Testing#setup) (fake) is enabled?

 > A test fake that pushes all jobs into a jobs array

And, if that wouldn't be the case.. then why  using a different sidekiq version make tests pass or fail? I have tried with `6.5.11` with redis stopped and my tests pass.

**Comment by dgmora** [comment]
Thanks for the info. I further debugged this and it seems that in my case the issue is with [fakeredis](https://github.com/guilleiguaran/fakeredis). 

In both cases with `redis` gem `4.8.1`, sidekiq `7.x` adds `redis-client (0.17.0)`. `fakeredis` isn't mocking the connection in `7.x`, but it was with `6.x`

**Comment by devsheva** [comment]
I fixed my concern by adding this line in `spec_helper.rb`.

```ruby
 # WARN !!! TMP solution, cause seems that sidekiq-status is required somewhere else after testing module is required here
  config.before(:suite) { require 'sidekiq-status/testing/inline' }
```
