### ISSUE TITLE
ERROR HANDLER THREW AN ERROR / only generation of JSON objects or arrays allowed

### ISSUE THREAD

**Issue by bwalton** [sidekiq/sidekiq#6047]
Ruby version: 3.1.3
Rails version: 6.1.7.6
Sidekiq / Pro / Enterprise version(s): 7.1.4, 7.1.4, 7.1.2

initializer
```
Sidekiq::Client.reliable_push!
Sidekiq::Enterprise.unique!

Sidekiq.configure_client do |config|
  config.redis = { url: ENV["REDIS_URL"] } if Rails.env.production?
end

Sidekiq.configure_server do |config|
  config.redis = { url: ENV["REDIS_URL"] } if Rails.env.production?
  config.periodic do |mgr|
    # A bunch of periodic jobs registered here
  end
end
```

sidekiq.yml
```
---
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] %>
:queues:
  - firebase
  - default
  - mailers
```

Backtrace:
```
pid=2 tid=y34gu ERROR: !!! ERROR HANDLER THREW AN ERROR !!! 
pid=2 tid=y34gu ERROR: only generation of JSON objects or arrays allowed 
pid=2 tid=y34gu ERROR: /app/vendor/bundle/ruby/3.1.0/gems/json_pure-2.3.0/lib/json/common.rb:224:in `generate' 
/app/vendor/bundle/ruby/3.1.0/gems/json_pure-2.3.0/lib/json/common.rb:224:in `generate' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:57:in `dump_json' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/rails.rb:25:in `to_json' 
/app/vendor/bundle/ruby/3.1.0/gems/json_pure-2.3.0/lib/json/common.rb:224:in `generate' 
/app/vendor/bundle/ruby/3.1.0/gems/json_pure-2.3.0/lib/json/common.rb:224:in `generate' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:57:in `dump_json' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:60:in `to_json' 
/app/vendor/bundle/ruby/3.1.0/gems/json_pure-2.3.0/lib/json/common.rb:224:in `generate' 
/app/vendor/bundle/ruby/3.1.0/gems/json_pure-2.3.0/lib/json/common.rb:224:in `generate' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:57:in `dump_json' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:40:in `block in <class:Config>' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:269:in `block in handle_exception' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:268:in `each' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:268:in `handle_exception' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:48:in `handle_exception' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:48:in `handle_exception' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:193:in `rescue in block (2 levels) in process' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:178:in `block (2 levels) in process' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:177:in `handle_interrupt' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:177:in `block in process' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:176:in `handle_interrupt' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:176:in `process' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:82:in `process_one' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:72:in `run' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:10:in `watchdog' 
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:19:in `block in safe_thread'
```

Hi everyone,
After upgrading to Sidekiq 7.1.4 (Pro and Ent as well) I'm seeing a bunch of the above in place of normal exceptions.

In production, Honeybadger catches the error like normal and in development I can see the issue in Sidekiq's web UI, but it doesn't show in the dev console. Not the end of the world, just kinda annoying.

I went into `json_pure-2.3.0/lib/json/common.rb:224` and right before `state.generate(obj)`, I threw a `puts obj.inspect` and I get this:
`#<Sidekiq::Rails::Reloader @app=MyApp::Application>`

I'm sure I'm doing something funky so any guidance here would be appreciated.

**Comment by mperham** [comment]
Yes, storing the app in the config hash has turned out to be a poor choice, I need to refactor it.
