### ISSUE TITLE
Customer Job Logger in Sidekiq-ENT 7

### ISSUE THREAD

**Issue by hao-atob** [sidekiq/sidekiq#6048]
Ruby version: 3.2.2
Rails version: 7.0.7.2
Sidekiq / Pro / Enterprise version(s):
sidekiq:  7.1.4
sidekiq-pro: 7.1.4
sidekiq-ent: 7.1.2

We are trying to migrating from 
sidekiq: 6.5.8 -> 7.1.4
sidekiq-ent: 2.5.3 -> 7.1.2
sidekiq-pro: 5.5.5 -> 7.1.4

However, after update our Sidekiq failed to start. Looking into 
```
$> bundle exec sidekiq
undefined method `options' for #<Sidekiq::Config:0x00007f8bb98114a0 @options={:labels=>#<Set: {}>, :require=>".", :environment=>"production", :concurrency=>5, :timeout=>25, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :on_complex_arguments=>:raise, :error_handlers=>[#<Proc:0x00007f8bb98efb10 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:37 (lambda)>, #<Sentry::Sidekiq::ErrorHandler:0x00007f8bad38c8f0>], :death_handlers=>[#<Proc:0x00007f8bb79032c0 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-pro-7.1.4/lib/sidekiq/batch/death.rb:62 (lambda)>, #<Proc:0x00007f8ba4e3e838 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/unique.rb:211 (lambda)>], :lifecycle_events=>{:startup=>[#<Proc:0x00007f8bb70af4e8 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-pro-7.1.4/lib/sidekiq-pro.rb:68>, #<Proc:0x00007f8bb70ac450 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/election.rb:4>, #<Proc:0x00007f8bb7a3c268 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/restart.rb:5>, #<Proc:0x00007f8bb798a220 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent.rb:26>], :quiet=>[#<Proc:0x00007f8bb70af498 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-pro-7.1.4/lib/sidekiq-pro.rb:73>], :shutdown=>[], :heartbeat=>[], :beat=>[#<Proc:0x00007f8bb8ce8100 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/metrics/tracking.rb:133>], :leader=>[#<Proc:0x00007f8bb7089810 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/periodic.rb:88>, #<Proc:0x00007f8bb7a3dcf8 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/census.rb:183>], :fork=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Proc:0x00007f8bb98efbb0 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/config.rb:33>, :backtrace_cleaner=>#<Proc:0x00007f8bb267a0d0 /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/rails.rb:59 (lambda)>, :queues=>["critical", "default", "low", "eventually", "backfill"], :config_file=>"./config/sidekiq.yml", :backup_limit=>1000}, @directory={"pro:metrics"=>#<Sidekiq::Pro::Metrics::Dogstatsd:0x00007f8ba16a1060 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @statsd=#<ConnectionPool:0x00007f8ba0e58d90 @size=10, @timeout=5, @auto_reload_after_fork=true, @available=#<ConnectionPool::TimedStack:0x00007f8ba0e58d40 @create_block=#<Proc:0x00007f8ba16a1100 /app/config/initializers/sidekiq.rb:33 (lambda)>, @created=0, @que=[], @max=10, @mutex=#<Thread::Mutex:0x00007f8ba16a0ef8>, @resource=#<Thread::ConditionVariable:0x00007f8ba16a0ed0>, @shutdown_block=nil>, @key=:"pool-73280", @key_count=:"pool-73280-count">>}, @redis_config={:url=>"rediss://:p83fe30d55ed89262f27ad054c91f8d9a5016fba423073b83499e2df0dd509408@ec2-44-218-38-92.compute-1.amazonaws.com:18369", :ssl_params=>{:verify_mode=>0}}, @capsules={"default"=>#<Sidekiq::Capsule:0x00007f8bb9e5c2b0 @name="default", @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @queues=["critical", "default", "low", "eventually", "backfill"], @weights={"critical"=>0, "default"=>0, "low"=>0, "eventually"=>0, "backfill"=>0}, @concurrency=5, @mode=:strict>}, @server_chain=#<Sidekiq::Middleware::Chain:0x00007f8bb8ce87b8 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @entries=[#<Sidekiq::Middleware::Entry:0x00007f8bb8ce82e0 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sidekiq::Metrics::Middleware, @args=[#<Sidekiq::Metrics::ExecutionTracker:0x00007f8bb9811450 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @jobs={}, @totals={}, @grams={}, @lock=#<Thread::Mutex:0x00007f8bb8ce8858>>]>, #<Sidekiq::Middleware::Entry:0x00007f8bb70a3d00 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sidekiq::Limiter::Middleware, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8ba4e3ea68 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sidekiq::Enterprise::Unique::Server, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8bb790ea80 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sidekiq::Batch::Server, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8bad38c648 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sentry::Sidekiq::SentryContextServerMiddleware, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8ba1fd1fe0 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Datadog::Tracing::Contrib::Sidekiq::ServerTracer, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8ba16a1240 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sidekiq::CurrentAttributes::Load, @args=[{"cattr"=>"Current"}]>]>, @client_chain=#<Sidekiq::Middleware::Chain:0x00007f8bb790eee0 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @entries=[#<Sidekiq::Middleware::Entry:0x00007f8ba4e3e8d8 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sidekiq::Enterprise::Unique::Client, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8bb790ec38 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sidekiq::Batch::Client, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8bad38c508 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sentry::Sidekiq::SentryContextClientMiddleware, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8ba1fd2198 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Datadog::Tracing::Contrib::Sidekiq::ClientTracer, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f8ba16a1358 @config=#<Sidekiq::Config:0x00007f8bb98114a0 ...>, @klass=Sidekiq::CurrentAttributes::Save, @args=[{"cattr"=>"Current"}]>]>, @logger=#<SemanticLogger::Logger:0x00007f8baac60d30 @filter=nil, @name="Sidekiq", @level_index=nil, @level=nil>>
/app/config/initializers/sidekiq.rb:35:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:98:in `configure_server'
/app/config/initializers/sidekiq.rb:28:in `block in <main>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:445:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:445:in `block in make_lambda'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:686:in `catch'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:686:in `block in default_terminator'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:200:in `block in halting'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:595:in `block in invoke_before'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:595:in `each'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:595:in `invoke_before'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/callbacks.rb:106:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/reloader.rb:88:in `prepare!'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/application/finisher.rb:68:in `block in <module:Finisher>'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:32:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:32:in `run'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:60:in `run_initializers'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/application.rb:372:in `initialize!'
/app/config/environment.rb:8:in `<top (required)>'
<internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/cli.rb:303:in `boot_application'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/cli.rb:42:in `run'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/bin/sidekiq:31:in `<top (required)>'
/app/vendor/bundle/ruby/3.2.0/bin/sidekiq:25:in `load'
/app/vendor/bundle/ruby/3.2.0/bin/sidekiq:25:in `<top (required)>'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
/app/vendor/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/app/vendor/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
/app/bin/bundle:113:in `load'
/app/bin/bundle:113:in `<main>'

```

The error seems to be the line where we configure customer job_logger
```
    config.options[:job_logger] = SidekiqExtensions::TaggedJobLogger
```

What's the new way to set up custom job logger in Sidekiq 7?

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
```
Sidekiq.configure_server do |config|
    # rubocop:disable Style/GlobalVars
    config.redis = $redis_params
    # rubocop:enable Style/GlobalVars

    config.dogstatsd = -> { Datadog::Statsd.new("localhost", 8125, namespace: "sidekiq") }

    config.options[:job_logger] = SidekiqExtensions::TaggedJobLogger

    # Enable historical metrics
    # https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics
    config.retain_history(30.seconds) do |s|
      s.batch do |b|
        # Push latency metrics for individual queues.  The default queue is
        # already pushed by default.  See
        # https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics#custom
        %w[critical low eventually].each do |qname|
          q = Sidekiq::Queue.new(qname)
          b.gauge("sidekiq.queue.latency", q.latency, tags: ["queue:#{qname}"])
        end
      end
    end

    # See configuration in config/periodic_jobs.rb
    require_relative "../periodic_jobs"
    config.periodic(&PERIODIC_JOBS)

    config.server_middleware do |chain|
      require "sidekiq/middleware/server/statsd"
      chain.add Sidekiq::Middleware::Server::Statsd
      chain.add SidekiqUtils::RequestDetailsMiddleware
      chain.add SidekiqUtils::PausedJobClassMiddleware
      chain.add SidekiqUtils::OwningTeamsMiddleware
    end
  end

  require "sidekiq/pro/web"
  require "sidekiq-ent/web"

  ::Sidekiq::Web.register SidekiqUtils::Web
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
Review https://github.com/sidekiq/sidekiq/wiki/Logging. I think you want `config[:job_logger] = ...` in Sidekiq 7.
