### ISSUE TITLE
`no implicit conversion of String into Integer` in batch status after upgrade from 6 to 7

### ISSUE THREAD

**Issue by jimmyaurora** [sidekiq/sidekiq#6061]
Ruby version: 3.1.4
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s): 7.1.4 / 7.1.4 / 7.1.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

We started seeing the error consistently after deploying the upgrade from 6 to 7.

initializer
```require_relative "redis" # Making sure redis is loaded before Sidekiq.

# To setup sidekiq with redis locally:
# You will have to start redis: $ redis-server
# And also start sidekiq:       $ bundle exec sidekiq

require "sidekiq/pro/expiry"

# default_worker_options can only be set using Sidekiq as it not a server configuration
Sidekiq.default_job_options = {"retry" => false} unless Rails.env.production?

# Configure Sidekiq Pro to use Datadog agent to send job metrics to Datadog.
# See https://app.datadoghq.com/account/settings#integrations/sidekiq.
require "datadog/statsd"
Sidekiq::Pro.dogstatsd = -> { Datadog::Statsd.new("localhost", 8125, namespace: "sidekiq") }

redis_config = {
  url: Rails.application.config_for(:redis)[:url],
  db: Rails.application.config_for(:redis)[:db],
  size: Rails.application.config_for(:sidekiq)[:concurrency] + 5,
  protocol: 2
}

# Customize and enable global stats submission with Sidekiq::Enterprise::History
Sidekiq::Enterprise::History.send(:prepend, Sidekiq::EnterpriseStats)

Sidekiq.configure_server do |config|
  config.redis = redis_config

  config.on(:fork) do
    # See https://github.com/sidekiq/sidekiq/wiki/Ent-Multi-Process#application-preload
    ActiveRecord::Base.clear_active_connections!

    # Same as with puma - multi-process deployments require initializing LD for each process
    # See https://docs.launchdarkly.com/sdk/server-side/ruby#initializing-ldclient-in-a-rails-application
    FeatureFlags.configure(
      sdk_key: ENV["LAUNCHDARKLY_SDK_KEY"],
      redis_url: ENV["LAUNCHDARKLY_REDIS_URL"],
      redis_prefix: "feature-flags",
      redis_expiration: 30, # seconds
      local_flags_file: (Rails.root.join("config", "development_feature_flags.json") if Rails.env.development?)
    )

    config.retain_history(30)
  end

  # Use Sidekiq logger for normal logs so worker/thread/job can be correlated
  Rails.logger = Sidekiq.logger

  # Add sidekiq metrics statsd middleware for Datadog integration.
  # See https://app.datadoghq.com/account/settings#integrations/sidekiq.
  config.server_middleware do |chain|
    # this middleware should be first in the chain to correctly measure queue wait time
    require "sidekiq/middleware/server/statsd"

    chain.add Sidekiq::Middleware::QueueStatsd

    chain.add Sidekiq::Middleware::OnCompletedCallback

    # Override the DEFAULT_OPTIONS to add common tags (e.g. service:)
    Sidekiq::Middleware::Server::Statsd.options = ->(w, _, q) do
      {tags: ["worker:#{w}", "queue:#{q}"] + Sidekiq::CommonTags.metrics_tags}
    end
    chain.add Sidekiq::Middleware::Server::Statsd

    chain.add Sidekiq::Middleware::PodNameTagger

    # Added last because we want to measure mem "use" by the job, not by middleware
    chain.add Sidekiq::Middleware::MemStatsd
  end

  # the server can also act as a client, so make sure client middleware runs there as well
  # docs: https://github.com/sidekiq/sidekiq/wiki/Middleware#client-middleware-registered-in-both-places
  config.client_middleware do |chain|
    chain.add Sidekiq::Middleware::OnEnqueuedCallback
  end

  # start the cron job that will poll for SQS messages coming from the Client Service for product enablement
  if ENV.fetch("CS_PRODUCT_ENABLEMENT_ENABLED", "false") == "true"
    config.periodic do |mgr|
      # see any crontab reference for the first argument
      # e.g. http://www.adminschoice.com/crontab-quick-reference
      # or   https://crontab.guru/
      mgr.register("* * * * *", CreditAdapter::Workers::ProductEnablementMessagePoller.to_s)
    end
  end
end

Sidekiq.configure_client do |config|
  config.redis = redis_config

  config.client_middleware do |chain|
    chain.add Sidekiq::Middleware::OnEnqueuedCallback
  end

  config.retain_history(30)
end
```
sidekiq.yml
```defaults: &defaults
  :concurrency: <%= ENV["SIDEKIQ_MAX_THREADS"] || 10 %>

  # If we notice that only critical jobs are executed and default/low jobs are
  # accumulating in their queue, we should update these to weighted queues.
  # Ref: https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues
  # Article: https://phil.tech/2016/tips-on-sidekiq-queues/
  :queues:
    - ["critical", <%= ENV["SIDEKIQ_QUEUE_CRITICAL_WEIGHT"] || 1 %>]
    - ["default", <%= ENV["SIDEKIQ_QUEUE_DEFAULT_WEIGHT"] || 1 %>]

  # Most of our workers perform work that is user initiated, as in a user is
  # actively waiting for the worker to finish to then receive some output from us.
  # In this context, waiting more than 5 minutes is unrealistic, hence I set the
  # global max retry count from 25 to 4.
  # Docs: https://github.com/mperham/sidekiq/wiki/Error-Handling
  :max_retries: 4 # Equals to ~ 5 minutes

development:
  <<: *defaults
  :concurrency: <%= ENV['SIDEKIQ_MAX_THREADS'] || 2 %>
  :verbose: true
  :logfile: log/sidekiq.log

test:        *defaults
staging:     *defaults
alpha:       *defaults
beta:        *defaults
delta:       *defaults
epsilon:     *defaults
gamma:       *defaults
sandbox:     *defaults
production:  *defaults
deployed_development:  *defaults
```
stacktrace
```TypeError: no implicit conversion of String into Integer
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-7.1.4/lib/sidekiq/batch/status.rb:34:in `load_data': no implicit conversion of String into Integer (TypeError)
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-7.1.4/lib/sidekiq/batch/status.rb:23:in `initialize'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-7.1.4/lib/sidekiq/batch/callback.rb:14:in `new'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-7.1.4/lib/sidekiq/batch/callback.rb:14:in `perform'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:210:in `execute_job'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:180:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/lib/sidekiq/middleware/mem_statsd.rb:37:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/lib/sidekiq/middleware/pod_name_tagger.rb:18:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-7.1.4/lib/sidekiq/middleware/server/statsd.rb:40:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/lib/sidekiq/middleware/on_completed_callback.rb:18:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/lib/sidekiq/middleware/queue_statsd.rb:30:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-7.1.4/lib/sidekiq/pro/expiry.rb:37:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/contrib/sidekiq/server_tracer.rb:79:in `block in call'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/trace_operation.rb:192:in `block in measure'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/span_operation.rb:150:in `measure'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/trace_operation.rb:192:in `measure'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/tracer.rb:380:in `start_span'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/tracer.rb:160:in `block in trace'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/context.rb:45:in `activate!'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/tracer.rb:159:in `trace'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing.rb:18:in `trace'
	from /app/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.11.0/lib/datadog/tracing/contrib/sidekiq/server_tracer.rb:40:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-7.1.4/lib/sidekiq/batch/middleware.rb:58:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/limiter/middleware.rb:10:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sentry-sidekiq-4.8.0/lib/sentry/sidekiq/sentry_context_middleware.rb:24:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/metrics/tracking.rb:26:in `track'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/metrics/tracking.rb:122:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:173:in `invoke'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/job_retry.rb:114:in `local'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/rails.rb:16:in `block in call'
	from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.4/lib/active_support/execution_wrapper.rb:91:in `wrap'
	from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.4/lib/active_support/reloader.rb:72:in `block in wrap'
	from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.4/lib/active_support/execution_wrapper.rb:91:in `wrap'
	from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.4/lib/active_support/reloader.rb:71:in `wrap'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/rails.rb:15:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:271:in `stats'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/job_logger.rb:13:in `call'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/job_retry.rb:81:in `global'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:128:in `block in dispatch'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/job_logger.rb:39:in `prepare'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:127:in `dispatch'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:177:in `handle_interrupt'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:177:in `block in process'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:176:in `handle_interrupt'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:176:in `process'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:82:in `process_one'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:72:in `run'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:10:in `watchdog'
	from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:19:in `block in safe_thread'```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
The problem is `protocol: 2` in your initializer. Sidekiq 7 only supports RESP3.
