### ISSUE TITLE
Sidekiq 7 tries to connect to Redis in RSpec

### ISSUE THREAD

**Issue by andrewt77** [sidekiq/sidekiq#6062]
Ruby version: 3.0.1
Rails version: 7.0.7
Sidekiq / Pro / Enterprise version(s): 7.1.3

sidekiq initializer:
```
require 'sidekiq'
require 'sidekiq-status'

# SIDEKIQ_STATUS_EXPIRATION = 48.hours.to_i
Sidekiq.configure_client do |config|
  config.redis = { :size => 1 }
  Sidekiq.strict_args!(false)
  # Sidekiq::Status.configure_client_middleware(config,
                                              # expiration: SIDEKIQ_STATUS_EXPIRATION)
end
```

After updating from Sidekiq 6 to Sidekiq 7, running sidekiq worker tests with RSpec that involve using `Sidekiq::Status` or `Sidekiq::Batch` modules are failing because they are trying to connect to a redis server (which should not happen in RSpec, and also confirmed that in Sidekiq 6 it works as expected).

Even trying to put the `Sidekiq::Status.configure_client_middleware` line in the sidekiq initializer (commented for now) and trying to run a RSpec test with sidekiq will result into the following error:

```
RedisClient::CannotConnectError:
       Connection refused - connect(2) for 127.0.0.1:6379
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client/ruby_connection.rb:117:in `connect'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client/ruby_connection.rb:49:in `initialize'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client.rb:688:in `new'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client.rb:688:in `block in connect'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client/middlewares.rb:12:in `connect'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client.rb:687:in `connect'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client.rb:674:in `raw_connection'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client.rb:641:in `ensure_connected'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client.rb:415:in `multi'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client/decorator.rb:55:in `multi'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-status-3.0.3/lib/sidekiq-status/storage.rb:17:in `block in store_for_id'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-status-3.0.3/lib/sidekiq-status/storage.rb:112:in `block in redis_connection'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-status-3.0.3/lib/sidekiq-status/storage.rb:111:in `redis_connection'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-status-3.0.3/lib/sidekiq-status/storage.rb:16:in `store_for_id'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-status-3.0.3/lib/sidekiq-status/client_middleware.rb:42:in `call'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-7.1.3/lib/sidekiq/middleware/chain.rb:182:in `traverse'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-7.1.3/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-batch-0.1.9/lib/sidekiq/batch/middleware.rb:11:in `call'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-7.1.3/lib/sidekiq/middleware/chain.rb:182:in `traverse'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-7.1.3/lib/sidekiq/middleware/chain.rb:173:in `invoke'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-7.1.3/lib/sidekiq/client.rb:88:in `push'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-7.1.3/lib/sidekiq/job.rb:361:in `client_push'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-7.1.3/lib/sidekiq/job.rb:198:in `perform_async'
     # /Users/andrew/.rvm/gems/ruby-3.0.1/gems/sidekiq-7.1.3/lib/sidekiq/job.rb:286:in `perform_async'
     # ./spec/workers/associations_dac_billing_report_spec.rb:154:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::ECONNREFUSED:
     #   Connection refused - connect(2) for 127.0.0.1:6379
     #   /Users/andrew/.rvm/gems/ruby-3.0.1/gems/redis-client-0.17.0/lib/redis_client/ruby_connection.rb:117:in `connect'
```

If I comment that line then the initializer runs successfully, but then it will fail where I use `Sidekiq::Status` or `Sidekiq::Batch` in the workers that are being tested. For `Sidekiq::Batch` I found a workaround with `rspec-sidekiq`, but I can't find one to prevent `Sidekiq::Status` to connect to redis server.

We really want to upgrade the Sidekiq gem from 6 to 7, so any help would be appreciated, thank you!

**Comment by mperham** [comment]
It sounds like your problem is with Sidekiq-status, not Sidekiq.
