### ISSUE TITLE
Exception When Queuing an ActiveJob on Rails 7.1.0 and Sidekiq 6.5.11

### ISSUE THREAD

**Issue by bjreath** [sidekiq/sidekiq#6070]
Ruby version: 3.2.2
Rails version: 7.1.0
Sidekiq / Pro / Enterprise version(s): 6.5.11

When queuing an ActionMailer job in our development environment (which is our only environment not logging to STDOUT directly), we are seeing this exception:

```
17:42:53 worker.1     | 2023-10-09T22:42:53.242Z pid=17819 tid=13ff WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","wrapped":"ActionMailer::MailDeliveryJob","args":[{"job_class":"ActionMailer::MailDeliveryJob","job_id":"95b9c3d9-a6b6-4f9e-ab47-c99a5759374f","provider_job_id":null,"queue_name":"default","priority":null,"arguments":["ItineraryMailer","traveler_itinerary_email","deliver_now",{"args":[{"trip":{"_aj_globalid":"gid://tern/Trip/197"},"recipient":{"_aj_globalid":"gid://tern/User/1"},"message":"Hello world","_aj_ruby2_keywords":["trip","recipient","message"]}],"_aj_ruby2_keywords":["args"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2023-10-09T22:00:44.924958000Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"e7a40db9e099e41d20431bd4","created_at":1696888844.9250062,"enqueued_at":1696891373.151364,"error_message":"undefined method `current_tags' for nil:NilClass","error_class":"NoMethodError","failed_at":1696891373.240861,"retry_count":6,"retried_at":1696890041.1269,"processor":"Gibson.local:17819"}}
17:42:53 worker.1     | 2023-10-09T22:42:53.242Z pid=17819 tid=13ff WARN: NoMethodError: undefined method `current_tags' for nil:NilClass
17:42:53 worker.1     | 2023-10-09T22:42:53.242Z pid=17819 tid=13ff WARN: /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activejob-7.1.0/lib/active_job/logging.rb:39:in `logger_tagged_by_active_job?'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activejob-7.1.0/lib/active_job/logging.rb:25:in `tag_logger'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activejob-7.1.0/lib/active_job/logging.rb:18:in `perform_now'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activejob-7.1.0/lib/active_job/execution.rb:30:in `block in execute'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activejob-7.1.0/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/reloader.rb:77:in `block in wrap'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/reloader.rb:74:in `wrap'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activejob-7.1.0/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:130:in `instance_exec'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/callbacks.rb:141:in `run_callbacks'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activejob-7.1.0/lib/active_job/execution.rb:28:in `execute'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activejob-7.1.0/lib/active_job/queue_adapters/sidekiq_adapter.rb:70:in `perform'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:202:in `execute_job'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/sidekiq/server.rb:38:in `block in call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:383:in `perform_action_with_newrelic_trace'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/instrumentation/sidekiq/server.rb:27:in `call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/ddtrace-1.15.0/lib/datadog/tracing/contrib/sidekiq/server_tracer.rb:79:in `block in call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/ddtrace-1.15.0/lib/datadog/tracing/tracer.rb:529:in `skip_trace'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/ddtrace-1.15.0/lib/datadog/tracing/tracer.rb:136:in `trace'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/ddtrace-1.15.0/lib/datadog/tracing.rb:18:in `trace'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/ddtrace-1.15.0/lib/datadog/tracing/contrib/sidekiq/server_tracer.rb:40:in `call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/bugsnag-6.25.2/lib/bugsnag/integrations/sidekiq.rb:24:in `call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-failures-1.0.4/lib/sidekiq/failures/middleware.rb:9:in `call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:182:in `invoke'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:169:in `block in process'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/job_retry.rb:113:in `local'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/rails.rb:14:in `block in call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/reloader.rb:77:in `block in wrap'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/execution_wrapper.rb:92:in `wrap'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/activesupport-7.1.0/lib/active_support/reloader.rb:74:in `wrap'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/rails.rb:13:in `call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:263:in `stats'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/job_logger.rb:13:in `call'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/job_retry.rb:80:in `global'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:124:in `block in dispatch'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/job_logger.rb:39:in `prepare'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:123:in `dispatch'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:168:in `process'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:78:in `process_one'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:68:in `run'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/component.rb:8:in `watchdog'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/sidekiq-6.5.11/lib/sidekiq/component.rb:17:in `block in safe_thread'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:435:in `block (2 levels) in thread_block_with_current_transaction'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
17:42:53 worker.1     | /Users/bjreath/.rvm/gems/ruby-3.2.2@tern/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:434:in `block in thread_block_with_current_transaction'
```

This is caused by this code in `ActiveJob`:

```
def logger_tagged_by_active_job?
  logger.formatter.current_tags.include?("ActiveJob")
end
```

In Sidekiq 6.5.11, the Sidekiq library is setting up the logger in `lib/sidekiq/rails.rb` with:

```
::Rails.logger = ::ActiveSupport::BroadcastLogger.new(::Rails.logger, config.logger)
```

In railties 7.1.0, Rails is setting up a `BroadcastLogger` doing this by default:

```
unless Rails.logger.is_a?(ActiveSupport::BroadcastLogger)
  broadcast_logger = ActiveSupport::BroadcastLogger.new(Rails.logger)
  broadcast_logger.formatter = Rails.logger.formatter
  Rails.logger = broadcast_logger
end
```

Note that it's explicitly assigning a formatter on the newly-created `BroadcastLogger`.

In our application, we have fixed the issue for now by assigning a formatter to the `ActiveSupport::BroadcastLogger` via this snippet in `development.rb`.

```
config.after_initialize do
  if Rails.logger.is_a?(ActiveSupport::BroadcastLogger) &&
      Rails.logger.broadcasts.any? { |broadcast| broadcast == Sidekiq.logger }
    basic_logger = Rails.logger.broadcasts.first
    Rails.logger.formatter ||= basic_logger.formatter
  end
end
```

I'm wondering if something similar should be included in the Sidekiq code that initializes the `BroadcastLogger`.

**Comment by fatkodima** [comment]
This change needs to be backported to 6.5.x - https://github.com/sidekiq/sidekiq/pull/6060.

This should be already fixed in Sidekiq 7, if you can upgrade.
