### ISSUE TITLE
Avoid method_missing

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#6083]
The redis client adapter today uses [`method_missing`](https://github.com/sidekiq/sidekiq/blob/dad5627466e162bc0682d5effbf274930786f965/lib/sidekiq/redis_client_adapter.rb#L28-L31) to implement the old-style ::Redis API where each command is a separate method `c.blpop("queue")` instead of the new-style ::RedisClient API which uses a single `call` method for all commands: `c.call("blpop", "queue")`.

Survey Sidekiq's Redis command usage and define methods ahead of time so the Ruby VM can optimize these calls and we can avoid using `method_missing`.

**Comment by bf4** [comment]
Investigating a "TypeError: Unsupported command argument type: TrueClass" on context "super_fetch startup" when updating from sidekiq 7.1.6 to 7.2.0. Sidekiq pro is still 7.1.6. Looks like our dependabot missed that there was a 7.2.0 upgrade.  I'm thinking we should assert that `Sidekiq::VERSION == Sidekiq::Pro::VERSION` in our test suite.

**Comment by mperham** [comment]
It is wrong to update only the Sidekiq gem. You must update with “bundle up sidekiq-ent” or pro so Bundler can assure the comm and oss gems are version compatible.

the assert’s a bad idea because you might have OSS 7.2.1 running with Pro 7.2.0.

**Comment by ReazerDev** [comment]
Hi I'm getting `TypeError: Unsupported command argument type: TrueClass` aswell. I'm not using Sidekiq Pro.

Is there anything else I have to do?

**Comment by mperham** [comment]
> Is there anything else I have to do?

Show us a backtrace.

**Comment by ReazerDev** [comment]
```
2023-11-02T14:43:44.015Z pid=75090 tid=1qlu INFO: Booted Rails 7.1.1 application in development environment                                                                                                                                                    
2023-11-02T14:43:44.015Z pid=75090 tid=1qlu INFO: Running in ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]                                                                                                                                        
2023-11-02T14:43:44.015Z pid=75090 tid=1qlu INFO: See LICENSE and the LGPL-3.0 for licensing details.                                                                                                                                                          
2023-11-02T14:43:44.015Z pid=75090 tid=1qlu INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org                                                                                                                                    
2023-11-02T14:43:44.016Z pid=75090 tid=1qlu INFO: Sidekiq 7.2.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>nil}                                                                                                                
2023-11-02T14:43:44.017Z pid=75090 tid=1qlu INFO: Sidekiq 7.2.0 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>nil}                                                                                                                  
2023-11-02T14:43:44.018Z pid=75090 tid=1qlu WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}                                                                                                                                    
2023-11-02T14:43:44.018Z pid=75090 tid=1qlu WARN: TypeError: Unsupported command argument type: TrueClass                                                                                                                                                      
2023-11-02T14:43:44.018Z pid=75090 tid=1qlu WARN:                                                                                                                                                                                                              
Unsupported command argument type: TrueClass                                                                                                                                                                                                                   
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:37:in `block in generate'                                                                                                                    
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:28:in `map!'                                                                                                                                 
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:28:in `generate'                                                                                                                             
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client.rb:253:in `call'                                                                                                                                                
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/redis_client_adapter.rb:36:in `block (2 levels) in <module:CompatMethods>'                                                                                                 
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/orphans/manager.rb:195:in `block in register_reaper_process'                                                                        
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/decorator.rb:46:in `block in with'                                                                                                                              
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client.rb:219:in `with'                                                                                                                                                
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/decorator.rb:46:in `with'                                                                                                                                       
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/connection.rb:16:in `block in redis'                                                                                                
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/config.rb:163:in `block in redis'                                                                                                                                          
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'                                                                                                                       
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'                                                                                                                               
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'                                                                                                                                  
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'                                                                                                                               
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'                                                                                                                                           
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/config.rb:160:in `redis'                                                                                                                                                   
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq.rb:73:in `redis'                                                                                                                                                           
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/connection.rb:15:in `redis'                                                                                                         
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/orphans/manager.rb:195:in `register_reaper_process'                                                                                 
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/orphans/manager.rb:42:in `block in start'                                                                                           
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/logging.rb:142:in `block in with_logging_context'                                                                                   
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/logger.rb:11:in `with'                                                                                                                                                     
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/logging.rb:157:in `call'                                                                                                            
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/logging.rb:157:in `with_configured_loggers_context'                                                                                 
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/logging.rb:141:in `with_logging_context'                                                                                            
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/orphans/manager.rb:41:in `start'                                                                                                    
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/server.rb:36:in `start'                                                                                                             
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/server.rb:20:in `block in configure'                                                                                                
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/component.rb:60:in `block in fire_event'                                                                                                                                   
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/component.rb:59:in `each'                                                                                                                                                  
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/component.rb:59:in `fire_event'                                                                                                                                            
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/lib/sidekiq/cli.rb:106:in `run'                                                                                                                                                        
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.0/bin/sidekiq:31:in `<top (required)>'                                                                                                                                                   
/home/work/.rbenv/versions/3.2.0/bin/sidekiq:25:in `load'                                                                                                                                                                                                      
/home/work/.rbenv/versions/3.2.0/bin/sidekiq:25:in `<top (required)>'                                                                                                                                                                                          
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'                                                                                                                                                   
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'                                                                                                                                            
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'                                                                                                                                                    
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'                                                                                                                                                       
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'                                                                                                                                
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'                                                                                                                 
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'                                                                                                                                  
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'                                                                                                                                                    
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'                                                                                                   
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'                                                                                                                          
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'                                                                                                              
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'                                                                                              
/home/work/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'                                                                                                                       
/home/work/.rbenv/versions/3.2.0/bin/bundle:25:in `load'                                                                                                                                                                          
/home/work/.rbenv/versions/3.2.0/bin/bundle:25:in `<main>'
```

**Comment by mperham** [comment]
Here's the problem:

gems/sidekiq-unique-jobs-36ffe8f95b01/lib/sidekiq_unique_jobs/orphans/manager.rb:195:in `block in register_reaper_process'

**Comment by ReazerDev** [comment]
Oh, sorry, must've missed that :sweat_smile:

**Comment by Greg-Myers-SB** [comment]
@mperham , our issue was caused by using `sidekiq-ent-7.1.2/lib/sidekiq-ent/senate.rb:84:in 'block in stage_coup!'` with sidekiq 7.2.0
If the gems are supposed to be locked together, can you please consider a short-circuit with an error message saying that?

**Comment by mperham** [comment]
@Greg-Myers-SB If you use `bundle up sidekiq`, you will break Sidekiq Pro/Ent. Always upgrade the highest-level gem. To use a house analogy, otherwise you are upgrading the foundation but not the parts above the foundation. https://github.com/sidekiq/sidekiq/wiki/Commercial-FAQ#how-do-i-upgrade-sidekiq-pro-or-sidekiq-enterprise

**Comment by mperham** [comment]
And yes, I think it would be reasonable for Pro/Ent to check that all Sidekiq gems are using the same MAJOR.MINOR.

**Comment by Greg-Myers-SB** [comment]
Totally appreciate that it's documented well here, and known within my organisation. The combination of Dependabot upgrading anything it can get it's hands on, and some level of human error leads to anything possible will happen eventually 😓 
Thanks for all you do on Sidekiq 🙏

**Comment by leorseligmann** [comment]
Hi all,

We are using sidekiq-ent has anyone been able to set up dependabot bumps for sidekiq where human interventions is not needed.
Thanks

**Comment by Greg-Myers-SB** [comment]
@leorseligmann even with Dependabot it's worth looking at it with a human eye as it's possible the dependabot run could happen during a sidekiq release and the best you can do is ask dependabot to look for new versions at the same time, not that the versions match.
If you still wanted to, it would look like this:
```yaml
...
updates:
  - package-ecosystem: bundler
    groups:
      # Sidekiq can have issues updating these separately https://github.com/sidekiq/sidekiq/issues/6083
      all-of-sidekiq:
        patterns:
          - "sidekiq*"
...
```
