### ISSUE TITLE
Sidekiq Pro reschedule metrics

### ISSUE THREAD

**Issue by dpep** [sidekiq/sidekiq#6086]
Ruby version: 3
Rails version: 6
Sidekiq / Pro / Enterprise version(s):
- sidekiq-pro-5.5.1
- sidekiq-ent-2.5.2

Hi Mike,

I have a question (and maybe a feature request) about how Sidekiq Ent rate limiters get tracked in Sidekiq Pro Datadog/statsd metrics.  It seems like rate limited jobs are marked as `sidekiq.jobs.failure`...is that right?  I see `over rate limit, rescheduling for later` in my logs, so it seems like the jobs is being rescheduled.

Questions:
- Are rescheduled jobs indeed marked as failures?  If so, what differentiates reschedules from retries?
- What is the correct metric to track rescheduled jobs?

stack trace in case you need it.  I think the key line is `sidekiq-pro-5.5.1/lib/sidekiq/middleware/server/statsd.rb`

Thanks

```
from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-pro-5.5.1/lib/sidekiq/pro/metrics.rb:193:in `batch'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-pro-5.5.1/lib/sidekiq/middleware/server/statsd.rb:43:in `call'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/rollbar-3.4.1/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/ddtrace-0.54.2/lib/ddtrace/contrib/sidekiq/server_tracer.rb:43:in `block in call'

from /usr/local/bundle/ruby/3.0.0/gems/ddtrace-0.54.2/lib/ddtrace/tracer.rb:283:in `trace'

from /usr/local/bundle/ruby/3.0.0/gems/ddtrace-0.54.2/lib/ddtrace/contrib/sidekiq/server_tracer.rb:24:in `call'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/timeout-0.4.0/lib/timeout.rb:186:in `block in timeout'

from /usr/local/bundle/ruby/3.0.0/gems/timeout-0.4.0/lib/timeout.rb:193:in `timeout'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-ent-2.5.2/lib/sidekiq-ent/limiter/unlimited.rb:11:in `within_limit'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-pro-5.5.1/lib/sidekiq/batch/middleware.rb:58:in `call'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-ent-2.5.2/lib/sidekiq-ent/unique.rb:154:in `call'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-ent-2.5.2/lib/sidekiq-ent/limiter/middleware.rb:39:in `call'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/middleware/chain.rb:182:in `invoke'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:169:in `block in process'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/job_retry.rb:113:in `local'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/rails.rb:14:in `block in call'

from /usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.7.4/lib/active_support/execution_wrapper.rb:91:in `wrap'

from /usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.7.4/lib/active_support/reloader.rb:72:in `block in wrap'

from /usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.7.4/lib/active_support/execution_wrapper.rb:91:in `wrap'

from /usr/local/bundle/ruby/3.0.0/gems/activesupport-6.1.7.4/lib/active_support/reloader.rb:71:in `wrap'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/rails.rb:13:in `call'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:263:in `stats'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/job_retry.rb:80:in `global'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:124:in `block in dispatch'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/job_logger.rb:39:in `prepare'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:123:in `dispatch'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:168:in `process'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:78:in `process_one'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/processor.rb:68:in `run'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/component.rb:8:in `watchdog'

from /usr/local/bundle/ruby/3.0.0/gems/sidekiq-6.5.11/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**Comment by mperham** [comment]
Can you start Sidekiq with `-v` and show me the client/server middleware chains that log on startup?

**Comment by mperham** [comment]
I think this might work better for you:

```ruby
# in your initializer
# before
chain.add Sidekiq::Middleware::Server::Statsd
# after
chain.insert_before Sidekiq::Limiter::Middleware, Sidekiq::Middleware::Server::Statsd
```

**Comment by dpep** [comment]
thanks, I'll give that load order change a shot!

**Comment by dpep** [comment]
that did the job...thanks Mike!
