### ISSUE TITLE
Unhandle lock for flush tracking

### ISSUE THREAD

**Issue by doha99-eh** [sidekiq/sidekiq#6088]
Ruby version: 2.7.5
Rails version: 6.1.7.6)
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

I got this bug
```
RuntimeError: can't add a new key into hash during iteration
  from sidekiq (7.1.6) lib/sidekiq/metrics/tracking.rb:108:in `block (2 levels) in reset'
  from sidekiq (7.1.6) lib/sidekiq/metrics/tracking.rb:35:in `block in track'
  from sidekiq (7.1.6) lib/sidekiq/metrics/tracking.rb:34:in `synchronize'
  from sidekiq (7.1.6) lib/sidekiq/metrics/tracking.rb:34:in `track'
  from sidekiq (7.1.6) lib/sidekiq/metrics/tracking.rb:122:in `call'
  from sidekiq (7.1.6) lib/sidekiq/middleware/chain.rb:182:in `traverse'
  from sidekiq (7.1.6) lib/sidekiq/middleware/chain.rb:173:in `invoke'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
  from sidekiq (7.1.6) lib/sidekiq/job_retry.rb:114:in `local'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
  from sidekiq (7.1.6) lib/sidekiq/rails.rb:16:in `block in call'
  from activesupport (6.1.7.6) lib/active_support/execution_wrapper.rb:91:in `wrap'
  from activesupport (6.1.7.6) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.7.6) lib/active_support/execution_wrapper.rb:91:in `wrap'
  from activesupport (6.1.7.6) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (7.1.6) lib/sidekiq/rails.rb:15:in `call'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:271:in `stats'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
  from sidekiq (7.1.6) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
  from sidekiq (7.1.6) lib/sidekiq/job_retry.rb:81:in `global'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:128:in `block in dispatch'
  from sidekiq (7.1.6) lib/sidekiq/job_logger.rb:39:in `prepare'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:127:in `dispatch'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:177:in `handle_interrupt'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:177:in `block in process'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:176:in `handle_interrupt'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:176:in `process'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:82:in `process_one'
  from sidekiq (7.1.6) lib/sidekiq/processor.rb:72:in `run'
  from sidekiq (7.1.6) lib/sidekiq/component.rb:10:in `watchdog'
  from sidekiq (7.1.6) lib/sidekiq/component.rb:19:in `block in safe_thread'
```

~After investigating, I saw the below block doesn't have a wrapper of the `@lock.synchronize`~

https://github.com/sidekiq/sidekiq/blob/e9f212902185591831af514df6313f8ae2cce31a/lib/sidekiq/metrics/tracking.rb#L73-L75

It is reassigned in the reset https://github.com/sidekiq/sidekiq/blob/e9f212902185591831af514df6313f8ae2cce31a/lib/sidekiq/metrics/tracking.rb#L103-L111

But I wonder why does it happen? 

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
Yeah, the bug is not obvious to me either. @gram should only be touched with the lock and no one else is reporting this issue. Anything else strange about your deploy? Maybe upgrade Ruby?

**Comment by doha99-eh** [comment]
> Yeah, the bug is not obvious to me either. @grams should only be touched with the lock and no one else is reporting this issue. Anything else strange about your deploy? Maybe upgrade Ruby?

I don't upgrade Ruby but upgrade sidekiq. And some relative gems are upgraded also.

**Comment by grams** [comment]
Hi folks 👋🏻
No need to tag me on that one 😅

**Comment by mperham** [comment]
Is this still an issue? If not, please close.
