### ISSUE TITLE
Unsupported command argument type: TrueClass (TypeError) after upgrade to sidekiq 7.2.0

### ISSUE THREAD

**Issue by stereosupersonic** [sidekiq/sidekiq#6089]
Ruby version: 3.1.4
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): 7.2.0, 7.1.6, 7.0.8

this error happened when i start sidekiq `bundle exec sidekiq -C config/sidekiq.yml`
```
/Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:38:in `block in generate': Unsupported command argument type: TrueClass (TypeError)
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:28:in `map!'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:28:in `generate'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/redis-client-0.18.0/lib/redis_client.rb:253:in `call'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/bundler/gems/sidekiq-23bcc2480c00/lib/sidekiq/redis_client_adapter.rb:36:in `block (2 levels) in <module:CompatMethods>'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-ent-7.0.8/lib/sidekiq-ent/senate.rb:81:in `block in stage_coup!'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/bundler/gems/sidekiq-23bcc2480c00/lib/sidekiq/config.rb:163:in `block in redis'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/bundler/gems/sidekiq-23bcc2480c00/lib/sidekiq/config.rb:160:in `redis'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/bundler/gems/sidekiq-23bcc2480c00/lib/sidekiq/component.rb:28:in `redis'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-ent-7.0.8/lib/sidekiq-ent/senate.rb:80:in `stage_coup!'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/sidekiq-ent-7.0.8/lib/sidekiq-ent/senate.rb:93:in `cycle'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/bundler/gems/sidekiq-23bcc2480c00/lib/sidekiq/component.rb:10:in `watchdog'
	from /Users/michaeldeimel/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/bundler/gems/sidekiq-23bcc2480c00/lib/sidekiq/component.rb:19:in `block in safe_thread'
	
```

when i downgrade to `gem "sidekiq", "7.1.6", git: "https://github.com/mperham/sidekiq", ref:"bab4b4918e5765951ed04494940093e76bfab34f" `  then everything works again

**Comment by mperham** [comment]
That's because unreleased Sidekiq doesn't work with released Ent. You're mixing 7.1 and 7.2.

**Comment by stereosupersonic** [comment]
i only did `bundle update --patch`

**Comment by stereosupersonic** [comment]
ok thx

**Comment by mperham** [comment]
Easiest way to upgrade Sidekiq Enterprise is “bundle up sidekiq-ent”.

**Comment by stereosupersonic** [comment]
@mperham is it possible that the startup for sidekiq failed if there is such an exception? now i only get a warning  

```
2023-10-31T08:50:11.784Z pid=60388 tid=2qdg WARN: {"context":"senate"}
2023-10-31T08:50:11.784Z pid=60388 tid=2qdg WARN: TypeError: Unsupported command argument type: TrueClass
```

**Comment by mperham** [comment]
@stereosupersonic I can't predict anything about the state of Sidekiq if it is logging exceptions like that.

**Comment by pcothenet** [comment]
We experience that issue, even when updating sidekiq and sidekiq-pro in lockstep. Looking at the stack trace, it might be related to sidekiq-unique-jobs. I'll file an issue there.
