### ISSUE TITLE
Inconsistency in Serialization and Deserialization of `@options` in `Sidekiq::Periodic::Loop`

### ISSUE THREAD

**Issue by nohat** [sidekiq/sidekiq#6092]
#### Summary 
The `@options` instance variable is serialized to a JSON string when storing in Redis via `Sidekiq::Periodic::Config#persist`, but not deserialized back to a hash during the initialization of `Sidekiq::Periodic::Loop`, causing type inconsistency and potential downstream issues.

---

#### Description:

In the Sidekiq-Enterprise implementation of periodic jobs, there is a discrepancy between how the `@options` instance variable is stored and later retrieved. This mismatch is unexpected behavior, though [the documentation for the periodic jobs API](https://github.com/sidekiq/sidekiq/wiki/Ent-Periodic-Jobs#api) does not specify either way what type the `@options` instance variable is. In our use case, the [Sidekiq Cronitor gem](https://github.com/cronitorio/cronitor-sidekiq/) [assumes](https://github.com/cronitorio/cronitor-sidekiq/blob/master/lib/sidekiq/cronitor.rb#L55
) that the job's `options` method returns a hash corresponding to the values specified when the registering the periodic job:

```ruby
    def periodic_job_key(worker)
      return unless defined?(Sidekiq::Periodic)

      periodic_job = Sidekiq::Periodic::LoopSet.new.find do |lop|
        lop.history.find { |j| j[0] == worker.jid }
      end

      periodic_job.present? && periodic_job.options.fetch('cronitor_key', nil)
    end

```

The problem manifests in two core parts of the periodic jobs implementation:

1. **Storing Options to Redis**: In the `Sidekiq::Periodic::Config#persist` method, `@options` is serialized to a JSON string before being stored in Redis.

    ```ruby
    args.append("options", Sidekiq.dump_json(lop.options))
    ```

2. **Reading Options from Redis**: In the `Sidekiq::Periodic::Loop#initialize` method, `@options` is read directly from Redis without deserializing it back into its original data type (most likely a hash).

    ```ruby
    @options = opts.delete("options")
    ```

This inconsistency between serialization and deserialization can cause unexpected behavior, particularly if the consuming code expects `@options` to be a hash.

---

#### Versions
Ruby version: 3.1.0
Rails version: 7.0.4.3
Sidekiq / Pro / Enterprise version(s): 7.0.3 / 7.0.10 / 7.0.8

#### Initializer
```ruby
require 'sidekiq'
require 'sidekiq/cronitor/periodic_jobs'

sidekiq_config = { url: ENV.fetch('DEDICATED_REDIS_URI', 'redis://localhost:6379/0') }

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Cronitor::ServerMiddleware
  end
  LogstopGuard.guard!(config.logger)
  config.redis = sidekiq_config
  config.periodic do |mgr|
    mgr.register('*/5 * * * 1-5', 'TestLoanProConnection', cronitor_enabled: true)
  end
end
```

#### Example error
```
2023-10-31 19:20:00.112938 I [6:default/processor] Sidekiq -- fail
2023-10-31 19:20:00.113108 W [6:default/processor] Sidekiq -- {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"TestLoanProConnection","args":[],"cronitor_enabled":true,"jid":"50ce858a9af4a387a7277a26","created_at":1698780000.085093,"enqueued_at":1698780000.085868},"_config":"#<Sidekiq::Config:0x0000ffffb0e65810>"}
2023-10-31 19:20:00.114064 W [6:default/processor] Sidekiq -- NoMethodError: undefined method `fetch' for "{\"cronitor_enabled\":true}":String

      periodic_job.present? && periodic_job.options.fetch('cronitor_key', nil)
                                                   ^^^^^^
2023-10-31 19:20:00.114091 W [6:default/processor] Sidekiq -- /rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-cronitor-3.7.1/lib/sidekiq/cronitor.rb:55:in `periodic_job_key'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-cronitor-3.7.1/lib/sidekiq/cronitor.rb:44:in `job_key'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-cronitor-3.7.1/lib/sidekiq/cronitor.rb:76:in `rescue in ping'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-cronitor-3.7.1/lib/sidekiq/cronitor.rb:67:in `ping'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-cronitor-3.7.1/lib/sidekiq/cronitor.rb:21:in `rescue in call'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-cronitor-3.7.1/lib/sidekiq/cronitor.rb:16:in `call'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-7.0.10/lib/sidekiq/batch/middleware.rb:58:in `call'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-ent-7.0.8/lib/sidekiq-ent/limiter/middleware.rb:40:in `call'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/metrics/tracking.rb:24:in `track'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/metrics/tracking.rb:120:in `call'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/middleware/chain.rb:180:in `invoke'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:173:in `block in process'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/job_retry.rb:113:in `local'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/rails.rb:16:in `block in call'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:72:in `block in wrap'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:71:in `wrap'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/rails.rb:15:in `call'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:267:in `stats'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/job_logger.rb:13:in `call'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/job_retry.rb:80:in `global'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:128:in `block in dispatch'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/job_logger.rb:39:in `prepare'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:127:in `dispatch'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:172:in `process'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:82:in `process_one'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:72:in `run'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:8:in `watchdog'
/rails_terraform_docker/vendor/bundle/ruby/3.1.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:17:in `block in safe_thread'
```
If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

#### Steps to Reproduce:

1. Register a periodic job with options:

    ```ruby
    Sidekiq.configure_server do |config|
      config.periodic do |mgr|
        mgr.register('*/5 * * * 1-5', 'TestLoanProConnection', cronitor_enabled: true)
      end
    end
    ```

2. Check the `@options` instance variable in any instance of `Sidekiq::Periodic::Loop`. It will be a string containing the serialized JSON, rather than a hash. In this example, it had the string value `"{\"cronitor_enabled\":true}"` rather than the expected hash.

---

#### Expected Results:

The `@options` instance variable should be a hash containing the original options, consistent with the type before serialization.

---

#### Actual Results:

The `@options` instance variable is a JSON string as read directly from Redis.

---

#### Temporary Workaround:

A monkey-patch can correct this behavior:

```ruby
module LoopInitializerPatch
  def initialize(lid)
    super
    @options = JSON.parse(@options) unless @options.nil? || @options.is_a?(Hash)
  rescue JSON::ParserError => e
    Sidekiq.logger.error("Failed to parse @options as JSON in Sidekiq::Periodic::Loop: #{e.message}")
  end
end

Sidekiq::Periodic::Loop.prepend(LoopInitializerPatch)
```

---

#### Suggested Fix:

The simplest fix would be to deserialize `@options` during initialization in `Sidekiq::Periodic::Loop`, ensuring it’s consistent with its original type.

```ruby
@options = JSON.parse(opts.delete("options")) unless opts.delete("options").nil?
```

This ensures that `@options` retains its original type, without introducing breaking changes.

---

Thank you for considering this issue. Let me know if additional information or clarification is needed.

**Comment by mperham** [comment]
I think the person that wrote that Cronitor code didn't really understand Sidekiq's job implementation. Sidekiq jobs are just a simple Hash. There are many different sources for options.

```
Sidekiq.default_job_options
sidekiq_options key: value
JobClass.set(key: value)
PeriodicManager.register(..., key: value)
```
```ruby
mgr.register("* * * * *", "MikeJob", foo: "bar", cronitor_enabled: true) # symbols are converted to strings by json
```

All of those option hashes are merged into one payload at runtime when the job is actually created by the periodic subsystem. When the job executes, you'll see this in middleware:

```ruby
def call(worker, job, queue)
  job["class"] # == "MikeJob"
  job["foo"] # == "bar"
  job["cronitor_enabled"] # == true
end
```

Middleware shouldn't be scanning through sidekiq_options. Look up the option's value directly in the job payload:

```ruby
def call(worker, job, queue)
  job["cronitor_enabled"] # == true
```

I [advise people to never use Sidekiq's data APIs](https://www.mikeperham.com/2021/04/20/a-tour-of-the-sidekiq-api/) for your own logic as they aren't guaranteed to be fast or scalable. If you have questions how to do something, open an issue and I'd be happy to advise.
