### ISSUE TITLE
Sidekiq workers do not start (or at least do not start processing jobs) after updating from 7.1.6 to 7.2.0

### ISSUE THREAD

**Issue by WvanLelyveld** [sidekiq/sidekiq#6096]
Ruby version: ruby 3.2.2
Rails version: Rails 7.0.8
Sidekiq / Pro / Enterprise version(s): 7.2.0

When upgrading from sidekiq and sidekiq-pro 7.1.6 to 7.2.0, the sidekiq workers do not seem to start in the capistrano deployment process anymore.
The capistrano log does say `01 sudo systemctl start sidekiq` and returns ok, but the worker never shows up in the /sidekiq/busy UI, nor do jobs get processed.

After only reverting the gems to 7.1.6 again, no other changes, the workers do start again on a deploy.
If you need any more info/logs, please let me know.

relevant gems:
```
gem 'sidekiq', '7.1.6'
gem 'sidekiq-pro', '7.1.6'
gem 'sidekiq-bulk' (0.2.0)       
gem 'sidekiq-failures' (1.0.4)   
gem 'sidekiq-limit_fetch' (4.4.1)
gem 'sidekiq-scheduler' (5.0.3)  
gem 'sidekiq-unique-jobs' (8.0.3)
gem 'capistrano-sidekiq'  (2.3.1)
```

Or maybe it's just we can't upgrade to 7.2.0 yet if we are on pro?

**Comment by cpjmcquillan** [comment]
We ran into this error when starting our app after updating to `7.2`. Haven't had time to investigate yet though 👍 

```
ruby/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:37:in `block in generate': Unsupported command argument type: TrueClass (TypeError)
sidekiq |
sidekiq |             raise TypeError, "Unsupported command argument type: #{element.class}"
```

**Comment by mperham** [comment]
You need to give me the full backtrace of the error. sidekiq-unique-jobs has a known issue with 7.2.

**Comment by pathouse** [comment]
ran into the same issue - we dont use `sidekiq-unique-jobs`

here's the stacktrace:

```
gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:37:in `block in generate': Unsupported command argument type: TrueClass (TypeError)
    from gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:28:in `map!'
    from gems/redis-client-0.18.0/lib/redis_client/command_builder.rb:28:in `generate'
    from gems/redis-client-0.18.0/lib/redis_client.rb:510:in `call'
    from gems/sidekiq-7.2.0/lib/sidekiq/redis_client_adapter.rb:36:in `block (2 levels) in <module:CompatMethods>'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch/middleware.rb:115:in `block (2 levels) in needs_callback?'
    from gems/redis-client-0.18.0/lib/redis_client/decorator.rb:51:in `block in pipelined'
    from gems/redis-client-0.18.0/lib/redis_client.rb:403:in `pipelined'
    from gems/redis-client-0.18.0/lib/redis_client/decorator.rb:51:in `pipelined'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch/middleware.rb:114:in `block in needs_callback?'
    from gems/sidekiq-7.2.0/lib/sidekiq/capsule.rb:102:in `block in redis'
    from gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
    from gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
    from gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
    from gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
    from gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
    from gems/sidekiq-7.2.0/lib/sidekiq/capsule.rb:99:in `redis'
    from gems/sidekiq-7.2.0/lib/sidekiq.rb:73:in `redis'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch.rb:38:in `redis'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch/middleware.rb:112:in `needs_callback?'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch/middleware.rb:108:in `needs_complete?'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch/middleware.rb:90:in `add_success'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch/middleware.rb:36:in `block in call'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch/middleware.rb:35:in `handle_interrupt'
    from gems/sidekiq-pro-7.1.6/lib/sidekiq/batch/middleware.rb:35:in `call'
    from gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
    from gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
    from gems/bugsnag-6.26.0/lib/bugsnag/integrations/sidekiq.rb:25:in `call'
    from gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
    from gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
    from gems/sidekiq-7.2.0/lib/sidekiq/metrics/tracking.rb:26:in `track'
    from gems/sidekiq-7.2.0/lib/sidekiq/metrics/tracking.rb:122:in `call'
    from gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
    from gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:173:in `invoke'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
    from gems/sidekiq-7.2.0/lib/sidekiq/job_retry.rb:114:in `local'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
    from gems/sidekiq-7.2.0/lib/sidekiq/rails.rb:16:in `block in call'
    from gems/activesupport-7.0.4.2/lib/active_support/execution_wrapper.rb:92:in `wrap'
    from gems/activesupport-7.0.4.2/lib/active_support/reloader.rb:72:in `block in wrap'
    from gems/activesupport-7.0.4.2/lib/active_support/execution_wrapper.rb:92:in `wrap'
    from gems/activesupport-7.0.4.2/lib/active_support/reloader.rb:71:in `wrap'
    from gems/sidekiq-7.2.0/lib/sidekiq/rails.rb:15:in `call'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:271:in `stats'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
    from gems/sidekiq-7.2.0/lib/sidekiq/job_logger.rb:13:in `call'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
    from gems/sidekiq-7.2.0/lib/sidekiq/job_retry.rb:81:in `global'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:128:in `block in dispatch'
    from gems/sidekiq-7.2.0/lib/sidekiq/job_logger.rb:39:in `prepare'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:127:in `dispatch'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:177:in `handle_interrupt'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:177:in `block in process'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:176:in `handle_interrupt'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:176:in `process'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:82:in `process_one'
    from gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:72:in `run'
    from gems/sidekiq-7.2.0/lib/sidekiq/component.rb:10:in `watchdog'
    from gems/sidekiq-7.2.0/lib/sidekiq/component.rb:19:in `block in safe_thread'
 ```
 
 lmk if there's any other details i can provide to help debug

**Comment by mperham** [comment]
@pathouse you are mixing Pro 7.1 with Sidekiq 7.2. It will break. Upgrade Pro.

**Comment by pathouse** [comment]
d'oh! thanks @mperham

**Comment by mperham** [comment]
https://github.com/sidekiq/sidekiq/wiki/Commercial-FAQ#how-do-i-upgrade-sidekiq-pro-or-sidekiq-enterprise

**Comment by xiaoxipang** [comment]
Encounter the same error as the [comment](https://github.com/sidekiq/sidekiq/issues/6096#issuecomment-1792888380)

Follow the [instruction](https://github.com/sidekiq/sidekiq/wiki/Commercial-FAQ#how-do-i-upgrade-sidekiq-pro-or-sidekiq-enterprise) and bump the Ent version and it works well.

**Comment by KevinCarterDev** [comment]
Why does sidekiq-pro 7.1.6 have a constraint of `sidekiq (>= 7.1.5, < 8)`, thereby making it compatible with sidekiq 7.2 when in fact sidekiq 7.2 has breaking changes? Shouldn't sidekiq-pro 7.1.6 use a version constraint of `sidekiq (>=7.1, <7.2)` if minor versions of sidekiq are going to contain breaking changes?

**Comment by mperham** [comment]
@KevinCarterDev Because I do not try to predict the future and assume that vA.X will be incompatible with vA.X+1.

**Comment by KevinCarterDev** [comment]
But you decided the future as soon as you released sidekiq-pro 7.1.6. By setting the version constraint to `sidekiq (>= 7.1.5, < 8)` you've committed to that version of sidekiq-pro being compatible with all versions of sidekiq 7.1.6 -> 8.0. If you can't make that commitment then sidekiq-pro should use a version constraint of `sidekiq (=7.1.6)` so that backwards incompatible versions of sidekiq don't break it.

**Comment by mperham** [comment]
But then customers can't get Sidekiq bugfixes (i.e. 7.1.7) without me releasing Sidekiq Pro 7.1.7, which is a non-starter. Perhaps I should lock to the minor version, `sidekiq ~> 7.1.0`.

**Comment by josephfrazier** [comment]
This just bit me as well via a dependabot-triggered sidekiq upgrade, which didn't upgrade sidekiq-pro because the version constraint didn't require it. So, I'd be in favor of a more conservative constraint that's more likely to guarantee compatibility. 👍🏻
