### ISSUE TITLE
Sidekiq 6.5.x crashes with Rails 7.1: undefined method `broadcast' for ActiveSupport::Logger:Class

### ISSUE THREAD

**Issue by collimarco** [sidekiq/sidekiq#6104]
Ruby version: 3.2.2
Rails version: 7.1.1
Sidekiq / Pro / Enterprise version(s): 6.5.5

After the upgrade to Rails 7.1, Sidekiq and all our background jobs crash completely:

```
NoMethodError: undefined method `broadcast' for ActiveSupport::Logger:Class

/usr/local/bundle/gems/sidekiq-6.5.5/lib/sidekiq/rails.rb:46:in `block (2 levels) in <class:Rails>'
/usr/local/bundle/gems/sidekiq-6.5.5/lib/sidekiq.rb:142:in `configure_server'
/usr/local/bundle/gems/sidekiq-6.5.5/lib/sidekiq/rails.rb:41:in `block in <class:Rails>'
/usr/local/bundle/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.1.1/lib/rails/initializable.rb:61:i
```

Can you please fix this in Sidekiq 6 ?

**Comment by collimarco** [comment]
Even upgrading to Sidekiq v6.5.12 (which is the latest available on 6.x) doesn't solve the issue.

Workers crash completely with this error (basically the process in the container crashes and keeps restarting):

```
NoMethodError: undefined method `broadcast_to' for #<Logger:0x00007fe912d92fd0 @level=1, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007fe91302c390 @datetime_format=nil>, @formatter=#<LogStashLogger::Formatter::JsonLines:0x00007fe91302c840 @customize_event=nil, @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x00007fe912d92f80 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<LogStashLogger::Device::TCP:0x00007fe9129a4d88 @sync=nil, @error_logger=#

/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/rails.rb:61:in `block (2 levels) in <class:Rails>'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq.rb:142:in `configure_server'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/rails.rb:52:in `block in <class:Rails>'
/usr/local/bundle/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'
/usr/local/bundle/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
```

**Comment by mperham** [comment]
I'm guessing it's because you are using a logstash plugin which breaks the Rails logger.

**Comment by collimarco** [comment]
@mperham Thanks! I had a replacement of the default `Rails.logger`... I removed it and now it works!
