### ISSUE TITLE
Document sidekiq_options backtrace_cleaner: lambda { |trace| ... } 

### ISSUE THREAD

**Issue by Nowaker** [sidekiq/sidekiq#6106]
Feature request: allow `sidekiq_options backtrace: ...` to accept a proc that will determine how much of the backtrace to preserve in Redis.

I'd like to preserve all stacktrace in my code, but skip all the Sidekiq code in the trace.  I could use `1` or `5`, but this is not as cool as a piece of code that determines which stacktrace lines are relevant to me, and which aren't. If I pick `3` but have 5 levels of `rescue` in my jobs, I would lose the context. If I pick `10` or `true`, I'll have too much information. If I can pass a `proc`, I'll have the the exact number of frames that matter to me. (In the below example, I'd preserve the first two)

```
["/home/nowaker/projekty/modern/XXX/app/jobs/process_video_job.rb:16:in `perform'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:202:in `execute_job'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-status-2.1.3/lib/sidekiq-status/server_middleware.rb:42:in `call'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'",
 "/home/nowaker/projekty/modern/XXX/config/initializers/sidekiq.rb:17:in `call'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-batch-0.1.9/lib/sidekiq/batch/middleware.rb:30:in `call'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-failures-1.0.0/lib/sidekiq/failures/middleware.rb:9:in `call'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/middleware/chain.rb:182:in `invoke'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:169:in `block in process'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/job_retry.rb:113:in `local'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/rails.rb:14:in `block in call'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:72:in `block in wrap'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:71:in `wrap'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/rails.rb:13:in `call'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:263:in `stats'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/job_logger.rb:13:in `call'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/job_retry.rb:80:in `global'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:124:in `block in dispatch'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/job_logger.rb:39:in `prepare'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:123:in `dispatch'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:168:in `process'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:78:in `process_one'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/processor.rb:68:in `run'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/component.rb:8:in `watchdog'",
 "/home/nowaker/.rvm/gems/ruby-3.1.4/gems/sidekiq-6.5.9/lib/sidekiq/component.rb:17:in `block in safe_thread'"]
 ```

**Comment by mperham** [comment]
It exists already but it's not documented in the wiki. Something like this should work.

https://github.com/sidekiq/sidekiq/blob/ed9e01d427ed0503caa73191e32ff18a86e9f35e/lib/sidekiq/config.rb#L34

```ruby
Sidekiq.configure_server do |config|
  config[:backtrace_cleaner] = ->(bt) { bt[0..5] }
```

**Comment by Nowaker** [comment]
Awesome. I'll use it!

I guess this ticket now becomes "document existence of backtrace cleaner feature". :)

**Comment by mperham** [comment]
https://github.com/sidekiq/sidekiq/wiki/Logging#backtrace-cleaning
