### ISSUE TITLE
Sidekiq issue => `require': cannot load such file -- sidekiq/util (LoadError)

### ISSUE THREAD

**Issue by limjinsun** [sidekiq/sidekiq#6108]
Ruby version: 2.7.7
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): gem 'sidekiq', '~> 7.2'

```
gem 'sidekiq', '~> 7.2'
gem "sidekiq-cron", '1.11.0'
gem 'sidekiq-worker-killer', '1.0.0'
```

```
❯ rails s
=> Booting Puma
=> Rails 7.0.8 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	58: from bin/rails:4:in `<main>'
	57: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:37:in `require'
	56: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:37:in `require'
	55: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<top (required)>'
	54: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
	53: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
	52: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	51: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	50: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	49: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:134:in `perform'
	48: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:134:in `tap'
	47: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	46: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:36:in `start'
	45: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	44: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/rack-2.2.8/lib/rack/server.rb:422:in `wrapped_app'
	43: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/rack-2.2.8/lib/rack/server.rb:249:in `app'
	42: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/rack-2.2.8/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	41: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'
	40: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'
	39: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'
	38: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'
	37: from config.ru:3:in `block in <main>'
	36: from config.ru:3:in `require_relative'
	35: from /Users/flenderjin/Documents/projects/flender/config/environment.rb:5:in `<top (required)>'
	34: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
	33: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
	32: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	31: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	30: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	29: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:347:in `call'
	28: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:347:in `each'
	27: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	26: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	25: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:415:in `call'
	24: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/initializable.rb:50:in `tsort_each_child'
	23: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/initializable.rb:50:in `each'
	22: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	21: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	20: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	19: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	18: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	17: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
	16: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
	15: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
	14: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/engine.rb:619:in `block in <class:Engine>'
	13: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/engine.rb:619:in `each'
	12: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
	11: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/engine.rb:666:in `load_config_initializer'
	10: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/activesupport-7.0.8/lib/active_support/notifications.rb:208:in `instrument'
	 9: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/engine.rb:667:in `block in load_config_initializer'
	 8: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/railties-7.0.8/lib/rails/engine.rb:667:in `load'
	 7: from /Users/flenderjin/Documents/projects/flender/config/initializers/sidekiq.rb:5:in `<top (required)>'
	 6: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	 5: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:37:in `require'
	 4: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:37:in `require'
	 3: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/sidekiq-worker-killer-1.0.0/lib/sidekiq/worker_killer.rb:3:in `<top (required)>'
	 2: from /Users/flenderjin/Documents/projects/flender/vendor/cache/ruby/2.7.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	 1: from /Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:37:in `require'
/Users/flenderjin/.rvm/rubies/ruby-2.7.7/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:37:in `require': cannot load such file -- sidekiq/util (LoadError)
```

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

initializer
```
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq-cron'
require 'sidekiq/cron/web'
require 'sidekiq/worker_killer'
require 'middleware/stop_background_work'

Sidekiq.logger = Logger.new(STDOUT)
Sidekiq.configure_server do |config|

  config.redis = { url: ENV['REDIS_URL'] }
  config.logger.level = Logger::DEBUG

  Rails.application.config.after_initialize do
    Sidekiq::Cron::Job.load_from_hash(YAML.load_file('config/schedule.yml'))
  end

  
  config.client_middleware do |chain|
    chain.add StopBackgroundWork
  end
  config.server_middleware do |chain|
    chain.add Sidekiq::WorkerKiller, max_rss: SIDEKIQ_MAX_RSS_LIMIT 
  end

end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL'] }
end

Sidekiq.options[:max_retries] = 2
```
sidekiq.yml
```
production:
  :concurrency: 8
staging:
  :concurrency: 8
development:
  :concurrency: 8

:queues:
  - mailer
  - default
  - logger
  - rake
  - investment_account_check
```  

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by fatkodima** [comment]
Try to upgrade `sidekiq-worker-killer`.
