### ISSUE TITLE
Unable to mark the deploy for Sidekiq metrics

### ISSUE THREAD

**Issue by bhanuone** [sidekiq/sidekiq#6125]
Ruby version: 2.7.8
Rails version: 6.1.7.6
Sidekiq / Pro / Enterprise version(s): Pro

I have this capistrano task that marks a deployment for sidekiq metrics. But throwing an error when runnning it. Please see error log below.
```ruby
namespace :sidekiq do
  desc 'Mark deployment in Sidekiq Metrics'
  task :mark_deploy_for_metrics do
    on roles(:app) do
      Sidekiq::Deploy.mark!(label: "test")
    end
  end
end
```

Error log
```
#<Thread:0x000000011d504d08 /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        18: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
        17: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:31:in `run'
        16: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
        15: from config/deploy.rb:152:in `block (3 levels) in <top (required)>'
        14: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sidekiq-7.2.0/lib/sidekiq/deploy.rb:24:in `mark!'
        13: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sidekiq-7.2.0/lib/sidekiq/deploy.rb:45:in `mark!'
        12: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
        11: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
        10: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
         9: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
         8: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
         7: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sidekiq-7.2.0/lib/sidekiq/deploy.rb:49:in `block in mark!'
         6: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/redis-client-0.18.0/lib/redis_client/decorator.rb:55:in `multi'
         5: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/redis-client-0.18.0/lib/redis_client.rb:447:in `multi'
         4: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/redis-client-0.18.0/lib/redis_client.rb:675:in `ensure_connected'
         3: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/redis-client-0.18.0/lib/redis_client.rb:449:in `block in multi'
         2: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/redis-client-0.18.0/lib/redis_client/middlewares.rb:16:in `call'
         1: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/redis-client-0.18.0/lib/redis_client.rb:450:in `block (2 levels) in multi'
/Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/redis-client-0.18.0/lib/redis_client/connection_mixin.rb:61:in `call_pipelined': ERR wrong number of arguments for 'hsetnx' command (RedisClient::CommandError)
        1: from /Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/bhanu/workspace/railsapp/vendor/ruby/2.7.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as railsapp@bhanu-i.sac.railsapp.com: ERR wrong number of arguments for 'hsetnx' command (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as railsapp@bhanu-i.sac.railsapp.com: ERR wrong number of arguments for 'hsetnx' command


Caused by:
RedisClient::CommandError: ERR wrong number of arguments for 'hsetnx' command

Tasks: TOP => sidekiq:mark_deploy_for_metrics
```

**Comment by mperham** [comment]
It's because the API is `Sidekiq::Deploy.mark!(label)`, you're passing a complex Hash, not a single String.
