### ISSUE TITLE
Sidekiq UI not working

### ISSUE THREAD

**Issue by TheCodeSommelier** [sidekiq/sidekiq#6149]
I am encountering an error I do not know how to solve... I cannot access the Sidekiq UI. I was able to fix it once by updating to a newer version but then it broke on heroku. I went back to development and now it's not working there either... This my development problem. 😅 I tried updating to the latest version but no luck... Anybody has the same issue? Any solutions?

```
Ruby version: 3.1.2
Rails version: 7.1.2
Sidekiq / Pro / Enterprise version(s): 
"sidekiq", "< 7"
"sidekiq-failures", "~> 1.0"
"sidekiq-status" 
```
Above are the sidekiq related gems added also I am using the free version of sidekiq

This is my sidekiq.yml file:
```
:concurrency: 1
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default
  - database_cleaning
  - scrapers
  - scheduler
  - mailers
  - active_storage_analysis
  - active_storage_purge
 ```

Initializer here:

```
url = ENV["REDISCLOUD_URL"]

if url
  Sidekiq.configure_server do |config|
    config.redis = { url: url }
  end

  Sidekiq.configure_client do |config|
    config.redis = { url: url }
  end
end
```

Full backtrace is here:
```
NoMethodError (undefined method `first' for nil:NilClass

      default_queue_latency = if (entry = pipe1_res[6].first)
                                                      ^^^^^^):
  
sidekiq (6.0.4) lib/sidekiq/api.rb:86:in `fetch_stats!'
sidekiq (6.0.4) lib/sidekiq/api.rb:11:in `initialize'
sidekiq (6.0.4) lib/sidekiq/web/helpers.rb:156:in `new'
sidekiq (6.0.4) lib/sidekiq/web/helpers.rb:156:in `stats'
sidekiq (6.0.4) lib/sidekiq/web/action.rb:51:in `_erb__summary'
sidekiq (6.0.4) lib/sidekiq/web/action.rb:89:in `_erb'
sidekiq (6.0.4) lib/sidekiq/web/action.rb:55:in `erb'
sidekiq (6.0.4) lib/sidekiq/web.rb:232:in `_render'
sidekiq (6.0.4) lib/sidekiq/web/action.rb:60:in `erb'
sidekiq (6.0.4) lib/sidekiq/web/application.rb:51:in `block in <class:WebApplication>'
sidekiq (6.0.4) lib/sidekiq/web/application.rb:296:in `instance_exec'
sidekiq (6.0.4) lib/sidekiq/web/application.rb:296:in `block in call'
sidekiq (6.0.4) lib/sidekiq/web/application.rb:294:in `catch'
sidekiq (6.0.4) lib/sidekiq/web/application.rb:294:in `call'
rack-protection (3.0.6) lib/rack/protection/xss_header.rb:20:in `call'
rack-protection (3.0.6) lib/rack/protection/base.rb:53:in `call'
rack-protection (3.0.6) lib/rack/protection/base.rb:53:in `call'
rack-protection (3.0.6) lib/rack/protection/path_traversal.rb:18:in `call'
rack-protection (3.0.6) lib/rack/protection/json_csrf.rb:28:in `call'
rack-protection (3.0.6) lib/rack/protection/base.rb:53:in `call'
rack-protection (3.0.6) lib/rack/protection/base.rb:53:in `call'
rack-protection (3.0.6) lib/rack/protection/frame_options.rb:33:in `call'
rack-protection (3.0.6) lib/rack/protection/base.rb:53:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
rack (3.0.8) lib/rack/urlmap.rb:76:in `block in call'
rack (3.0.8) lib/rack/urlmap.rb:60:in `each'
rack (3.0.8) lib/rack/urlmap.rb:60:in `call'
rack (3.0.8) lib/rack/builder.rb:264:in `call'
sidekiq (6.0.4) lib/sidekiq/web.rb:104:in `call'
sidekiq (6.0.4) lib/sidekiq/web.rb:109:in `call'
actionpack (7.1.2) lib/action_dispatch/routing/mapper.rb:22:in `block in <class:Constraints>'
actionpack (7.1.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:51:in `block in serve'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:124:in `each'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:124:in `find_routes'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.1.2) lib/action_dispatch/routing/route_set.rb:882:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (3.0.8) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.0.8) lib/rack/etag.rb:29:in `call'
rack (3.0.8) lib/rack/conditional_get.rb:31:in `call'
rack (3.0.8) lib/rack/head.rb:15:in `call'
actionpack (7.1.2) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
actionpack (7.1.2) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (7.1.2) lib/active_record/migration.rb:654:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.2) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (7.1.2) lib/active_support/tagged_logging.rb:135:in `block in tagged'
activesupport (7.1.2) lib/active_support/tagged_logging.rb:39:in `tagged'
activesupport (7.1.2) lib/active_support/tagged_logging.rb:135:in `tagged'
activesupport (7.1.2) lib/active_support/broadcast_logger.rb:240:in `method_missing'
railties (7.1.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (3.0.8) lib/rack/method_override.rb:28:in `call'
rack (3.0.8) lib/rack/runtime.rb:24:in `call'
activesupport (7.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
actionpack (7.1.2) lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
actionpack (7.1.2) lib/action_dispatch/middleware/server_timing.rb:58:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (3.0.8) lib/rack/sendfile.rb:114:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
railties (7.1.2) lib/rails/engine.rb:529:in `call'
puma (6.4.0) lib/puma/configuration.rb:272:in `call'
puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.0) lib/puma/request.rb:99:in `handle_request'
puma (6.4.0) lib/puma/server.rb:443:in `process_client'
puma (6.4.0) lib/puma/server.rb:241:in `block in run'
puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by mperham** [comment]
You're using an ancient version of Sidekiq. Upgrade.

**Comment by TheCodeSommelier** [comment]
Thank you for your time! Updated the sidekiq and sidekiq-failures and it works. Still have issues on heroku though (I pushed the latest changes there)... Are they related directly to sidekiq or just to redis? Apologies if my question is obvious I am quite new to this and wanted to make sure I am not doing anything wrong. 


Backlogs from heroku
```
RedisClient::UnsupportedServer (redis-client requires Redis 6+ with HELLO command available (redis://redis-10249.c1.eu-west-1-3.ec2.cloud.redislabs.com:10249/0)):
2024-01-01T17:53:59.753620+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309]
2024-01-01T17:53:59.753624+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] redis-client (0.19.1) lib/redis_client.rb:759:in `rescue in connect'
2024-01-01T17:53:59.753625+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] redis-client (0.19.1) lib/redis_client.rb:715:in `connect'
2024-01-01T17:53:59.753625+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] redis-client (0.19.1) lib/redis_client.rb:710:in `raw_connection'
2024-01-01T17:53:59.753625+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] redis-client (0.19.1) lib/redis_client.rb:675:in `ensure_connected'
2024-01-01T17:53:59.753626+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] redis-client (0.19.1) lib/redis_client.rb:255:in `call'
2024-01-01T17:53:59.753626+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] redis-client (0.19.1) lib/redis_client/decorator.rb:26:in `call'
2024-01-01T17:53:59.753626+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/config.rb:144:in `block in redis_info'
2024-01-01T17:53:59.753626+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/config.rb:163:in `block in redis'
2024-01-01T17:53:59.753628+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] connection_pool (2.4.1) lib/connection_pool.rb:110:in `block (2 levels) in with'
2024-01-01T17:53:59.753628+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] connection_pool (2.4.1) lib/connection_pool.rb:109:in `handle_interrupt'
2024-01-01T17:53:59.753628+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] connection_pool (2.4.1) lib/connection_pool.rb:109:in `block in with'
2024-01-01T17:53:59.753628+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] connection_pool (2.4.1) lib/connection_pool.rb:106:in `handle_interrupt'
2024-01-01T17:53:59.753629+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] connection_pool (2.4.1) lib/connection_pool.rb:106:in `with'
2024-01-01T17:53:59.753629+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/config.rb:160:in `redis'
2024-01-01T17:53:59.753629+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/config.rb:143:in `redis_info'
2024-01-01T17:53:59.753629+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web/helpers.rb:201:in `redis_info'
2024-01-01T17:53:59.753629+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web/application.rb:58:in `block in <class:WebApplication>'
2024-01-01T17:53:59.753630+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web/application.rb:404:in `instance_exec'
2024-01-01T17:53:59.753630+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web/application.rb:404:in `block in call'
2024-01-01T17:53:59.753630+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web/application.rb:402:in `catch'
2024-01-01T17:53:59.753630+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web/application.rb:402:in `call'
2024-01-01T17:53:59.753631+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web/csrf_protection.rb:52:in `admit'
2024-01-01T17:53:59.753631+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web/csrf_protection.rb:41:in `call'
2024-01-01T17:53:59.753631+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/static.rb:161:in `call'
2024-01-01T17:53:59.753631+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/builder.rb:264:in `call'
2024-01-01T17:53:59.753639+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web.rb:117:in `call'
2024-01-01T17:53:59.753639+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] sidekiq (7.2.0) lib/sidekiq/web.rb:122:in `call'
2024-01-01T17:53:59.753641+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/routing/mapper.rb:22:in `block in <class:Constraints>'
2024-01-01T17:53:59.753641+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
2024-01-01T17:53:59.753641+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/journey/router.rb:51:in `block in serve'
2024-01-01T17:53:59.753641+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
2024-01-01T17:53:59.753642+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/journey/router.rb:124:in `each'
2024-01-01T17:53:59.753642+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/journey/router.rb:124:in `find_routes'
2024-01-01T17:53:59.753642+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/journey/router.rb:32:in `serve'
2024-01-01T17:53:59.753642+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/routing/route_set.rb:882:in `call'
2024-01-01T17:53:59.753646+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
2024-01-01T17:53:59.753646+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
2024-01-01T17:53:59.753646+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] warden (1.2.9) lib/warden/manager.rb:34:in `call'
2024-01-01T17:53:59.753646+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/tempfile_reaper.rb:20:in `call'
2024-01-01T17:53:59.753646+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/etag.rb:29:in `call'
2024-01-01T17:53:59.753647+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/conditional_get.rb:31:in `call'
2024-01-01T17:53:59.753647+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/head.rb:15:in `call'
2024-01-01T17:53:59.753647+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
2024-01-01T17:53:59.753647+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
2024-01-01T17:53:59.753647+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
2024-01-01T17:53:59.753647+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
2024-01-01T17:53:59.753647+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] activesupport (7.1.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] railties (7.1.2) lib/rails/rack/logger.rb:37:in `call_app'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] railties (7.1.2) lib/rails/rack/logger.rb:24:in `block in call'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] activesupport (7.1.2) lib/active_support/tagged_logging.rb:135:in `block in tagged'
2024-01-01T17:53:59.753648+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] activesupport (7.1.2) lib/active_support/tagged_logging.rb:39:in `tagged'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] activesupport (7.1.2) lib/active_support/tagged_logging.rb:135:in `tagged'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] activesupport (7.1.2) lib/active_support/broadcast_logger.rb:240:in `method_missing'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] railties (7.1.2) lib/rails/rack/logger.rb:24:in `call'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/request_id.rb:28:in `call'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/method_override.rb:28:in `call'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/runtime.rb:24:in `call'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
2024-01-01T17:53:59.753649+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/static.rb:25:in `call'
2024-01-01T17:53:59.753650+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] rack (3.0.8) lib/rack/sendfile.rb:114:in `call'
2024-01-01T17:53:59.753650+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] actionpack (7.1.2) lib/action_dispatch/middleware/ssl.rb:79:in `call'
2024-01-01T17:53:59.753650+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] railties (7.1.2) lib/rails/engine.rb:529:in `call'
2024-01-01T17:53:59.753650+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] puma (6.4.0) lib/puma/configuration.rb:272:in `call'
2024-01-01T17:53:59.753650+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'
2024-01-01T17:53:59.753650+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
2024-01-01T17:53:59.753650+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] puma (6.4.0) lib/puma/request.rb:99:in `handle_request'
2024-01-01T17:53:59.753651+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] puma (6.4.0) lib/puma/server.rb:443:in `process_client'
2024-01-01T17:53:59.753651+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] puma (6.4.0) lib/puma/server.rb:241:in `block in run'
2024-01-01T17:53:59.753653+00:00 app[web.1]: [66c562ff-3fa5-4898-83be-0d9f7a3c2309] puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by TheCodeSommelier** [comment]
Ok thank you sir!
