### ISSUE TITLE
When `perform_bulk` is passed an array arg with size 1, e.g. [[1, 2, 3]] ArgumentError

### ISSUE THREAD

**Issue by yesthesoup** [sidekiq/sidekiq#6156]
Ruby version: 3.2
Rails version: 7.0.8
Sidekiq / Pro / Enterprise version(s): sidekiq-pro (7.2.0) although this is not a pro feature

Steps to reproduce:

basic worker class:

```ruby
class MyWorker
  include Sidekiq::Job

  sidekiq_options backtrace: true

  # need to use this to get the backtrace as opposed to above backtrace option, see below screenshot in UI
  sidekiq_retry_in do |_count, exception, _jobhash|
     Rails.logger.error [exception.message, *exception.backtrace].join($INPUT_RECORD_SEPARATOR)
   end

  def perform(array_of_ids)
    puts array_of_ids
  end
end
```

```
# rails c

test = [[1, 2, 3]]
MyWorker.perform_bulk(test)
2024-01-04T20:21:59.728Z pid=64846 tid=wti INFO: Sidekiq 7.2.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://127.0.0.1:6379"}
=> ["d13ec135058015d79c0736b1"]
```

```ruby
# bundle exec sidekiq

E, [2024-01-04T15:22:00.307153 #65197] ERROR -- : wrong number of arguments (given 3, expected 1)
/Users/my.user/work/my-service/components/revenue/app/workers/my_worker.rb:11:in `perform'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:210:in `execute_job'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:180:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
[...logstash logging... ]
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/custom-rails-helper-gem-18.9.0/lib/custom/rails-helper-gem/sidekiq/middleware.rb:37:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/custom-rails-helper-gem-18.9.0/lib/custom/rails-helper-gem/sidekiq/middleware.rb:27:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/custom-rails-helper-gem-18.9.0/lib/custom/rails-helper-gem/sidekiq/queue_latency_logger.rb:11:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-pro-7.2.0/lib/sidekiq/middleware/server/statsd.rb:40:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/ddtrace-1.17.0/lib/datadog/tracing/contrib/sidekiq/server_tracer.rb:79:in `block in call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/ddtrace-1.17.0/lib/datadog/tracing/tracer.rb:529:in `skip_trace'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/ddtrace-1.17.0/lib/datadog/tracing/tracer.rb:136:in `trace'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/ddtrace-1.17.0/lib/datadog/tracing.rb:18:in `trace'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/ddtrace-1.17.0/lib/datadog/tracing/contrib/sidekiq/server_tracer.rb:40:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/rollbar-3.4.1/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-pro-7.2.0/lib/sidekiq/batch/middleware.rb:58:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/metrics/tracking.rb:26:in `track'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/metrics/tracking.rb:122:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/middleware/chain.rb:173:in `invoke'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/job_retry.rb:114:in `local'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/rails.rb:16:in `block in call'
/Users/my.user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/my.user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/my.user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/my.user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/reloader.rb:71:in `wrap'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/rails.rb:15:in `call'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:271:in `stats'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
[custom logging]
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/job_retry.rb:81:in `global'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:128:in `block in dispatch'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/job_logger.rb:39:in `prepare'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:127:in `dispatch'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:177:in `handle_interrupt'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:177:in `block in process'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:176:in `handle_interrupt'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:176:in `process'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:82:in `process_one'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/processor.rb:72:in `run'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/component.rb:10:in `watchdog'
/Users/my.user/.rbenv/versions/3.2.2/gemsets/my-service/gems/sidekiq-7.2.0/lib/sidekiq/component.rb:19:in `block in safe_thread'
2024-01-04T20:22:00.309Z pid=65197 tid=uwd WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","backtrace":true,"class":"MyWorker","args":[1,2,3],"jid":"d13ec135058015d79c0736b1","created_at":1704399719.729451,"custom":{},"enqueued_at":1704399719.730907}}
```

Probably because of the way args are expanded here?

https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/job.rb#L315-L317

bonus issue: `backtrace: true` results in no backtrace?

![image](https://github.com/sidekiq/sidekiq/assets/2483953/e31f82a0-b225-4bd9-87bc-028af14dd983)

**Workaround**

Of course we can just check `if input_args.one?` use `perform_async` instead, but likely this issue should be handled with a more clear exception or warning.

**Comment by mperham** [comment]
It takes an Array of Arrays, one Array for each job's args: `[[1], [2], [3]]`

**Comment by yesthesoup** [comment]
> It takes an Array of Arrays, one Array for each job's args: `[[1], [2], [3]]`

Yes, thanks, that is what I am passing:

the job's args is [1, 2, 3]

And I am passing an array of size one: `[[1, 2, 3]]`

**Comment by mperham** [comment]
Then I think you are missing an Array?

`[[[1,2,3]]]`

**Comment by yesthesoup** [comment]
> Then I think you are missing an Array?
> 
> `[[[1,2,3]]]`

Thanks - I guess that could be a workaround as well - but basically my normal usecase is a whole bunch of ids:

`args = [[1, 2, 3...], [4, 5, 6...], [7, 8, 9 ...]]`

`perform_bulk(args)`

but when we are testing with a smaller amount of IDs, we'd have to double nest the array?

`[[[1,2,3]]]`

**Comment by mperham** [comment]
I think you're still missing an Array because your job only takes one argument: an array. You want this:

```ruby
[ # the set of jobs
  [ # the first job
    [1, 2, 3...] # the first argument
  ],
  [[4, 5, 6...]],
  [[7, 8, 9 ...]],
]
```

**Comment by yesthesoup** [comment]
You are right, thank you. Sorry for the back and forth, I'm not sure what I was testing earlier with my larger set of args but it wasn't correct.

Solved by adding a `zip` call:

previously:

```ruby
my_id_args = my_ids.in_groups_of(BATCH_SIZE, false)
MyWorker.perform_bulk(my_id_args)
```

now:

```ruby
my_ids.in_groups_of(BATCH_SIZE, false).zip
MyWorker.perform_bulk(my_id_args)
```
