### ISSUE TITLE
You are connecting to Redis 6.0.16, Sidekiq requires Redis 6.2.0 or greater

### ISSUE THREAD

**Issue by ashrafalzyoud** [sidekiq/sidekiq#6177]
Ruby version: 3.2.3
Rails version:6.1.7.6
ubuntu 22.4
```
redmine@redmine:~/redmine-5.1$ RAILS_ENV=production bundle exec sidekiq
2024-01-29T22:00:06.511Z pid=64392 tid=1az4 INFO: Booted Rails 6.1.7.6 application in production environment
2024-01-29T22:00:06.511Z pid=64392 tid=1az4 INFO: Running in ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux]
2024-01-29T22:00:06.511Z pid=64392 tid=1az4 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2024-01-29T22:00:06.511Z pid=64392 tid=1az4 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2024-01-29T22:00:06.512Z pid=64392 tid=1az4 INFO: Sidekiq 7.2.1 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>nil}
You are connecting to Redis 6.0.16, Sidekiq requires Redis 6.2.0 or greater
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/cli.rb:77:in `run'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/sidekiq-7.2.1/bin/sidekiq:31:in `<top (required)>'
/home/redmine/.rbenv/versions/3.2.3/bin/sidekiq:25:in `load'
/home/redmine/.rbenv/versions/3.2.3/bin/sidekiq:25:in `<top (required)>'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
/home/redmine/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
/home/redmine/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
```

**Comment by mperham** [comment]
Is there something unclear about that error?

**Comment by mperham** [comment]
> You are connecting to Redis 6.0.16, Sidekiq requires Redis 6.2.0 or greater

Is there something unclear about this error message? Upgrade your Redis.

**Comment by ashrafalzyoud** [comment]
The default version in Ubuntu 22.04
It's 16.0.16
If there version in sidekiq compilable with this!!?

**Comment by mperham** [comment]
Sidekiq <7.0.
