### ISSUE TITLE
New `RedisClient::ReadTimeoutError` error

### ISSUE THREAD

**Issue by ksweetie** [sidekiq/sidekiq#6188]
Ruby version: 3.2.2
Rails version: 7.0.7.1
Sidekiq / Pro / Enterprise version(s): 7.2.0 / 7.2.0 / 7.2.0

Kind of a followup to https://github.com/sidekiq/sidekiq/issues/5929 and https://github.com/sidekiq/sidekiq/pull/6159. Like the latter recommends, we upgraded from Redis 6 to 7.0.15, and haven't seen the same error in the two weeks since. However, we just received a single error that looks very similar, but different. Whereas we were always seeing something close to `RedisClient::ReadTimeoutError: Waited 1.0000165048986673 seconds`, now we just got one that waited much longer: `Waited 20.998952341033146 seconds`. This is happening for a Concurrent 

Our redis config looks like:

```rb
SIDEKIQ_REDIS_CONFIG = {
  # some other stuff before this
  read_timeout: 2,
  write_timeout: 2,
  network_timeout: 2,
  pool_timeout: 2,
  size: 50,
}
```

And the backtrace:

```
RedisClient::ReadTimeoutError: Waited 20.998952341033146 seconds
          when :wait_readable
            unless @io.to_io.wait_readable(@read_timeout)
              raise ReadTimeoutError, "Waited #{@read_timeout} seconds" unless @blocking_reads
            end
          when :wait_writable

[[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:140 :in `block in fill_buffer`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-fe13f960701fb10e77f8e7eee5ba925f-52d4dbf2da16)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:122 :in `loop`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-e2896abf5874a195a1667f78138bc584-d5e2c0d2b68b)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:122 :in `fill_buffer`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-faed29a52ba45143ddb240cdabcedfe5-37ee86075ec6)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:114 :in `ensure_remaining`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-84e4325a61be41f0d1a333228c1c02e8-9edf3ba81587)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:85 :in `getbyte`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-5858f968f042d44beb39bf17f44aeab9-fa1f16ca2169)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/resp3.rb:113 :in `parse`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-56db50f4db0af719b9402dcc0e09afab-9a5cf1908475)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/resp3.rb:50 :in `load`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-598a8e4112def773f289f31bd17de43f-de15ec8cf016)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection.rb:96 :in `block in read`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-bd69e1a96e9d1d06abcf4a4a90f9d401-904bd1832809)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:48 :in `with_timeout`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-8ed6b2905571f2755f1ed1965aba081e-15a3fb333c6d)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/ruby_connection.rb:96 :in `read`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-743ae90358bd3c17da0cbe56419d66f4-80175dd2ef48)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/connection_mixin.rb:31 :in `call`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-09cbe8e3a2c1604dcc770468f9fccfbd-8eb25306f1d7)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client.rb:272 :in `block (2 levels) in blocking_call`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-2f30441dc9056c1edd9a28d21df3f6e6-e1169df9a4bb)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/middlewares.rb:16 :in `call`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-8a607984081a2b28b3b48537b4e98df5-3e8c4921a921)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client.rb:271 :in `block in blocking_call`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-f48a2c947bf09ecd4062bf8e6bf4fdcc-c84f303692e5)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client.rb:626 :in `ensure_connected`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-cf729bc23307ae7d28ad5743f24fc64a-4979ca675259)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client.rb:270 :in `blocking_call`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-8846f80ddfaac846fa02d92edb1d5f0e-2f5ebecb0007)
  [[GEM_ROOT]/gems/redis-client-0.14.1/lib/redis_client/decorator.rb:26 :in `blocking_call`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-aace8dc4e1033ed2c9f473ce046a1102-5f3592b6e129)
 [[GEM_ROOT]/gems/sidekiq-ent-7.2.0/lib/sidekiq-ent/limiter/concurrent.rb:109 :in `block in lock`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-e18d7890e05fe7517c360c066a6ec0dd-03b06226596e)
 [[GEM_ROOT]/gems/sidekiq-ent-7.2.0/lib/sidekiq-ent/limiter.rb:103 :in `block in redis`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-2c61c23bbcceff3f6dac35b6a1a6c211-d46d104fa0c4)
  [[GEM_ROOT]/gems/connection_pool-2.3.0/lib/connection_pool.rb:65 :in `block (2 levels) in with`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-6c2a0b205a60b737997e35d95fafb3a7-41b55359b9da)
  [[GEM_ROOT]/gems/connection_pool-2.3.0/lib/connection_pool.rb:64 :in `handle_interrupt`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-7c9775150154aba3788ba13cf30c93ab-27b13fe0d500)
  [[GEM_ROOT]/gems/connection_pool-2.3.0/lib/connection_pool.rb:64 :in `block in with`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-75ce6aa5a32235317c0dc714539e1323-e4a8ba93bcc2)
  [[GEM_ROOT]/gems/connection_pool-2.3.0/lib/connection_pool.rb:61 :in `handle_interrupt`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-5d9a17fd07005716fff5e26ad0bb3617-0561f3be6b79)
  [[GEM_ROOT]/gems/connection_pool-2.3.0/lib/connection_pool.rb:61 :in `with`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-9b48d6fa0d2e358e43e3cdad5969b103-aaf9afd843e6)
 [[GEM_ROOT]/gems/sidekiq-ent-7.2.0/lib/sidekiq-ent/limiter.rb:100 :in `redis`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-aa61908de18875c19264ba73f081abcd-6b9e3f6b0887)
 [[GEM_ROOT]/gems/sidekiq-ent-7.2.0/lib/sidekiq-ent/limiter/concurrent.rb:104 :in `lock`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-b52df018dbf008cdd1fbfd47f1680002-3a2cf9914ac5)
 [[GEM_ROOT]/gems/sidekiq-ent-7.2.0/lib/sidekiq-ent/limiter/concurrent.rb:61 :in `within_limit`](https://app.honeybadger.io/projects/55475/faults/98823159#backtrace-line-bf5497b89cfeb508a9a8e152a3258494-7d7d529784eb)
```

Any ideas? Thanks for all the help with this over the last couple months.

**Comment by mperham** [comment]
Nothing immediately springs to mind. I notice your redis-client version is old, make sure you upgrade that too, just in case.

What does the code for this limiter look like? What's its config?

**Comment by brycemelvin** [comment]
We started seeing this morning on our redis / aws Elasticache instance. no code changes running redis 6.2.6, Sidekiq v7.1.6 / Pro v7.1.3.

**Comment by ksweetie** [comment]
I just upgraded redis / redis-client gems to their newest versions. I'm also going to remove the timeout configs we added. Those configs were shot in the dark when we were seeing the `Waited 1.00001~ seconds" errors, but I don't think they were related to that issue.

Our limiter code looks like this:

```rb
Sidekiq::Limiter.concurrent("foo", 1, wait_timeout: 20, lock_timeout: 90, ttl: 4.hours)
```

I'll see if those changes make any difference. Thank you!

**Comment by dsalkoatdoctible** [comment]
Experiencing the same issue with enterprise limiters. What's interesting is 1.0001~ seconds timeout is confusing since all our timeouts are set to 5 seconds. I narrowed it down to a magic number `1` in sidekiq limiter code:

lib/sidekiq-ent/limiter/concurrent.rb:109    (@ksweetie it's in your call stack too)
```
candidate = conn.blocking_call(diff + 1, "BLMOVE", @free, @pend, "RIGHT", "LEFT", diff.to_f)
```

It seems like the error happens when `diff` is a very small number, for example `0.0001`.

```
#<Sidekiq::Limiter::Concurrent>)> candidate = conn.blocking_call(diff + 1, "BLMOVE", @free, @pend, "RIGHT", "LEFT", diff.to_f)
RedisClient::ReadTimeoutError: Waited 1.0001 seconds (RedisClient::ReadTimeoutError)
from /Users/dsalko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/redis-client-0.17.0/lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer'
```

The first argument `diff + 1` is a custom timeout, as described here https://github.com/redis-rb/redis-client?tab=readme-ov-file#blocking-commands . And the logic is correct since `BLMOVE` timeout is 0.0001 and call timeout is 1.0001, but something goes wrong here.

But the error is not that bad by itself; the problem that this leads to a reduction of Sidekiq limiter size by 1. In the case of "mutex" limiters, completely disables it.

**Comment by mperham** [comment]
You're hitting a redis-server bug: https://github.com/redis/redis/issues/11732

**Comment by mperham** [comment]
What do you think of this patch?

```diff
+++ b/lib/sidekiq-ent/limiter/concurrent.rb
@@ -104,7 +104,7 @@ module Sidekiq
         Sidekiq::Limiter.redis do |conn|
           wait_until = start + wait_for
           diff = wait_until - ::Process.clock_gettime(::Process::CLOCK_MONOTONIC)
-          while diff > 0
+          while diff > 0.001 # redis/redis#11732
             # Wait for a token to reappear in the free list
```

**Comment by dsalkoatdoctible** [comment]
@mperham I think this could be a fix for this issue. It seems like 0.001 is the exact threshold for this issue to happen.

```
irb(main):001>
irb(main):002* Sidekiq::Limiter.redis do |conn|
irb(main):003*   candidate = conn.blocking_call(1.01, "BLMOVE", "{lmtr-c-cull}-free", "{lmtr-c-cull}-pend", "RIGHT", "LEFT", 0.0011)
irb(main):004> end
=> "11705477669.4565077"
irb(main):005* Sidekiq::Limiter.redis do |conn|
irb(main):006*   candidate = conn.blocking_call(1.01, "BLMOVE", "{lmtr-c-cull}-free", "{lmtr-c-cull}-pend", "RIGHT", "LEFT", 0.001)
irb(main):007> end
/usr/local/bundle/gems/redis-client-0.17.0/lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer': Waited 1.01 seconds (RedisClient::ReadTimeoutError)
```

**Comment by mperham** [comment]
Ent 7.2.2 is out with this workaround.

**Comment by ankitsinghaniyaz** [comment]
Will this not be resolved for sidekiq users?

**Comment by mperham** [comment]
@ankitsinghaniyaz if you have an problem, please open a new issue.
