### ISSUE TITLE
Seeing an issue when a failed job is re-queued

### ISSUE THREAD

**Issue by kapso** [sidekiq/sidekiq#6236]
Ruby version: 3.3.0
Rails version: 7.1.3.2
Sidekiq Pro: Sidekiq v7.2.2 / Pro v7.2.0

So I queued the following bad job (id - 100 is not present) - `App::MemberMailer.with(id: 100, recipient: u, notification_id: 5000).invited.deliver_later(wait: 1.minute)`

As expected that triggers the following error in Sidekiq - `ActiveRecord::RecordNotFound (Couldn't find Member with 'id'=100):`

But RecordNotFound error only shows up the 1st time, after that I start seeing the following... 
- TypeError: no implicit conversion of Float into String
- ArgumentError: invalid xmlschema format: "1710968644.9502552" (sentry stack trace shows the issue here - https://github.com/rails/rails/blob/7-1-stable/activejob/lib/active_job/core.rb#L163)

Its looks as if the issue happens when a job is re-queued after an error.

my sidekiq config ...

```ruby
# Web Dashboard
require 'sidekiq/pro/web'
require 'sidekiq-scheduler'
require 'sidekiq-scheduler/web'

Sidekiq.configure_client do |config|
  config.redis = { url: Settings.redis.url, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
  config.logger.level = Rails.env.development? ? Logger::INFO : Logger::WARN

  # Sidekiq Pro options
  Sidekiq::Client.reliable_push! unless Rails.env.test?
end

Sidekiq.configure_server do |config|
  config.redis = { url: Settings.redis.url, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
  config.logger.level = Rails.env.development? ? Logger::INFO : Logger::WARN

  # Default is 5
  config.average_scheduled_poll_interval = 2

  config.on(:startup) do
    Sidekiq.schedule = YAML.safe_load(ERB.new(Rails.root.join('config/schedule.yml').read).result)
    SidekiqScheduler::Scheduler.instance.reload_schedule!
  end

  # Sidekiq Pro options
  Sidekiq::Client.reliable_push! unless Rails.env.test?
  config.super_fetch!
  config.reliable_scheduler!
end

if Rails.env.staging? || Rails.env.production?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.sidekiq.admin.username && password == Settings.sidekiq.admin.password
  end
end
```

Job object ...
```json
{
  "context": "Job raised exception",
  "job": {
    "retry": true,
    "queue": "mailers",
    "wrapped": "ActionMailer::MailDeliveryJob",
    "args": [
      {
        "job_class": "ActionMailer::MailDeliveryJob",
        "job_id": "0b543732-9f1d-4bf3-8b36-cb88ea3b8cc3",
        "provider_job_id": null,
        "queue_name": "mailers",
        "priority": null,
        "arguments": [
          "App::MemberMailer",
          "invited",
          "deliver_now",
          {
            "params": {
              "id": 100,
              "recipient": {
                "_aj_globalid": "gid://tradespace/User/169"
              },
              "notification_id": 5000,
              "_aj_symbol_keys": [
                "id",
                "recipient",
                "notification_id"
              ]
            },
            "args": [],
            "_aj_ruby2_keywords": [
              "params",
              "args"
            ]
          }
        ],
        "executions": 0,
        "exception_executions": {},
        "locale": "en",
        "timezone": "UTC",
        "enqueued_at": 1710973024.839318,
        "scheduled_at": "2024-03-20T22:16:40.238769000Z"
      }
    ],
    "class": "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
    "jid": "d8a39939a8a941fc0582a836",
    "created_at": 1710972940.239732,
    "trace_propagation_headers": {
      "sentry-trace": "3abafec684ec4a3b8a3e938ccadc1603-0335c1439e04455b",
      "baggage": "sentry-trace_id=3abafec684ec4a3b8a3e938ccadc1603,sentry-environment=development,sentry-public_key=bd604bac9c434ad68d6e550ac37544a2"
    },
    "apartment": "public",
    "enqueued_at": 1710973024.839318,
    "error_message": "Couldn't find Member with 'id'=100",
    "error_class": "ActiveRecord::RecordNotFound",
    "failed_at": 1710973001.582341,
    "retry_count": 0
  }
}
```

Rails console (trying to parse `enqueued_at`)  ...
```
irb(main):016> Time.iso8601 1710973024.839318
/Users/kapil/.rbenv/versions/3.3.0/lib/ruby/3.3.0/time.rb:627:in `xmlschema': no implicit conversion of Float into String (TypeError)
```

Sidekiq console ...
<img width="1418" alt="Screenshot 2024-03-20 at 3 32 49 PM" src="https://github.com/sidekiq/sidekiq/assets/344198/e78a30e3-0e4f-4555-803b-cc8d5825a46b">

**Comment by mperham** [comment]
Are you using some new ActiveJob API? I’ve never seen this `with` API:

> App::MemberMailer.with(id: 100, recipient: u, notification_id: 5000).invited.deliver_later(wait: 1.minute)

**Comment by kapso** [comment]
@mperham I think it got introduced with Rails 7 (we been using this for a while) - https://guides.rubyonrails.org/action_mailer_basics.html


<img width="687" alt="Screenshot 2024-03-21 at 4 26 56 PM" src="https://github.com/sidekiq/sidekiq/assets/344198/8ed314c1-6088-4c64-a9f7-d2161c84937f">

**Comment by mperham** [comment]
Ah, it's ActionMailer specific. I didn't know about that syntax.

I need a backtrace to see where the issue is coming from.

**Comment by kapso** [comment]
@mperham here you go, hope it helps.

```
rgumentError: invalid xmlschema format: "1710968644.9502552" (ArgumentError)

        raise ArgumentError.new("invalid xmlschema format: #{time.inspect}")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  from vendor/ruby-3.3.0/lib/ruby/3.3.0/time.rb:650:in `xmlschema'
  from activejob (7.1.3.2) lib/active_job/core.rb:163:in `deserialize'
  from activejob (7.1.3.2) lib/active_job/core.rb:66:in `deserialize'
  from activejob (7.1.3.2) lib/active_job/execution.rb:29:in `block in execute'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from activejob (7.1.3.2) lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
  from activesupport (7.1.3.2) lib/active_support/reloader.rb:77:in `block in wrap'
  from activesupport (7.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (7.1.3.2) lib/active_support/reloader.rb:74:in `wrap'
  from activejob (7.1.3.2) lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:130:in `instance_exec'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:141:in `run_callbacks'
  from activejob (7.1.3.2) lib/active_job/execution.rb:28:in `execute'
  from activejob (7.1.3.2) lib/active_job/queue_adapters/sidekiq_adapter.rb:70:in `perform'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:210:in `execute_job'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:180:in `traverse'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
  from sidekiq-pro (7.2.0) lib/sidekiq/batch/middleware.rb:58:in `call'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:182:in `traverse'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
  from ros-apartment-sidekiq (1.2.0) lib/apartment/sidekiq/middleware/server.rb:5:in `block in call'
  from apartment (e1cb51eaecc4) lib/apartment/adapters/abstract_adapter.rb:89:in `switch'
  from vendor/ruby-3.3.0/lib/ruby/3.3.0/forwardable.rb:240:in `switch'
  from ros-apartment-sidekiq (1.2.0) lib/apartment/sidekiq/middleware/server.rb:4:in `call'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:182:in `traverse'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
  from sentry-sidekiq (5.17.1) lib/sentry/sidekiq/sentry_context_middleware.rb:26:in `call'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:182:in `traverse'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
  from sidekiq (7.2.2) lib/sidekiq/metrics/tracking.rb:26:in `track'
  from sidekiq (7.2.2) lib/sidekiq/metrics/tracking.rb:126:in `call'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:182:in `traverse'
  from sidekiq (7.2.2) lib/sidekiq/middleware/chain.rb:173:in `invoke'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
  from sidekiq (7.2.2) lib/sidekiq/job_retry.rb:113:in `local'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
  from sidekiq (7.2.2) lib/sidekiq/rails.rb:16:in `block in call'
  from activesupport (7.1.3.2) lib/active_support/reloader.rb:77:in `block in wrap'
  from activesupport (7.1.3.2) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.1.3.2) lib/active_support/reloader.rb:74:in `wrap'
  from sidekiq (7.2.2) lib/sidekiq/rails.rb:15:in `call'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:271:in `stats'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
  from sidekiq (7.2.2) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
  from sidekiq (7.2.2) lib/sidekiq/job_retry.rb:80:in `global'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:128:in `block in dispatch'
  from sidekiq (7.2.2) lib/sidekiq/job_logger.rb:39:in `prepare'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:127:in `dispatch'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:177:in `handle_interrupt'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:177:in `block in process'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:176:in `handle_interrupt'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:176:in `process'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:82:in `process_one'
  from sidekiq (7.2.2) lib/sidekiq/processor.rb:72:in `run'
  from sidekiq (7.2.2) lib/sidekiq/component.rb:10:in `watchdog'
  from sidekiq (7.2.2) lib/sidekiq/component.rb:19:in `block in safe_thread'
```

**Comment by mperham** [comment]
Is ActiveJob trying to supply its own `enqueued_at` value which is clashing with Sidekiq's value? That error trace is from ActiveJob, not Sidekiq.

**Comment by mperham** [comment]
Yep, that's the problem. ActiveJob started saving `enqueued_at` as a String in the job payload itself, which clashes with Sidekiq's Float value. I assume this was added in 7.1.

**Comment by mperham** [comment]
You'll need to open an ActiveJob issue for the compatibility issue. One solution:

```ruby
      ea = job_data["enqueued_at"]
      self.enqueued_at          = Time.iso8601(ea) if ea && ea.is_a?(String)
      self.enqueued_at          = Time.at(ea) if ea && ea.is_a?(Float)
```

**Comment by kapso** [comment]
@mperham maybe I am wrong, but isn't Sidekiq supposed to keep compatibility with ActiveJob, rather than the other way around?

**Comment by mperham** [comment]
But I’m also supposed to maintain compatibility with the thousands of Sidekiq users that are currently using the enqueued_at variable. Sidekiq has been using that key name for a decade.
