### ISSUE TITLE
Enterprise 7.2 and "NX: true"

### ISSUE THREAD

**Issue by nthx** [sidekiq/sidekiq#6240]
Ruby version: 3.0.6
Rails version: 7.0.8.1
Sidekiq / Pro / Enterprise version(s): affected 7.2.2
Sidekiq / Pro / Enterprise version(s): not affected 7.1.2
Redis server version: redis_version: 6.2.13; but 7.+ is also affected

## Description
When starting sidekiq `sidekiq -c 2` it raises an error, but continues to run. The error:
> TypeError: Unsupported command argument type: TrueClass

NOTE: I have modified the error in the following log, to get the full context of what's actually being sent to Redis.

Patch that fixes the issue:
> /site/public/.rvm/gems/ruby-3.0.6/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/senate.rb:85
      result = redis { |conn|
        #conn.set(@key, identity, ex: TTL, nx: true) == "OK"
        conn.call("SET",@key,identity,"EX",TTL,"NX") == "OK"
      }

I have also checked Redis documentation and "NX" command takes no arguments
https://redis.io/commands/set/

```
@pc:~$ redis-cli -h pc -p 6379  -n 3 
pc:6379[3]> set 'foo' 'value' EX 1 NX 'true'
(error) ERR syntax error
pc:6379[3]> set 'foo' 'value' EX 1 NX
OK
```

The solution for me is NOT to upgrade to the latest 7.2, but stay at 7.1.* of `sidekiq` gem

Let me know if you need more information.

Full startup log:
```
INFO: Booted Rails 7.0.8.1 application in development environment 
INFO: Running in ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
INFO: Sidekiq Pro 7.1.5 / Sidekiq Enterprise 7.1.2, commercially licensed.
INFO: Sidekiq 7.2.2 connecting to Redis with options {:size=>10, :pool_name=>"internal"
INFO: Sidekiq 7.2.2 connecting to Redis with options {:size=>3, :pool_name=>"default"
INFO: Starting processing, hit Ctrl-C to stop
WARN: {"context":"senate"}
WARN: TypeError: Unsupported command argument type: TrueClass: ["set", "dear-leader", "pc.lan:2445951:8f660de463ce", "ex", "60", "nx", true] args: ["set", "dear-leader", "pc.lan:2445951:8f660de463ce", {:ex=>60, :nx=>true}] kwargs: {}
WARN: 
INFO: DEPRECATION: Sidekiq exception handlers now take three arguments, see #<Proc:0x0000559a7f272f30 .rvm/gems/ruby-3.0.6/gems/rollbar-3.3.1/lib/rollbar/plugins/sidekiq.rb:15>
#<Thread:0x0000559a81e2b000@sidekiq.senate .rvm/gems/ruby-3.0.6/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:17 run> terminated with exception (report_on_exception is true):
.rvm/gems/ruby-3.0.6/gems/redis-client-0.21.1/lib/redis_client/command_builder.rb:38:in `block in generate': Unsupported command argument type: TrueClass: ["set", "dear-leader", "pc.lan:2445951:8f660de463ce", "ex", "60", "nx", true] args: ["set", "dear-leader", "pc.lan:2445951:8f660de463ce", {:ex=>60, :nx=>true}] kwargs: {} (TypeError)
        from .rvm/gems/ruby-3.0.6/gems/redis-client-0.21.1/lib/redis_client/command_builder.rb:28:in `map!'
        from .rvm/gems/ruby-3.0.6/gems/redis-client-0.21.1/lib/redis_client/command_builder.rb:28:in `generate'
        from .rvm/gems/ruby-3.0.6/gems/redis-client-0.21.1/lib/redis_client.rb:276:in `call'
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-7.2.2/lib/sidekiq/redis_client_adapter.rb:36:in `block (2 levels) in <module:CompatMethods>'
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/senate.rb:85:in `block in stage_coup!' 
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-7.2.2/lib/sidekiq/config.rb:163:in `block in redis'
        from .rvm/gems/ruby-3.0.6/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
        from .rvm/gems/ruby-3.0.6/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
        from .rvm/gems/ruby-3.0.6/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
        from .rvm/gems/ruby-3.0.6/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
        from .rvm/gems/ruby-3.0.6/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-7.2.2/lib/sidekiq/config.rb:160:in `redis'
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:28:in `redis'
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/senate.rb:83:in `stage_coup!'
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-ent-7.1.2/lib/sidekiq-ent/senate.rb:98:in `cycle'
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:10:in `watchdog'
        from .rvm/gems/ruby-3.0.6/gems/sidekiq-7.2.2/lib/sidekiq/component.rb:19:in `block in safe_thread' 
```

**Comment by mperham** [comment]
You upgraded Sidekiq Enterprise incorrectly, leading to version mismatch.

## Incorrect:

```
bundle up sidekiq
```

## Correct:

```
bundle up sidekiq-ent
```

**Comment by nthx** [comment]
Thank you @mperham 

Actually I wasn't upgrading sidekiq. I was upgrading another gem `sidekiq-throttled` and did not want to upgrade anything else. The upgrade triggered additional `sidekiq` upgrade (only) and `redis-client`. Nothing else really.

However, with your suggestion of upgrading `sidekiq-ent`, it seems the issue is gone. Thank you a lot!
