### ISSUE TITLE
sidekiq-ent: unknown keyword: :cluster_safe (ArgumentError)

### ISSUE THREAD

**Issue by karlentwistle** [sidekiq/sidekiq#6324]
Since upgrading to sidekiq-ent (7.2.3) I am seeing the following error when I attempt to launch a rails console or run the server

```
unknown keyword: :cluster_safe (ArgumentError)
```

Ruby version: 3.3.2
Rails version: 7.1.3.4
Sidekiq / Pro / Enterprise version(s): 
  - sidekiq (7.2.4)
  - sidekiq-ent (7.2.3)
  - sidekiq-pro (7.2.1)

`config/initializers/sidekiq.rb`

```ruby
Sidekiq::Limiter.configure do |config|
  config.redis = { size: 10, url: 'redis://localhost/15' }
end
```

`sidekiq.yml`

```yaml
---
default: &default
  server_logging_level: <%= Logger::INFO %>
  max_retries: 10 # dead after roughly 4h 22m

development:
  <<: *default

review:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```

Running `bin/rails c`

```
/Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/redis-client-0.22.2/lib/redis_client/config.rb:21:in `initialize': unknown keyword: :cluster_safe (ArgumentError)
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/redis-client-0.22.2/lib/redis_client/config.rb:207:in `initialize'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/redis-client-0.22.2/lib/redis_client.rb:166:in `new'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/redis-client-0.22.2/lib/redis_client.rb:166:in `config'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-7.2.4/lib/sidekiq/redis_client_adapter.rb:68:in `initialize'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-7.2.4/lib/sidekiq/redis_connection.rb:22:in `new'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-7.2.4/lib/sidekiq/redis_connection.rb:22:in `create'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-ent-7.2.3/lib/sidekiq-ent/limiter.rb:92:in `redis='
from /Users/karl/local/biggerpockets/lib/sidekiq_limiters.rb:6:in `block in <main>'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-ent-7.2.3/lib/sidekiq-ent/limiter.rb:85:in `configure'
from /Users/karl/local/biggerpockets/lib/sidekiq_limiters.rb:5:in `<main>'
from /Users/karl/local/biggerpockets/config/initializers/searchkick.rb:3:in `require_relative'
from /Users/karl/local/biggerpockets/config/initializers/searchkick.rb:3:in `<main>'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:690:in `load'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:690:in `block in load_config_initializer'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:208:in `instrument'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:689:in `load_config_initializer'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:643:in `block (2 levels) in <class:Engine>'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:642:in `each'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:642:in `block in <class:Engine>'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `instance_exec'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `run'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:425:in `block (2 levels) in each_strongly_connected_component_from'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:424:in `block in each_strongly_connected_component_from'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:50:in `each'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:418:in `call'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:418:in `each_strongly_connected_component_from'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `each'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `call'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:60:in `run_initializers'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application.rb:426:in `initialize!'
from /Users/karl/local/biggerpockets/config/environment.rb:8:in `<main>'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.15/lib/zeitwerk/kernel.rb:34:in `require'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application.rb:402:in `require_environment!'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command/actions.rb:20:in `boot_application!'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/console/console_command.rb:105:in `perform'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command/base.rb:178:in `invoke_command'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command/base.rb:73:in `perform'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:71:in `block in invoke'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<main>'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
from /Users/karl/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from bin/rails:9:in `<main>'
```

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 5ea91f335c..25621484b3 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -80,12 +80,13 @@ GIT
 GEM
   remote: https://enterprise.contribsys.com/
   specs:
-    sidekiq-ent (7.2.2)
+    sidekiq-ent (7.2.3)
       einhorn (~> 1.0)
       gserver
       sidekiq (>= 7.2.0, < 8)
       sidekiq-pro (>= 7.2.0, < 8)
-    sidekiq-pro (7.2.0)
+    sidekiq-pro (7.2.1)
+      base64
       sidekiq (>= 7.2.0, < 8)

 GEM
```

Please let me know if you'd like any further information.

**Comment by mperham** [comment]
Ugh, this change went into Sidekiq 7.3.0 and needs to be in Ent 7.3.0 also. Will revert.

**Comment by mperham** [comment]
724 is out.
