### ISSUE TITLE
Unmet dependency: Redis 6.2.0 doesn't exist

### ISSUE THREAD

**Issue by badde-media** [sidekiq/sidekiq#6335]
Ruby version: ruby 3.3.2 (2024-05-30 revision e5a195edf6) [x86_64-linux] (asdf)
Rails version: Rails 7.1.3.4
Sidekiq / Pro / Enterprise version(s): sidekiq (7.2.4)

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
I'm trying to get Rails BulletTrain running. That seems to have a sidekiq dep to redis 6.2.0, which doesn't exist. Possibly a typo?
```
worker           | You are connecting to Redis 6.0.16, Sidekiq requires Redis 6.2.0 or greater
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-7.2.4/lib/sidekiq/cli.rb:77:in `run'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/sidekiq-7.2.4/bin/sidekiq:31:in `<top (required)>'
worker           | /home/un/.asdf/installs/ruby/3.3.2/bin/sidekiq:25:in `load'
worker           | /home/un/.asdf/installs/ruby/3.3.2/bin/sidekiq:25:in `<top (required)>'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
worker           | /home/un/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
worker           | /home/un/.asdf/installs/ruby/3.3.2/bin/bundle:25:in `load'
worker           | /home/un/.asdf/installs/ruby/3.3.2/bin/bundle:25:in `<main>'
worker           | Exited with code 1
light-css        |
light-css        | Rebuilding...
web              | Interrupting...
js               | Interrupting...
light-css        | Interrupting...
light-mailer-css | Interrupting...
web              | [212287] - Gracefully shutting down workers...
js               | Exited with code 0
light-mailer-css | Exited with code 0
light-css        | Exited with code 0
web              | [212287] === puma shutdown: 2024-06-19 22:13:29 +0300 ===
web              | [212287] - Goodbye!
web              | Exiting
web              | Exited with code 0
```

Steps to reproduce:  Follow installation instructions here:
https://github.com/bullet-train-co/bullet_train
Then install the missing yarn dependencies, set up the database.yml and its credentials, run bin/dev
(Windows 11 / WSL2)

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?
not yet, will do
https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by badde-media** [comment]
nothing to update

**Comment by badde-media** [comment]
After correcting the version requirement from the non-existent version 6.2.0 to 5.2.0, BulletTrain boots without errors
