### ISSUE TITLE
`NOAUTH Authentication required` on heroku Redis Cloud since upgrading to 7.x

### ISSUE THREAD

**Issue by chimpanstache** [sidekiq/sidekiq#6362]
I'm trying to upgrade the rails version of my app from 7.0.8.3 to 7.1.2 and thus upgrading sidekiq version from 6.5.10 to 7.2.4.
I'm using Heroku pipeline for deployment and hosting, with a staging and production app. 
I'm using the Heroku Redis Cloud add-on. 
Everything works fine with sidekiq 6.5.10 even when I roll back, but as soon as I upgrade rails and sidekiq on staging it breaks.
Also everything works fine with a local server on all versions.

Ruby version: 3.2.0
Rails version: Rails 7.1.2
Sidekiq version(s): sidekiq-7.3.0

```
# config/initializers/sidekiq.rb

Sidekiq.configure_server do |config|
  config.redis = { url: ENV["REDIS_SIDEKIQ_URL"] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV["REDIS_SIDEKIQ_URL"] }
end

Sidekiq.strict_args! unless Rails.env.production?
```

```
# config/sidekiq.yml

---
:queues:
  - default
  - webhooks
  - mailers
  - low_priority
 ```

```
# backtrace

2024-07-11T10:18:03.555936+00:00 heroku[web.1]: Restarting
2024-07-11T10:18:03.603961+00:00 heroku[web.1]: State changed from up to starting
2024-07-11T10:18:03.737201+00:00 heroku[worker.1]: Restarting
2024-07-11T10:18:03.739484+00:00 heroku[worker.1]: State changed from up to starting
2024-07-11T10:18:04.176740+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2024-07-11T10:18:04.197905+00:00 app[worker.1]: pid=2 tid=42q INFO: Shutting down
2024-07-11T10:18:04.197930+00:00 app[worker.1]: pid=2 tid=42q INFO: Terminating quiet threads for default capsule
2024-07-11T10:18:04.197987+00:00 app[worker.1]: NOAUTH Authentication required (redis://[private-hostname]:[port])
2024-07-11T10:18:04.197998+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.22.2/lib/redis_client/connection_mixin.rb:36:in `call'
2024-07-11T10:18:04.197998+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:279:in `block (2 levels) in call'
2024-07-11T10:18:04.197998+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.22.2/lib/redis_client/middlewares.rb:16:in `call'
2024-07-11T10:18:04.197998+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:278:in `block in call'
2024-07-11T10:18:04.197999+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:699:in `ensure_connected'
2024-07-11T10:18:04.197999+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:277:in `call'
2024-07-11T10:18:04.198002+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/redis_client_adapter.rb:36:in `block (2 levels) in <module:CompatMethods>'
2024-07-11T10:18:04.198002+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/scheduled.rb:196:in `block in cleanup'
2024-07-11T10:18:04.198003+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/config.rb:167:in `block in redis'
2024-07-11T10:18:04.198004+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
2024-07-11T10:18:04.198004+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
2024-07-11T10:18:04.198004+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
2024-07-11T10:18:04.198004+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
2024-07-11T10:18:04.198005+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
2024-07-11T10:18:04.198005+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/config.rb:164:in `redis'
2024-07-11T10:18:04.198005+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/component.rb:28:in `redis'
2024-07-11T10:18:04.198005+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/scheduled.rb:196:in `cleanup'
2024-07-11T10:18:04.198005+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/scheduled.rb:232:in `initial_wait'
2024-07-11T10:18:04.198005+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/scheduled.rb:96:in `block in start'
2024-07-11T10:18:04.198006+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/component.rb:10:in `watchdog'
2024-07-11T10:18:04.198006+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.3.0/lib/sidekiq/component.rb:19:in `block in safe_thread'
2024-07-11T10:18:04.273276+00:00 heroku[worker.1]: Process exited with status 1
2024-07-11T10:18:04.318684+00:00 heroku[web.1]: Stopping all processes with SIGTERM
```

**Comment by mperham** [comment]
Did you read the 7.0 upgrade notes?

**Comment by chimpanstache** [comment]
Not diligently enough I guess, which part should I emphasize on?

**Comment by chimpanstache** [comment]
Just switched Redis protocol from RESP2 to RESP3, and it works... Rookie mistake, my bad.

**Comment by andreihelo** [comment]
Hi @chimpanstache, do you mind sharing more details about exactly what you did to solve it? I am facing the same issue and from my understanding, this could be done through the Sidekiq initializer file:

```
Sidekiq.configure_server do |config|
  config.redis = { protocol: 3 }
end
```

**Comment by chimpanstache** [comment]
I configured the change on redis side, not sidekiq. If you're using the Redis Cloud add-on, you can toggle it in the "edit database configuration" page.
![Screenshot 2024-07-12 at 19 52 31](https://github.com/user-attachments/assets/7c894f9e-48f3-499d-a72b-e99850c63cf3)
