### ISSUE TITLE
7.3.0+: Issue when running sidekiq-scheduler specs against 2.7

### ISSUE THREAD

**Issue by tagliala** [sidekiq/sidekiq#6371]
Hello,

this can be a bug in Ruby, however I think it should be reported

Ruby version: 2.7.8
Rails version: n/a
Sidekiq / Pro / Enterprise version(s): `7.3.0` and current `main`

Ref: https://github.com/sidekiq-scheduler/sidekiq-scheduler/actions/runs/10040804893/job/27747574809?pr=486#step:5:108

```
  1) Sidekiq::Web GET /recurring-jobs when the next execution time is setted 
     Failure/Error: erb File.read(File.join(VIEW_PATH, 'recurring_jobs.erb'))
     
     FrozenError:
       can't modify frozen String: "<link"
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/helpers.rb:42:in `block in html_tag'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/helpers.rb:40:in `each_pair'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/helpers.rb:40:in `html_tag'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/helpers.rb:22:in `style_tag'
     # (erb):2:in `_erb'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/action.rb:93:in `_erb'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/action.rb:64:in `erb'
     # ./lib/sidekiq-scheduler/web.rb:15:in `block in registered'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/application.rb:416:in `instance_exec'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/application.rb:416:in `block in call'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/application.rb:414:in `catch'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web/application.rb:414:in `call'
     # ~/.rvm/gems/ruby-2.7.8/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:266:in `context'
     # ~/.rvm/gems/ruby-2.7.8/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:260:in `call'
     # ~/.rvm/gems/ruby-2.7.8/gems/rack-2.2.9/lib/rack/static.rb:161:in `call'
     # ~/.rvm/gems/ruby-2.7.8/gems/rack-2.2.9/lib/rack/static.rb:161:in `call'
     # ~/.rvm/gems/ruby-2.7.8/gems/rack-2.2.9/lib/rack/builder.rb:244:in `call'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web.rb:121:in `call'
     # ~/.rvm/gems/ruby-2.7.8/bundler/gems/sidekiq-0226e311d02d/lib/sidekiq/web.rb:126:in `call'
     # ~/.rvm/gems/ruby-2.7.8/gems/rack-test-2.1.0/lib/rack/test.rb:360:in `process_request'
     # ~/.rvm/gems/ruby-2.7.8/gems/rack-test-2.1.0/lib/rack/test.rb:163:in `custom_request'
     # ~/.rvm/gems/ruby-2.7.8/gems/rack-test-2.1.0/lib/rack/test.rb:112:in `get'
     # ./spec/sidekiq-scheduler/web_spec.rb:39:in `block (3 levels) in <top (required)>'
     # ./spec/sidekiq-scheduler/web_spec.rb:72:in `block (4 levels) in <top (required)>'
```

### Cause of the issue

https://github.com/sidekiq/sidekiq/blob/0226e311d02de8ea77563c17c96a3d6527d0ec7f/lib/sidekiq/web/helpers.rb#L39

Apparently, in Ruby 2.7 `s` is frozen (Ruby bug? Behavior change in 3.0?), causing subsequent calls to `<<` to fail.

### Solution(s)

A. Bump minimum required Ruby version to 3.0
B. `add a +` to unfreeze the string and add a note to drop the `+` together with Ruby 2.7 support
  ```diff
  - s = "<#{tagname}" 
  + s = +"<#{tagname}" # TODO: remove `+` when dropping 2.7 support, sidekiq/sidekiq#6371
  ```

**Comment by Earlopain** [comment]
It's not a ruby bug, in 2.7 interpolated strings follow the magic comment.

**Comment by mperham** [comment]
PR welcome.

**Comment by tagliala** [comment]
Thanks
