### ISSUE TITLE
Sidekiq 7.x on Ruby 2.7 crashes on `hash.except("at")`

### ISSUE THREAD

**Issue by mhenrixon** [sidekiq/sidekiq#6376]
Ruby version: 2.7
Rails version: None
Sidekiq / Pro / Enterprise version(s):

https://github.com/mhenrixon/sidekiq-unique-jobs/actions/runs/10094768753/job/27913351109?pr=853 

It looks like ruby 2.7 is failing all Sidekiq 7.x versions due to the method `.except` not being available on a hash. 

```
32) UntilExpiredJob client middleware when job is delayed sets keys to expire as per configuration
      Failure/Error: before { described_class.perform_in(60, 1, 2) }

      NoMethodError:
        undefined method `except' for #<Hash:0x000055974be61490>
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/client.rb:254:in `block in atomic_push'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/client.rb:250:in `each'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/client.rb:250:in `flat_map'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/client.rb:250:in `atomic_push'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/testing.rb:103:in `atomic_push'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/client.rb:229:in `block (2 levels) in raw_push'
      # ./vendor/bundle/ruby/2.7.0/gems/redis-client-0.22.2/lib/redis_client/decorator.rb:51:in `block in pipelined'
      # ./vendor/bundle/ruby/2.7.0/gems/redis-client-0.22.2/lib/redis_client.rb:426:in `pipelined'
      # ./vendor/bundle/ruby/2.7.0/gems/redis-client-0.22.2/lib/redis_client/decorator.rb:51:in `pipelined'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/client.rb:228:in `block in raw_push'
      # ./vendor/bundle/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
      # ./vendor/bundle/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
      # ./vendor/bundle/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
      # ./vendor/bundle/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
      # ./vendor/bundle/ruby/2.7.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/client.rb:225:in `raw_push'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/client.rb:93:in `push'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/job.rb:372:in `client_push'
      # ./vendor/bundle/ruby/2.7.0/gems/sidekiq-7.3.0/lib/sidekiq/job.rb:342:in `perform_in'
      # ./spec/workers/until_expired_job_spec.rb:21:in `block (4 levels) in <top (required)>'
```

**Comment by mperham** [comment]
Oops, looks like we are missing some test coverage.

**Comment by mhenrixon** [comment]
> Oops, looks like we are missing some test coverage.

I think your tests pass because you have loaded active support, if you remove that gem the tests likely fail as except was added to newer Ruby?
