### ISSUE TITLE
Batch tests fail without running Redis instance available

### ISSUE THREAD

**Issue by micahhainlinetruelink** [sidekiq/sidekiq#6377]
I'm trying to test a batch job and finding that the batch block is trying to make a real redis connection to save metadata about the batch. Without a locally running redis, my test fails. With a locally running redis, the test actually writes some of the batch information to redis, though the jobs do not get enqueued there.

Normally when testing, a MyJob.perform_async eventually gets to the TestingClient.atomic_push, and the `conn` (while still a real connection) never gets called with anything and so never fails when a Redis isn't available. `Sidekiq::Batch#jobs` however ends up using the connection directly:
```
          redis(bid) do |conn|
            conn.multi do |m|
              m.hset(@key, *data)
              # only want to incr kids when the batch is first created,
              # not when reopened to add more jobs.
              m.hincrby("b-#{myparent}", "kids", 1) if myparent
              # Default expiry is one day for newly created batches.
              # If jobs are added to the batch, it is extended to 30 days.
              m.expire(@key, ONE_DAY)
            end
          end
```

The guidance for testing in the [wiki](https://github.com/sidekiq/sidekiq/wiki/Batches#testing) doesn't seem to provide any help for this or indication that it's expected behavior, and I can't seem to find an effective workaround other than bringing up a redis instance and clearing it after the test. At least that's the only way I can get the :success and :completed callbacks to fire in testing.

Ruby version: 3.1.4
Rails version: 7.0.8.4
Sidekiq / Pro / Enterprise version(s): Pro 7.3.0
sidekiq.yml
```
---
:concurrency: 3
:queues:
  - high
  - default
  - low
```

Stacktrace:
```
2024-07-25T20:15:37.067Z pid=14947 tid=3bf INFO: Sidekiq 7.3.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>nil}
RedisClient::CannotConnectError: Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379)

     RedisClient::CannotConnectError:
       Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379)
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client/ruby_connection.rb:119:in `connect'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client/ruby_connection.rb:51:in `initialize'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client.rb:746:in `new'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client.rb:746:in `block in connect'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client/middlewares.rb:12:in `connect'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client.rb:745:in `connect'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client.rb:732:in `raw_connection'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client.rb:697:in `ensure_connected'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client.rb:470:in `multi'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client/decorator.rb:55:in `multi'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-pro-7.3.0/lib/sidekiq/batch.rb:235:in `block in jobs'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/config.rb:167:in `block in redis'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/config.rb:164:in `redis'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq.rb:74:in `redis'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-pro-7.3.0/lib/sidekiq/batch.rb:38:in `redis'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-pro-7.3.0/lib/sidekiq/batch.rb:49:in `redis'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-pro-7.3.0/lib/sidekiq/batch.rb:234:in `jobs'
     # ./app/jobs/batch_sleeping_job.rb:11:in `perform'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/testing.rb:295:in `execute_job'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/testing.rb:290:in `block in process_job'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:180:in `traverse'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-pro-7.3.0/lib/sidekiq/batch/middleware.rb:58:in `call'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:173:in `invoke'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/testing.rb:289:in `process_job'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/testing.rb:273:in `drain'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/testing.rb:315:in `block in drain_all'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/testing.rb:314:in `each'
     # /Users/micah/.rvm/gems/ruby-3.1.4/gems/sidekiq-7.3.0/lib/sidekiq/testing.rb:314:in `drain_all'
     # ./spec/jobs/batch_sleeping_job_spec.rb:10:in `block (2 levels) in <top (required)>'
        ...
     # ------------------
     # --- Caused by: ---
     # Errno::ECONNREFUSED:
     #   Connection refused - connect(2) for 127.0.0.1:6379
     #   /Users/micah/.rvm/gems/ruby-3.1.4/gems/redis-client-0.22.2/lib/redis_client/ruby_connection.rb:119:in `connect'
```

**Comment by mperham** [comment]
Correct, batches require Redis.

**Comment by micahhainlinetruelink** [comment]
I would suggest adding this information to the testing section of the batches wiki

**Comment by micahhainlinetruelink** [comment]
> I would suggest adding this information to the testing section of the batches wiki

Never mind, I see that it's already been added. Thanks!
