### ISSUE TITLE
Running sidekiqswarm on docker container

### ISSUE THREAD

**Issue by yossiedri** [sidekiq/sidekiq#6381]
Ruby version: 2.7.2
Rails version: 5.2.7.1
Sidekiq / Pro / Enterprise version(s):
sidekiq (7.2.4)
sidekiq-ent (7.2.2)
sidekiq-pro (7.2.1)

Hi Mike
followup this issue https://github.com/sidekiq/sidekiq/issues/6346
Im running swarm as you suggested and im getting the error below, please advise
SIDEKIQ_PRELOAD_APP=true MALLOC_ARENA_MAX=2 RAILS_ENV=$REDMINE_ENV bundle exec sidekiqswarm 

Start sidekiq with RAILS_ENV: aws_staging SIDEKIQ_PRELOAD_APP: true MALLOC_ARENA_MAX: 2
[swarm] Preloading Bundler groups ["default"]
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
bundler: failed to load command: sidekiqswarm (/usr/local/bundle/bin/sidekiqswarm)
NameError: uninitialized constant ActiveRecord
Did you mean?  ActiveModel
  /app/plugins/sneaky-save/lib/sneaky-save.rb:113:in `<top (required)>'
  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
  /usr/local/bundle/gems/sidekiq-ent-7.2.2/bin/sidekiqswarm:40:in `<top (required)>'
  /usr/local/bundle/bin/sidekiqswarm:25:in `load'
  /usr/local/bundle/bin/sidekiqswarm:25:in `<top (required)>'
thanks
yossi

**Comment by mperham** [comment]
Rails 5 is no longer supported.

**Comment by yossiedri** [comment]
but running sidekiq insted works

SIDEKIQ_PRELOAD_APP=true MALLOC_ARENA_MAX=2 RAILS_ENV=aws_staging bundle exec sidekiq
Sidekiq 7.2.4 only supports Rails 6+
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
SERVERURL: https://rm-staging.mellanox.com Rails Env: aws_staging
REDIS_CONFIG: {"host"=>"redmine-redis-dev-01.wdh5cq.0001.usw2.cache.amazonaws.com", "port"=>6379, "thread_safe"=>true}
Connecting to Redis...
Redis connection established...
SIDEKIQ::REDIS_CONFIG: {"host"=>"redmine-redis-dev-01.wdh5cq.0001.usw2.cache.amazonaws.com", "port"=>6379, "thread_safe"=>true}
SIDEKIQ::redis_conn: {:url=>"redis://redmine-redis-dev-01.wdh5cq.0001.usw2.cache.amazonaws.com:6379"}
no schanduled tasks

**Comment by yossiedri** [comment]
what is the version i can use for rails 5?

**Comment by mperham** [comment]
As the Sidekiq 7 upgrade notes say, only Rails 6+ is supported. Sidekiq 6 supports Rails 5.

If you disable preload app, it will likely work just fine.

**Comment by yossiedri** [comment]
how can i disable preload app?

**Comment by mperham** [comment]
Look at your command: SIDEKIQ_PRELOAD_APP=true

**Comment by yossiedri** [comment]
still has same error.
im using sidekiq-ent my gemfile
source "https://enterprise.contribsys.com/" do
  gem 'sidekiq-ent'
end
what version of sidekiq-ent gem should i set to work with rails 5?

**Comment by mperham** [comment]
You don’t lock Ent. You lock Sidekiq to 6.x.
