### ISSUE TITLE
uninitialized constant Sidekiq::Component after upgrading from 7.2.4 to 7.3.0

### ISSUE THREAD

**Issue by xanderman** [sidekiq/sidekiq#6395]
Ruby version: 3.2.2p53
Rails version: 7.1.3.4
Sidekiq / Pro / Enterprise version(s): 7.3.0

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```
/Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/sidekiq-7.3.0/lib/sidekiq/job_logger.rb:5:in `<class:JobLogger>': uninitialized constant Sidekiq::Component (NameError)

    include Sidekiq::Component
                   ^^^^^^^^^^^
Did you mean?  Complex
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/sidekiq-7.3.0/lib/sidekiq/job_logger.rb:4:in `<module:Sidekiq>'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/sidekiq-7.3.0/lib/sidekiq/job_logger.rb:3:in `<main>'
        from <internal:/Users/bobgardner/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/bobgardner/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/sidekiq-logstash-3.0.0/lib/sidekiq/logstash_job_logger.rb:3:in `<main>'
        from <internal:/Users/bobgardner/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/bobgardner/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/sidekiq-logstash-3.0.0/lib/sidekiq/logstash.rb:7:in `<main>'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:73:in `rescue in block in require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:51:in `block in require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `each'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler.rb:187:in `require'
        from /Users/bobgardner/src/document-management/config/application.rb:19:in `<main>'
        from <internal:/Users/bobgardner/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/bobgardner/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/command/actions.rb:15:in `require_application!'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/command/environment_argument.rb:31:in `require_application!'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/command/actions.rb:19:in `boot_application!'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/commands/console/console_command.rb:105:in `perform'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/command/base.rb:73:in `perform'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/command.rb:71:in `block in invoke'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Users/bobgardner/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/bobgardner/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/bobgardner/.rvm/gems/ruby-3.2.2/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:5:in `<main>'
```

This is, in essence, a reoccurrence of #5462 but in a new file. 6677b45 added `include Sidekiq::Component` to `job_logger.rb` but did not add `require "sidekiq/component"` (as in 9d5a6d7). [sidekiq-logstash](https://github.com/iMacTia/sidekiq-logstash) has [`LogstashJobLogger`](https://github.com/iMacTia/sidekiq-logstash/blob/master/lib/sidekiq/logstash_job_logger.rb) that inherits from `Sidekiq::JobLogger`, which leads to the error above during loading. I've confirmed that adding `require "sidekiq/component"` in `job_logger.rb` fixes the error for me.

**Comment by mperham** [comment]
Bug in sidekiq-logstash. Components are only usable inside the Sidekiq process and I assume this is in puma.

**Comment by xanderman** [comment]
I see this running `rspec` and `rails c`. I believe simply requiring sidekiq-logstash is enough, which by default bundle will do in all modes. I seem to have resolved this by setting `gem sidekiq-logstash, require: false` in my Gemfile, and `require "sidekiq/logstash"` in `config/initializers/sidekiq.rb`.
