### ISSUE TITLE
undefined method broadcast for class ActiveSupport::Logger using sidekiq 7.3.0 with rails 7.1.3.4 in Docker

### ISSUE THREAD

**Issue by hildebrandjp** [sidekiq/sidekiq#6396]
Can you help me please?

I am using docker for running the application.
I am running docker with environment variables.
But this error appears when the command `bundle exec sidekiq` is executed.
Also, I am using the latest version of sidekiq

It is odd that when I run the docker build & docker run on Windows OS, the sidekiq is operating fine. But when docker build & docker run on Linux Debian OS the error below is shown.

Is my Dockerfile misconfigure?

I know this is related to this issue: https://github.com/sidekiq/sidekiq/issues/6054
But I cannot fix using the sidekiq latest version.

```
Ruby version: 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
Rails version: 7.1.3.4
```

Dockerfile
```
# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.3.4
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim AS base

# Rails app lives here
WORKDIR /rails

ARG BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_DEPLOYMENT=1 \
    RAILS_ENV=production

ENV RAILS_ENV=$RAILS_ENV \
    BUNDLE_DEPLOYMENT=${BUNDLE_DEPLOYMENT} \
    BUNDLE_PATH=${BUNDLE_PATH} \
    BUNDLE_WITHOUT="development"

.....

EXPOSE 3000

CMD ["/bin/sh", "-c", "rm -f tmp/pids/server.pid & bin/rails db:migrate & bundle exec sidekiq & bin/rails s -b '0.0.0.0'"]

```

Gemfile
```
ruby '3.3.4'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.1.3', '>= 7.1.3.4'

.....

gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sidekiq-unique-jobs'
gem 'activejob-uniqueness'
```

Output console:
```
undefined method `broadcast' for class ActiveSupport::Logger
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/rails.rb:66:in `block (2 levels) in <class:Rails>'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq.rb:99:in `configure_server'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/rails.rb:57:in `block in <class:Rails>'
/usr/local/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'
/usr/local/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
/usr/local/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
/usr/local/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
/usr/local/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:77:in `each'
/usr/local/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
/usr/local/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/application/finisher.rb:93:in `block in <module:Finisher>'
/usr/local/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
/usr/local/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each'
/usr/local/lib/ruby/3.3.0/tsort.rb:350:in `call'
/usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
/usr/local/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
/usr/local/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
/usr/local/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/application.rb:426:in `initialize!'
/rails/config/environment.rb:5:in `<top (required)>'
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/cli.rb:305:in `boot_application'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/cli.rb:42:in `run'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.0/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/ruby/3.3.0/bin/sidekiq:25:in `load'
/usr/local/bundle/ruby/3.3.0/bin/sidekiq:25:in `<top (required)>'
/usr/local/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
/usr/local/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
/usr/local/lib/ruby/3.3.0/bundler/cli.rb:455:in `exec'
/usr/local/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/lib/ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
/usr/local/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/lib/ruby/3.3.0/bundler/cli.rb:29:in `start'
/usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
/usr/local/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.3.4-p94) ("The Eagle of Durango")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 10
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1723532922.840949      64 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=0
I0000 00:00:1723532922.842705      64 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723532922.862497      64 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723532922.862816      64 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723532922.876337      65 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723532922.876405      65 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723532922.876936      65 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723532922.877005      65 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723533039.969085     531 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723533039.969174     531 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723533039.969624     531 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1
I0000 00:00:1723533039.969698     531 rb_grpc.c:331] GRPC_RUBY: grpc_ruby_init_threads g_bg_thread_init_done=1

```

**Comment by mperham** [comment]
> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR

what is absl? My guess is that’s the problem. Use standard logging, don’t customize it.

**Comment by hildebrandjp** [comment]
> > WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> 
> what is absl? My guess is that’s the problem. Use standard logging, don’t customize it.

Since I upgrade to latest rails 7.1.3.4 from 6.0.x.
I have been using some of my old configuration from old rails version.

Is this absl coming from Rails logging or from sidekiq logging?
Or is it coming from package from Debian OS?
I research where this absl come from but I think it is use in  `grpc` if I am not mistaken. 

I would like to share my config/initializers/sidekiq.rb & production.rb if there is something wrong?
```
Sidekiq.configure_server do |config|
  config.logger.level = Logger::WARN
  config.logger = Sidekiq::Logger.new($stdout)
  config.redis = { url: ENV['REDIS_URL_SIDEKIQ'] || 'redis://redis:6379/1' }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL_SIDEKIQ'] || 'redis://redis:6379/1' }
end

schedule_file = "config/schedule.yml"

if File.exist?(schedule_file) && Sidekiq.server?
  Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
end
```

environments/production.rb
```
config.logger = ActiveSupport::Logger.new(STDOUT)
    .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
    .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
```

**Comment by mperham** [comment]
Get rid of this, use Rails's default logging:

> config.logger = ActiveSupport::Logger.new(STDOUT) .tap { |logger| logger.formatter = ::Logger::Formatter.new } .then { |logger| ActiveSupport::TaggedLogging.new(logger) }

**Comment by mperham** [comment]
And this:

> config.logger = Sidekiq::Logger.new($stdout)

**Comment by hildebrandjp** [comment]
> Get rid of this, use Rails's default logging:
> 
> > config.logger = ActiveSupport::Logger.new(STDOUT) .tap { |logger| logger.formatter = ::Logger::Formatter.new } .then { |logger| ActiveSupport::TaggedLogging.new(logger) }

Thank you so much @mperham!
I was able to run without the errors.

![image](https://github.com/user-attachments/assets/774cd716-9612-4078-9457-ccfb17ef0ec2)
