### ISSUE TITLE
ERB error backtrace does not show template filename

### ISSUE THREAD

**Issue by mperham** [sidekiq/sidekiq#6407]
I noticed in a previous issue that an error backtrace from `batches.erb` in Sidekiq Pro does not appear in the backtrace. Instead it shows `(erb)` with no context.

```
NoMethodError: undefined method `utc' for nil (NoMethodError)
  from (erb):31:in `block in _erb'
  from (erb):22:in `each'
  from (erb):22:in `_erb'
  from erb.rb:429:in `eval'
  from erb.rb:429:in `result'
  from sidekiq (7.3.0) lib/sidekiq/web/action.rb:93:in `_erb'
  from sidekiq (7.3.0) lib/sidekiq/web/action.rb:64:in `erb'
  from sidekiq (7.3.0) lib/sidekiq/web/action.rb:73:in `render'
```

I noticed if I add a RuntimeError to a random page, the backtrace looks like this even though the error is raised in the dead.erb template itself:

```
RuntimeError: boo
    lib/sidekiq/web/action.rb:66:in `_erb_dead'
    lib/sidekiq/web/action.rb:96:in `_erb'
    lib/sidekiq/web/action.rb:65:in `erb'
    lib/sidekiq/web/application.rb:172:in `block in <class:WebApplication>'
    lib/sidekiq/web/application.rb:416:in `instance_exec'
    lib/sidekiq/web/application.rb:416:in `block in call'
    lib/sidekiq/web/application.rb:414:in `catch'
```

How can we improve this?

**Comment by mperham** [comment]
I suspect the problem lies in sidekiq/web/action.rb:51.

**Comment by davetron5000** [comment]
This should improve things:

```ruby
erb_filename = "#{views}/#{content}.erb"
template = ERB.new(File.read(erb_filename))
template.location = [  erb_filename, 1 ] # <----
src = template.src
```

The `, 1]` is a line number so I'm not sure your stack trace will have a decent line number in it, but it should show the filename.
