### ISSUE TITLE
JSON::ParserError  Sidekiq

### ISSUE THREAD

**Issue by StoneGod** [sidekiq/sidekiq#6446]
Ruby version: 3.3.4
Rails version: 7.1.4
Sidekiq version(s): 7.3.2
opentelemetry-instrumentation-sidekiq version(s): (0.25.7)

Sometimes I get an error about once a day in Sentry

```
JSON::ParserError: Empty input (after ) at line 1, column 1 [parse.c:1062] in 'PONG (JSON::ParserError)
  from sidekiq (7.3.2) lib/sidekiq.rb:54:in `parse'
  from sidekiq (7.3.2) lib/sidekiq.rb:54:in `load_json'
  from sidekiq (7.3.2) lib/sidekiq/scheduled.rb:39:in `block (2 levels) in enqueue_jobs'
  from sidekiq (7.3.2) lib/sidekiq/scheduled.rb:33:in `each'
  from sidekiq (7.3.2) lib/sidekiq/scheduled.rb:33:in `block in enqueue_jobs'
  from sidekiq (7.3.2) lib/sidekiq/config.rb:169:in `block in redis'
  from connection_pool (2.4.1) lib/connection_pool.rb:110:in `block (2 levels) in with'
  from connection_pool (2.4.1) lib/connection_pool.rb:109:in `handle_interrupt'
  from connection_pool (2.4.1) lib/connection_pool.rb:109:in `block in with'
  from connection_pool (2.4.1) lib/connection_pool.rb:106:in `handle_interrupt'
  from connection_pool (2.4.1) lib/connection_pool.rb:106:in `with'
  from sidekiq (7.3.2) lib/sidekiq/config.rb:166:in `redis'
  from sidekiq (7.3.2) lib/sidekiq/component.rb:28:in `redis'
  from sidekiq (7.3.2) lib/sidekiq/scheduled.rb:32:in `enqueue_jobs'
  from sidekiq (7.3.2) lib/sidekiq/scheduled.rb:107:in `enqueue'
  from opentelemetry-instrumentation-sidekiq (0.25.7) lib/opentelemetry/instrumentation/sidekiq/patches/poller.rb:19:in `block in enqueue'
  from opentelemetry-common (0.21.0) lib/opentelemetry/common/utilities.rb:99:in `block in untraced'
  from opentelemetry-api (1.4.0) lib/opentelemetry/context.rb:71:in `with_current'
  from opentelemetry-common (0.21.0) lib/opentelemetry/common/utilities.rb:99:in `untraced'
  from opentelemetry-instrumentation-sidekiq (0.25.7) lib/opentelemetry/instrumentation/sidekiq/patches/poller.rb:19:in `enqueue'
  from sidekiq (7.3.2) lib/sidekiq/scheduled.rb:99:in `block in start'
  from sidekiq (7.3.2) lib/sidekiq/component.rb:10:in `watchdog'
  from sidekiq (7.3.2) lib/sidekiq/component.rb:19:in `block in safe_thread'
```

**Comment by mperham** [comment]
You have something scheduling malformed jobs. Are you scheduling jobs manually from another language?

**Comment by StoneGod** [comment]
No, all code on ruby and ror. But we use `gem 'oj'`

**Comment by StoneGod** [comment]
Also use this gem for cron job https://github.com/bibendi/schked

**Comment by StoneGod** [comment]
Error looks like
```
[14] pry(main)> JSON.parse("PONG")
JSON::ParserError: Empty input (after ) at line 1, column 1 [parse.c:1062] in 'PONG
from (pry):8:in `parse'
```

**Comment by mperham** [comment]
I don't know how "PONG" got into your scheduled set but that's not a Sidekiq issue. The bug is elsewhere.

**Comment by mperham** [comment]
Don't use OJ. https://github.com/sidekiq/sidekiq/wiki/Problems-and-Troubleshooting#thread-unsafe-gems-do-not-use
