### ISSUE TITLE
Can't modify frozen hash

### ISSUE THREAD

**Issue by itsmegrave** [sidekiq/sidekiq#6470]
Ruby version: 3.3.5
Rails version: 7.2.1.1
Sidekiq / Pro / Enterprise version(s): 7.3.3

When I run `bundle exec sidekiq` I'm receiving the following error.
I'm upgrading my sidekick from 7.2.4 to 7.3.3. I made a test with 7.3.2 and it works fine.

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

Initializer:
```
REDIS_URL = ENV.fetch("REDIS_URL", "redis://localhost:6379")

class SidekiqMiddleware
  def call(worker, msg, _queue)
    worker.retry_count = msg["retry_count"] if worker.respond_to?(:retry_count)
    yield
  end
end

redis_connect_timeout = ENV.fetch("REDIS_CONNECT_TIMEOUT", 0.2)
redis_read_timeout = ENV.fetch("REDIS_READ_TIMEOUT", 1.0)
redis_write_timeout = ENV.fetch("REDIS_WRITE_TIMEOUT", 0.5)

client_workers = ENV.fetch("SIDEKIQ_CLIENT_WORKERS", 5)
server_workers = ENV.fetch("SIDEKIQ_SERVERS_WORKERS", 25)

Sidekiq.configure_server do |config|
  Sidekiq.strict_args!

  config.on(:startup) do
    Sidekiq.schedule = YAML.load_file(Rails.root.join("config/sidekiq_scheduler.yml"))
    SidekiqScheduler::Scheduler.instance.reload_schedule!
  end

  config.server_middleware do |chain|
    chain.add SidekiqMiddleware
  end

  config.redis = {
    url: REDIS_URL,
    connect_timeout: redis_connect_timeout.to_f,
    read_timeout: redis_read_timeout.to_f,
    write_timeout: redis_write_timeout.to_f,
    size: server_workers.to_f
  }
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: REDIS_URL,
    connect_timeout: redis_connect_timeout.to_f,
    read_timeout: redis_read_timeout.to_f,
    write_timeout: redis_write_timeout.to_f,
    size: client_workers.to_f
  }
end

```
sidekiq.yml
```
# Configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.

:concurrency: <%= ENV.fetch("SIDEKIQ_CLIENT_WORKERS") { 5 } %>
:timeout: 25
:verbose: false
# :pidfile: ./tmp/pids/sidekiq.pid
# :logfile: ./log/sidekiq.log

staging:
  :concurrency: 5
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CLIENT_WORKERS") { 5 } %>
:queues:
  - commissions_default
  - low

```
backtrace
```
can't modify frozen Hash: {:labels=>#<Set: {}>, :require=>".", :environment=>"development", :concurrency=>5, :timeout=>25, :poll_interval_average=>nil, :average_scheduled_poll_interval=>5, :on_complex_arguments=>:raise, :iteration=>{:max_job_runtime=>nil, :retry_backoff=>0}, :error_handlers=>[#<Proc:0x00007f1d94388bd8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/config.rb:43 (lambda)>, #<Proc:0x00007f1d90e28f88 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rollbar-3.6.0/lib/rollbar/plugins/sidekiq.rb:15>], :death_handlers=>[], :lifecycle_events=>{:startup=>[], :quiet=>[#<Proc:0x00007f1d9111bc90 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler.rb:24>], :shutdown=>[], :heartbeat=>[], :beat=>[#<Proc:0x00007f1d8b72ff60 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/metrics/tracking.rb:145>]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Sidekiq::Rails::Reloader @app=PierCommissions::Application>, :backtrace_cleaner=>#<Proc:0x00007f1d906dd4b8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/rails.rb:54 (lambda)>, :verbose=>false, :staging=>{:concurrency=>5}, :production=>{:concurrency=>5}, :queues=>["commissions_default", "low"], :config_file=>"./config/sidekiq.yml", :tag=>"pier-commissions", :identity=>"lnbpier0002:625374:3446d42d6c6d", :schedule_manager=>#<SidekiqScheduler::Manager:0x00007f1dae3adea0 @scheduler_instance=#<SidekiqScheduler::Scheduler:0x00007f1d9036da30 @scheduler_config=#<SidekiqScheduler::Config:0x00007f1dae3ae288 @sidekiq_config=#<Sidekiq::Config:0x00007f1d9257b230 @options={...}, @directory={}, @redis_config={:url=>"redis://redis:6379", :connect_timeout=>0.2, :read_timeout=>1.0, :write_timeout=>0.5, :size=>25.0}, @capsules={"default"=>#<Sidekiq::Capsule:0x00007f1d92577040 @name="default", @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @queues=["commissions_default", "low"], @weights={"commissions_default"=>0, "low"=>0}, @concurrency=5, @mode=:strict, @redis=#<ConnectionPool:0x00007f1d9072abf0 @size=25, @timeout=1, @auto_reload_after_fork=true, @available=#<ConnectionPool::TimedStack:0x00007f1d9072aba0 @create_block=#<Proc:0x00007f1d8b513240 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/redis_connection.rb:34>, @created=0, @que=[], @max=25, @mutex=#<Thread::Mutex:0x00007f1d8b5131f0>, @resource=#<Thread::ConditionVariable:0x00007f1d8b5131c8>, @shutdown_block=nil>, @key=:"pool-20280", @key_count=:"pool-20280-count">, @client_chain=#<Sidekiq::Middleware::Chain:0x00007f1d9226f280 @config=#<Sidekiq::Capsule:0x00007f1d92577040 ...>, @entries=[]>, @server_chain=#<Sidekiq::Middleware::Chain:0x00007f1d9226da48 @config=#<Sidekiq::Capsule:0x00007f1d92577040 ...>, @entries=[#<Sidekiq::Middleware::Entry:0x00007f1d8b72fb28 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @klass=Sidekiq::Metrics::Middleware, @args=[#<Sidekiq::Metrics::ExecutionTracker:0x00007f1d9257b190 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @jobs={}, @totals={}, @grams={}, @lock=#<Thread::Mutex:0x00007f1d8b72f0b0>>]>, #<Sidekiq::Middleware::Entry:0x00007f1d8b6c2b90 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @klass=Sidekiq::Job::InterruptHandler, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f1d90e29320 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @klass=Rollbar::Sidekiq::ResetScope, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f1d90e5daf8 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @klass=SidekiqMiddleware, @args=[]>]>>}, @server_chain=#<Sidekiq::Middleware::Chain:0x00007f1d8b72f150 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @entries=[#<Sidekiq::Middleware::Entry:0x00007f1d8b72fb28 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @klass=Sidekiq::Metrics::Middleware, @args=[#<Sidekiq::Metrics::ExecutionTracker:0x00007f1d9257b190 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @jobs={}, @totals={}, @grams={}, @lock=#<Thread::Mutex:0x00007f1d8b72f0b0>>]>, #<Sidekiq::Middleware::Entry:0x00007f1d8b6c2b90 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @klass=Sidekiq::Job::InterruptHandler, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f1d90e29320 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @klass=Rollbar::Sidekiq::ResetScope, @args=[]>, #<Sidekiq::Middleware::Entry:0x00007f1d90e5daf8 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @klass=SidekiqMiddleware, @args=[]>]>, @logger=#<PierLogging::Logger:0x00007f1d8bc98df8 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007f1d90e5c130 @datetime_format=nil>, @formatter=#<PierLogging::Formatter::Readable:0x00007f1d90c752e0 @app_name="sidekiq", @hostname="lnbpier0002", @trace_indent=2, @trace_max_lines=100, @serialize_backtrace=true, @datetime_format="%FT%T.%3N%:z">, @logdev=#<Logger::LogDevice:0x00007f1d8bc98ad8 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @binmode=false, @reraise_write_errors=[], @mon_data=#<Monitor:0x00007f1d90e5bff0>, @mon_data_owner_object_id=16560>, @level_override={}, @before_log=nil, @default_message="No message", @exc_key=:err, @with_fields={}, @local_level_key=:logger_thread_safe_level_19480>, @redis=#<ConnectionPool:0x00007f1d9071c870 @size=25, @timeout=1, @auto_reload_after_fork=true, @available=#<ConnectionPool::TimedStack:0x00007f1d9071c820 @create_block=#<Proc:0x00007f1d8b51ca48 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/redis_connection.rb:34>, @created=1, @que=[#<Sidekiq::RedisClientAdapter::CompatClient:0x00007f1d8b51c070 @client=#<RedisClient redis://redis:6379>, @_pipeline_class=Sidekiq::RedisClientAdapter::CompatClient::Pipeline>], @max=25, @mutex=#<Thread::Mutex:0x00007f1d8b51c9d0>, @resource=#<Thread::ConditionVariable:0x00007f1d8b51c980>, @shutdown_block=nil>, @key=:"pool-20140", @key_count=:"pool-20140-count">, @client_chain=#<Sidekiq::Middleware::Chain:0x00007f1d9226f2f8 @config=#<Sidekiq::Config:0x00007f1d9257b230 ...>, @entries=[]>>, @scheduler_config={:enabled=>true, :dynamic=>false, :dynamic_every=>"5s", :schedule=>{}, :rufus_scheduler_options=>{}}>, @enabled=true, @dynamic=false, @dynamic_every="5s", @listened_queues_only=nil, @rufus_scheduler_options={}, @scheduled_jobs={"create_gross_commissions_for_intermediary"=>#<Rufus::Scheduler::CronJob:0x00007f1d90d162d0 @scheduler=#<Rufus::Scheduler:0x00007f1d9077c4f0 @opts={}, @started_at=#<EtOrbi::EoTime:0x00007f1d94d24520 @seconds=1729709692.9453595, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @paused_at=nil, @jobs=#<Rufus::Scheduler::JobArray:0x00007f1d94d24cf0 @mutex=#<Thread::Mutex:0x00007f1d94d24c50>, @array=[#<Rufus::Scheduler::CronJob:0x00007f1d90d162d0 ...>, #<Rufus::Scheduler::CronJob:0x00007f1d90d153d0 @scheduler=#<Rufus::Scheduler:0x00007f1d9077c4f0 ...>, @original="00 04 * * 1", @opts={:job=>true, :tags=>["create_payment_file"]}, @handler=#<Proc:0x00007f1d9254ce58 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @callable=#<Proc:0x00007f1d9254ce58 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @scheduled_at=#<EtOrbi::EoTime:0x00007f1d92d2b138 @seconds=1729709692.9492662, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @unscheduled_at=nil, @last_time=nil, @discard_past=nil, @locals={}, @local_mutex=#<Thread::Mutex:0x00007f1d9254ce08>, @id="cron_1729709692.9492662_22080", @name=nil, @tags=["create_payment_file"], @count=0, @last_work_time=0.0, @mean_work_time=0.0, @paused_at=nil, @times=nil, @first_at_no_error=false, @first_at=nil, @last_at=nil, @resume_discard_past=nil, @cron_line=#<Fugit::Cron:0x00007f1d9076fd40 @original="00 04 * * 1", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[0], @hours=[4], @monthdays=nil, @months=nil, @weekdays=[[1]], @zone=nil, @timezone=nil>, @next_time=#<EtOrbi::EoTime:0x00007f1d92d21548 @seconds=1730098800.0, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=2024-10-28 04:00:00 -0300, @rday=nil, @rweek=nil>>]>, @frequency=0.3, @discard_past=true, @mutexes={}, @work_queue=#<Thread::Queue:0x00007f1d94d24980>, @join_queue=#<Thread::Queue:0x00007f1d94d248e0>, @max_work_threads=28, @stderr=#<IO:<STDERR>>, @thread_key="rufus_scheduler_21660", @scheduler_lock=#<Rufus::Scheduler::NullLock:0x00007f1d94d247a0>, @trigger_lock=#<Rufus::Scheduler::NullLock:0x00007f1d94d24728>, @thread=#<Thread:0x00007f1d94d240e8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rufus-scheduler-3.9.2/lib/rufus/scheduler.rb:634 sleep>>, @original="30 00 * * 1", @opts={:job=>true, :tags=>["create_gross_commissions_for_intermediary"]}, @handler=#<Proc:0x00007f1d9426faf8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @callable=#<Proc:0x00007f1d9426faf8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @scheduled_at=#<EtOrbi::EoTime:0x00007f1d943aae18 @seconds=1729709692.9463794, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @unscheduled_at=nil, @last_time=nil, @discard_past=nil, @locals={}, @local_mutex=#<Thread::Mutex:0x00007f1d9426f918>, @id="cron_1729709692.9463794_21940", @name=nil, @tags=["create_gross_commissions_for_intermediary"], @count=0, @last_work_time=0.0, @mean_work_time=0.0, @paused_at=nil, @times=nil, @first_at_no_error=false, @first_at=nil, @last_at=nil, @resume_discard_past=nil, @cron_line=#<Fugit::Cron:0x00007f1d942662f0 @original="30 00 * * 1", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[30], @hours=[0], @monthdays=nil, @months=nil, @weekdays=[[1]], @zone=nil, @timezone=nil>, @next_time=#<EtOrbi::EoTime:0x00007f1d92d2d9d8 @seconds=1730086200.0, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=2024-10-28 00:30:00 -0300, @rday=nil, @rweek=nil>>, "create_payment_file"=>#<Rufus::Scheduler::CronJob:0x00007f1d90d153d0 @scheduler=#<Rufus::Scheduler:0x00007f1d9077c4f0 @opts={}, @started_at=#<EtOrbi::EoTime:0x00007f1d94d24520 @seconds=1729709692.9453595, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @paused_at=nil, @jobs=#<Rufus::Scheduler::JobArray:0x00007f1d94d24cf0 @mutex=#<Thread::Mutex:0x00007f1d94d24c50>, @array=[#<Rufus::Scheduler::CronJob:0x00007f1d90d162d0 @scheduler=#<Rufus::Scheduler:0x00007f1d9077c4f0 ...>, @original="30 00 * * 1", @opts={:job=>true, :tags=>["create_gross_commissions_for_intermediary"]}, @handler=#<Proc:0x00007f1d9426faf8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @callable=#<Proc:0x00007f1d9426faf8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @scheduled_at=#<EtOrbi::EoTime:0x00007f1d943aae18 @seconds=1729709692.9463794, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @unscheduled_at=nil, @last_time=nil, @discard_past=nil, @locals={}, @local_mutex=#<Thread::Mutex:0x00007f1d9426f918>, @id="cron_1729709692.9463794_21940", @name=nil, @tags=["create_gross_commissions_for_intermediary"], @count=0, @last_work_time=0.0, @mean_work_time=0.0, @paused_at=nil, @times=nil, @first_at_no_error=false, @first_at=nil, @last_at=nil, @resume_discard_past=nil, @cron_line=#<Fugit::Cron:0x00007f1d942662f0 @original="30 00 * * 1", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[30], @hours=[0], @monthdays=nil, @months=nil, @weekdays=[[1]], @zone=nil, @timezone=nil>, @next_time=#<EtOrbi::EoTime:0x00007f1d92d2d9d8 @seconds=1730086200.0, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=2024-10-28 00:30:00 -0300, @rday=nil, @rweek=nil>>, #<Rufus::Scheduler::CronJob:0x00007f1d90d153d0 ...>]>, @frequency=0.3, @discard_past=true, @mutexes={}, @work_queue=#<Thread::Queue:0x00007f1d94d24980>, @join_queue=#<Thread::Queue:0x00007f1d94d248e0>, @max_work_threads=28, @stderr=#<IO:<STDERR>>, @thread_key="rufus_scheduler_21660", @scheduler_lock=#<Rufus::Scheduler::NullLock:0x00007f1d94d247a0>, @trigger_lock=#<Rufus::Scheduler::NullLock:0x00007f1d94d24728>, @thread=#<Thread:0x00007f1d94d240e8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rufus-scheduler-3.9.2/lib/rufus/scheduler.rb:634 sleep>>, @original="00 04 * * 1", @opts={:job=>true, :tags=>["create_payment_file"]}, @handler=#<Proc:0x00007f1d9254ce58 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @callable=#<Proc:0x00007f1d9254ce58 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @scheduled_at=#<EtOrbi::EoTime:0x00007f1d92d2b138 @seconds=1729709692.9492662, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @unscheduled_at=nil, @last_time=nil, @discard_past=nil, @locals={}, @local_mutex=#<Thread::Mutex:0x00007f1d9254ce08>, @id="cron_1729709692.9492662_22080", @name=nil, @tags=["create_payment_file"], @count=0, @last_work_time=0.0, @mean_work_time=0.0, @paused_at=nil, @times=nil, @first_at_no_error=false, @first_at=nil, @last_at=nil, @resume_discard_past=nil, @cron_line=#<Fugit::Cron:0x00007f1d9076fd40 @original="00 04 * * 1", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[0], @hours=[4], @monthdays=nil, @months=nil, @weekdays=[[1]], @zone=nil, @timezone=nil>, @next_time=#<EtOrbi::EoTime:0x00007f1d92d21548 @seconds=1730098800.0, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=2024-10-28 04:00:00 -0300, @rday=nil, @rweek=nil>>}, @rufus_scheduler=#<Rufus::Scheduler:0x00007f1d9077c4f0 @opts={}, @started_at=#<EtOrbi::EoTime:0x00007f1d94d24520 @seconds=1729709692.9453595, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @paused_at=nil, @jobs=#<Rufus::Scheduler::JobArray:0x00007f1d94d24cf0 @mutex=#<Thread::Mutex:0x00007f1d94d24c50>, @array=[#<Rufus::Scheduler::CronJob:0x00007f1d90d162d0 @scheduler=#<Rufus::Scheduler:0x00007f1d9077c4f0 ...>, @original="30 00 * * 1", @opts={:job=>true, :tags=>["create_gross_commissions_for_intermediary"]}, @handler=#<Proc:0x00007f1d9426faf8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @callable=#<Proc:0x00007f1d9426faf8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @scheduled_at=#<EtOrbi::EoTime:0x00007f1d943aae18 @seconds=1729709692.9463794, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @unscheduled_at=nil, @last_time=nil, @discard_past=nil, @locals={}, @local_mutex=#<Thread::Mutex:0x00007f1d9426f918>, @id="cron_1729709692.9463794_21940", @name=nil, @tags=["create_gross_commissions_for_intermediary"], @count=0, @last_work_time=0.0, @mean_work_time=0.0, @paused_at=nil, @times=nil, @first_at_no_error=false, @first_at=nil, @last_at=nil, @resume_discard_past=nil, @cron_line=#<Fugit::Cron:0x00007f1d942662f0 @original="30 00 * * 1", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[30], @hours=[0], @monthdays=nil, @months=nil, @weekdays=[[1]], @zone=nil, @timezone=nil>, @next_time=#<EtOrbi::EoTime:0x00007f1d92d2d9d8 @seconds=1730086200.0, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=2024-10-28 00:30:00 -0300, @rday=nil, @rweek=nil>>, #<Rufus::Scheduler::CronJob:0x00007f1d90d153d0 @scheduler=#<Rufus::Scheduler:0x00007f1d9077c4f0 ...>, @original="00 04 * * 1", @opts={:job=>true, :tags=>["create_payment_file"]}, @handler=#<Proc:0x00007f1d9254ce58 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @callable=#<Proc:0x00007f1d9254ce58 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-scheduler-5.0.6/lib/sidekiq-scheduler/scheduler.rb:266>, @scheduled_at=#<EtOrbi::EoTime:0x00007f1d92d2b138 @seconds=1729709692.9492662, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=nil, @rday=nil, @rweek=nil>, @unscheduled_at=nil, @last_time=nil, @discard_past=nil, @locals={}, @local_mutex=#<Thread::Mutex:0x00007f1d9254ce08>, @id="cron_1729709692.9492662_22080", @name=nil, @tags=["create_payment_file"], @count=0, @last_work_time=0.0, @mean_work_time=0.0, @paused_at=nil, @times=nil, @first_at_no_error=false, @first_at=nil, @last_at=nil, @resume_discard_past=nil, @cron_line=#<Fugit::Cron:0x00007f1d9076fd40 @original="00 04 * * 1", @cron_s=nil, @day_and=nil, @seconds=[0], @minutes=[0], @hours=[4], @monthdays=nil, @months=nil, @weekdays=[[1]], @zone=nil, @timezone=nil>, @next_time=#<EtOrbi::EoTime:0x00007f1d92d21548 @seconds=1730098800.0, @zone=#<TZInfo::DataTimezone: America/Sao_Paulo>, @time=2024-10-28 04:00:00 -0300, @rday=nil, @rweek=nil>>]>, @frequency=0.3, @discard_past=true, @mutexes={}, @work_queue=#<Thread::Queue:0x00007f1d94d24980>, @join_queue=#<Thread::Queue:0x00007f1d94d248e0>, @max_work_threads=28, @stderr=#<IO:<STDERR>>, @thread_key="rufus_scheduler_21660", @scheduler_lock=#<Rufus::Scheduler::NullLock:0x00007f1d94d247a0>, @trigger_lock=#<Rufus::Scheduler::NullLock:0x00007f1d94d24728>, @thread=#<Thread:0x00007f1d94d240e8 /home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rufus-scheduler-3.9.2/lib/rufus/scheduler.rb:634 sleep>>>>}
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/forwardable.rb:240:in `merge!'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/forwardable.rb:240:in `merge!'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/launcher.rb:40:in `block in run'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/ougai-2.0.0/lib/ougai/logging.rb:103:in `_log'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/pier_logging-0.4.3/lib/pier_logging/logger.rb:18:in `_log'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/ougai-2.0.0/lib/ougai/logging.rb:42:in `debug'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/launcher.rb:40:in `run'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/cli.rb:124:in `launch'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/lib/sidekiq/cli.rb:113:in `run'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.3/bin/sidekiq:31:in `<top (required)>'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/bin/sidekiq:25:in `load'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/bin/sidekiq:25:in `<top (required)>'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/bin/bundle:25:in `load'
/home/samuelgrave/.asdf/installs/ruby/3.3.5/bin/bundle:25:in `<main>'
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
Looks like ougai or pier_logging is doing some sketchy monkeypatching.

**Comment by itsmegrave** [comment]
thanks for the keen eye @mperham 
Looking at pier-logging and oukai, the only thing we did is to redact some sensible data 🤔  and format the hash to a structured object.
it should blow as it is not a global configuration 🤔

**Comment by mironov** [comment]
Not sure if the same thing or not, but adding:
```ruby
config.logger = Sidekiq::Logger.new($stdout)
```

breaks Sidekiq for us with the same error about frozen hash.

**Comment by mperham** [comment]
@mironov Where are you running that code? Initializer?

**Comment by mironov** [comment]
@mperham Yes, full initializer code below:

```ruby
# frozen_string_literal: true

require "sidekiq/middleware/current_attributes"

redis_configuration = {
  network_timeout: 15,
  username: ENV["REDIS_SERVICE_USERNAME"],
  password: ENV["REDIS_SERVICE_PASSWORD"],
  host: ENV["REDIS_SERVICE_HOST"],
  port: ENV["REDIS_SERVICE_PORT"],
  ssl: ActiveModel::Type::Boolean.new.cast(ENV["REDIS_SERVICE_SSL"]),
  db: ENV["REDIS_SERVICE_DATABASE"],
}

Sidekiq.configure_server do |config|
  config.redis = redis_configuration
  config.logger = Sidekiq::Logger.new($stdout)
end

Sidekiq.configure_client { |config| config.redis = redis_configuration }

Sidekiq::CurrentAttributes.persist("Current")
```

**Comment by mperham** [comment]
Ah, really dumb mistake on my part. 7.3.4 coming very soon.

**Comment by mperham** [comment]
7.3.4 is out, thank you for the reports.
