### ISSUE TITLE
`Errno::EALREADY` errors when Redis restarts

### ISSUE THREAD

**Issue by brucebolt** [sidekiq/sidekiq#6479]
Ruby version: 3.3.1
Rails version: 7.2.1.2
Sidekiq / Pro / Enterprise version(s): 7.3.2

Initalizer: https://github.com/alphagov/govuk_sidekiq/blob/main/lib/govuk_sidekiq/sidekiq_initializer.rb
Sidekiq.yml: https://github.com/alphagov/support-api/blob/main/config/sidekiq.yml

We are seeing `IO::EINPROGRESSWaitWritable` and `Errno::EALREADY` errors logged whilst Redis is restarting.  We have Redis `reconnect_attempts` configured  to `[15, 30, 45, 60]` which exceed the duration of the restart.

I'd expect to be seeing a different error, e.g. something about not being able to connect, rather than this error which suggests multiple attempts are being made to access Redis at the same time.

I'm unable to work out whether the error is caused by the connection pools in Sidekiq or something further down the line (e.g. in redis-client).

Error message:

```
IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
  from socket.rb:1217:in `__connect_nonblock'
  from socket.rb:1217:in `connect_nonblock'
  from redis (4.8.1) lib/redis/connection/ruby.rb:158:in `connect_addrinfo'
  from redis (4.8.1) lib/redis/connection/ruby.rb:196:in `block in connect'
  from redis (4.8.1) lib/redis/connection/ruby.rb:194:in `each'
  from redis (4.8.1) lib/redis/connection/ruby.rb:194:in `each_with_index'
  from redis (4.8.1) lib/redis/connection/ruby.rb:194:in `connect'
  from redis (4.8.1) lib/redis/connection/ruby.rb:308:in `connect'
  from redis (4.8.1) lib/redis/client.rb:385:in `establish_connection'
  from redis (4.8.1) lib/redis/client.rb:115:in `block in connect'
  from redis (4.8.1) lib/redis/client.rb:344:in `with_reconnect'
  from redis (4.8.1) lib/redis/client.rb:114:in `connect'
  from redis (4.8.1) lib/redis/client.rb:409:in `ensure_connected'
  from redis (4.8.1) lib/redis/client.rb:269:in `block in process'
  from redis (4.8.1) lib/redis/client.rb:356:in `logging'
  from sentry-ruby (5.21.0) lib/sentry/redis.rb:81:in `block in logging'
  from sentry-ruby (5.21.0) lib/sentry/redis.rb:18:in `block in instrument'
  from sentry-ruby (5.21.0) lib/sentry/hub.rb:108:in `with_child_span'
  from sentry-ruby (5.21.0) lib/sentry-ruby.rb:499:in `with_child_span'
  from sentry-ruby (5.21.0) lib/sentry/redis.rb:17:in `instrument'
  from sentry-ruby (5.21.0) lib/sentry/redis.rb:81:in `logging'
  from redis (4.8.1) lib/redis/client.rb:268:in `process'
  from opentelemetry-instrumentation-redis (0.25.7) lib/opentelemetry/instrumentation/redis/patches/redis_v4_client.rb:46:in `block in process'
  from opentelemetry-api (1.4.0) lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
  from opentelemetry-api (1.4.0) lib/opentelemetry/trace.rb:70:in `block in with_span'
  from opentelemetry-api (1.4.0) lib/opentelemetry/context.rb:87:in `with_value'
  from opentelemetry-api (1.4.0) lib/opentelemetry/trace.rb:70:in `with_span'
  from opentelemetry-api (1.4.0) lib/opentelemetry/trace/tracer.rb:37:in `in_span'
  from opentelemetry-instrumentation-redis (0.25.7) lib/opentelemetry/instrumentation/redis/patches/redis_v4_client.rb:45:in `process'
  from redis (4.8.1) lib/redis/client.rb:161:in `call'
  from prometheus_exporter (2.1.1) lib/prometheus_exporter/instrumentation/method_profiler.rb:49:in `call'
  from redis (4.8.1) lib/redis.rb:270:in `block in send_command'
  from redis (4.8.1) lib/redis.rb:269:in `synchronize'
  from redis (4.8.1) lib/redis.rb:269:in `send_command'
  from redis (4.8.1) lib/redis/commands/server.rb:90:in `info'
  from sidekiq (6.5.12) lib/sidekiq.rb:186:in `block in redis_info'
  from sidekiq (6.5.12) lib/sidekiq.rb:164:in `block in redis'
  from connection_pool (2.4.1) lib/connection_pool.rb:110:in `block (2 levels) in with'
  from connection_pool (2.4.1) lib/connection_pool.rb:109:in `handle_interrupt'
  from connection_pool (2.4.1) lib/connection_pool.rb:109:in `block in with'
  from connection_pool (2.4.1) lib/connection_pool.rb:106:in `handle_interrupt'
  from connection_pool (2.4.1) lib/connection_pool.rb:106:in `with'
  from sidekiq (6.5.12) lib/sidekiq.rb:161:in `redis'
  from sidekiq (6.5.12) lib/sidekiq.rb:182:in `redis_info'
  from sidekiq (6.5.12) lib/sidekiq/cli.rb:86:in `run'
  from sidekiq (6.5.12) bin/sidekiq:31:in `<top (required)>'
  from /usr/local/bundle/bin/sidekiq:27:in `load'
  from /usr/local/bundle/bin/sidekiq:27:in `<main>'

Errno::EALREADY: Operation already in progress - connect(2) for 172.20.22.70:6379 (Errno::EALREADY)
  from socket.rb:1217:in `__connect_nonblock'
  from socket.rb:1217:in `connect_nonblock'
  from redis (4.8.1) lib/redis/connection/ruby.rb:163:in `rescue in connect_addrinfo'
  from redis (4.8.1) lib/redis/connection/ruby.rb:157:in `connect_addrinfo'
  from redis (4.8.1) lib/redis/connection/ruby.rb:196:in `block in connect'
  from redis (4.8.1) lib/redis/connection/ruby.rb:194:in `each'
  from redis (4.8.1) lib/redis/connection/ruby.rb:194:in `each_with_index'
  from redis (4.8.1) lib/redis/connection/ruby.rb:194:in `connect'
  from redis (4.8.1) lib/redis/connection/ruby.rb:308:in `connect'
  from redis (4.8.1) lib/redis/client.rb:385:in `establish_connection'
  from redis (4.8.1) lib/redis/client.rb:115:in `block in connect'
  from redis (4.8.1) lib/redis/client.rb:344:in `with_reconnect'
  from redis (4.8.1) lib/redis/client.rb:114:in `connect'
  from redis (4.8.1) lib/redis/client.rb:409:in `ensure_connected'
  from redis (4.8.1) lib/redis/client.rb:269:in `block in process'
  from redis (4.8.1) lib/redis/client.rb:356:in `logging'
  from sentry-ruby (5.21.0) lib/sentry/redis.rb:81:in `block in logging'
  from sentry-ruby (5.21.0) lib/sentry/redis.rb:18:in `block in instrument'
  from sentry-ruby (5.21.0) lib/sentry/hub.rb:108:in `with_child_span'
  from sentry-ruby (5.21.0) lib/sentry-ruby.rb:499:in `with_child_span'
  from sentry-ruby (5.21.0) lib/sentry/redis.rb:17:in `instrument'
  from sentry-ruby (5.21.0) lib/sentry/redis.rb:81:in `logging'
  from redis (4.8.1) lib/redis/client.rb:268:in `process'
  from opentelemetry-instrumentation-redis (0.25.7) lib/opentelemetry/instrumentation/redis/patches/redis_v4_client.rb:46:in `block in process'
  from opentelemetry-api (1.4.0) lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
  from opentelemetry-api (1.4.0) lib/opentelemetry/trace.rb:70:in `block in with_span'
  from opentelemetry-api (1.4.0) lib/opentelemetry/context.rb:87:in `with_value'
  from opentelemetry-api (1.4.0) lib/opentelemetry/trace.rb:70:in `with_span'
  from opentelemetry-api (1.4.0) lib/opentelemetry/trace/tracer.rb:37:in `in_span'
  from opentelemetry-instrumentation-redis (0.25.7) lib/opentelemetry/instrumentation/redis/patches/redis_v4_client.rb:45:in `process'
  from redis (4.8.1) lib/redis/client.rb:161:in `call'
  from prometheus_exporter (2.1.1) lib/prometheus_exporter/instrumentation/method_profiler.rb:49:in `call'
  from redis (4.8.1) lib/redis.rb:270:in `block in send_command'
  from redis (4.8.1) lib/redis.rb:269:in `synchronize'
  from redis (4.8.1) lib/redis.rb:269:in `send_command'
  from redis (4.8.1) lib/redis/commands/server.rb:90:in `info'
  from sidekiq (6.5.12) lib/sidekiq.rb:186:in `block in redis_info'
  from sidekiq (6.5.12) lib/sidekiq.rb:164:in `block in redis'
  from connection_pool (2.4.1) lib/connection_pool.rb:110:in `block (2 levels) in with'
  from connection_pool (2.4.1) lib/connection_pool.rb:109:in `handle_interrupt'
  from connection_pool (2.4.1) lib/connection_pool.rb:109:in `block in with'
  from connection_pool (2.4.1) lib/connection_pool.rb:106:in `handle_interrupt'
  from connection_pool (2.4.1) lib/connection_pool.rb:106:in `with'
  from sidekiq (6.5.12) lib/sidekiq.rb:161:in `redis'
  from sidekiq (6.5.12) lib/sidekiq.rb:182:in `redis_info'
  from sidekiq (6.5.12) lib/sidekiq/cli.rb:86:in `run'
  from sidekiq (6.5.12) bin/sidekiq:31:in `<top (required)>'
  from /usr/local/bundle/bin/sidekiq:27:in `load'
  from /usr/local/bundle/bin/sidekiq:27:in `<main>'
```

**Comment by mperham** [comment]
How are you using a namespaced Redis connection for fetching? That shouldn't be possible in Sidekiq 7.

```
  from redis/commands/lists.rb:167:in `brpop'
  from redis/namespace.rb:564:in `wrapped_send'
  from redis/namespace.rb:521:in `call_with_namespace'
  from redis/namespace.rb:395:in `block (2 levels) in <class:Namespace>'
  from sidekiq/fetch.rb:49:in `block in retrieve_work'
  from sidekiq.rb:164:in `block in redis'
```

**Comment by brucebolt** [comment]
Thanks @mperham.  I just noticed the error occurred prior to us upgrading to Sidekiq 7 and removing the namespaces.

In the other apps where we see this error, we haven't yet upgraded to Sidekiq 7.

So I think I can say this is resolved, as we haven't seen this in apps that are upgraded to Sidekiq 7.
