### ISSUE TITLE
Web sidekiq breaks when filtering on Dead queue

### ISSUE THREAD

**Issue by fmichaut-diff** [sidekiq/sidekiq#6536]
Ruby version: 3.3.0
Rails version: 7.2.2
Sidekiq / Pro / Enterprise version(s): Sidekiq v7.3.6 / Pro v7.3.3

Here's the backtrace :

```
Routing Error, No route matches [GET] "/sidekiq/dead"

[Application Trace](http://localhost:3000/sidekiq/dead?substr=aa#) | [Framework Trace](http://localhost:3000/sidekiq/dead?substr=aa#) | [Full Trace](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:35:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[sentry-ruby (5.21.0) lib/sentry/rack/capture_exceptions.rb:30:in `block (2 levels) in call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[sentry-ruby (5.21.0) lib/sentry/hub.rb:262:in `with_session_tracking'](http://localhost:3000/sidekiq/dead?substr=aa#)
[sentry-ruby (5.21.0) lib/sentry-ruby.rb:412:in `with_session_tracking'](http://localhost:3000/sidekiq/dead?substr=aa#)
[sentry-ruby (5.21.0) lib/sentry/rack/capture_exceptions.rb:21:in `block in call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[sentry-ruby (5.21.0) lib/sentry/hub.rb:59:in `with_scope'](http://localhost:3000/sidekiq/dead?substr=aa#)
[sentry-ruby (5.21.0) lib/sentry-ruby.rb:392:in `with_scope'](http://localhost:3000/sidekiq/dead?substr=aa#)
[sentry-ruby (5.21.0) lib/sentry/rack/capture_exceptions.rb:20:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[lograge (0.14.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'](http://localhost:3000/sidekiq/dead?substr=aa#)
[railties (7.2.2) lib/rails/rack/logger.rb:29:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/remote_ip.rb:96:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/request_id.rb:33:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[rack (2.2.8.1) lib/rack/method_override.rb:24:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[shopify_app (22.2.1) lib/shopify_app/middleware/jwt_middleware.rb:25:in `call_next'](http://localhost:3000/sidekiq/dead?substr=aa#)
[shopify_app (22.2.1) lib/shopify_app/middleware/jwt_middleware.rb:13:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[rack (2.2.8.1) lib/rack/runtime.rb:22:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[activesupport (7.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/server_timing.rb:60:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/executor.rb:16:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/static.rb:27:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[rack (2.2.8.1) lib/rack/sendfile.rb:110:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[actionpack (7.2.2) lib/action_dispatch/middleware/host_authorization.rb:143:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[ddtrace (1.18.0) lib/datadog/tracing/contrib/rack/middlewares.rb:102:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[railties (7.2.2) lib/rails/engine.rb:535:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[puma (5.6.9) lib/puma/configuration.rb:252:in `call'](http://localhost:3000/sidekiq/dead?substr=aa#)
[puma (5.6.9) lib/puma/request.rb:77:in `block in handle_request'](http://localhost:3000/sidekiq/dead?substr=aa#)
[puma (5.6.9) lib/puma/thread_pool.rb:340:in `with_force_shutdown'](http://localhost:3000/sidekiq/dead?substr=aa#)
[puma (5.6.9) lib/puma/request.rb:76:in `handle_request'](http://localhost:3000/sidekiq/dead?substr=aa#)
[puma (5.6.9) lib/puma/server.rb:443:in `process_client'](http://localhost:3000/sidekiq/dead?substr=aa#)
[puma (5.6.9) lib/puma/thread_pool.rb:147:in `block in spawn_thread'](http://localhost:3000/sidekiq/dead?substr=aa#)
```

This does not occur in Scheduled filter
Looks like for some reason the UI form submits to `sidekiq/dead?substr=your_search_here` and that path does not exists.

**Comment by mperham** [comment]
Dupe, already fixed on main, waiting on a release

**Comment by fmichaut-diff** [comment]
When would the release be ?

**Comment by mperham** [comment]
I don't give specific release dates, "soon".
