### ISSUE TITLE
Periodic subsystem skipping ticks

### ISSUE THREAD

**Issue by calvincchen** [sidekiq/sidekiq#6560]
Ruby version: 3.3.5
Rails version: 7.2.2.1
Sidekiq / Pro / Enterprise version(s): 7.3.7 / 7.3.4 / 7.3.4

### Summary
We upgraded from Sidekiq 7.1.6 to 7.3.7 earlier this week and have noticed more logs for `"Periodic subsystem skipped tick"`. This seems to spike unpredictability throughout the day, and has led to us missing a number of periodic jobs.

<img width="1341" alt="image" src="https://github.com/user-attachments/assets/b3852637-4fd4-4a9f-b2d3-10aa4c615c8f" />

### Configuration
We're running Sidekiq Swarm with 5 processes x 1 concurrency per box.

Sidekiq Redis configuration
```rb
Sidekiq.configure_server do |config|
  config.redis = {
    url: my_url,
    timeout: 3,
    size: 10,
  }
end
```

Server initialization logs
```
#internal
Sidekiq 7.3.7 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>my_url, :timeout=>3}

#default
Sidekiq 7.3.7 connecting to Redis with options {:size=>10, :pool_name=>"default", :url=>my_url, :timeout=>3}
```

### Additional Context
The `"Periodic subsystem skipped tick"` occurrence appears to correlate with warnings of `ConnectionPool::TimeoutError: Waited 5 sec, 0/1 available`

Stacktrace
```
/usr/local/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool/timed_stack.rb:77:in `block (2 levels) in pop'
<internal:kernel>:187:in `loop'
/usr/local/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool/timed_stack.rb:69:in `block in pop'
/usr/local/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool/timed_stack.rb:68:in `synchronize'
/usr/local/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool/timed_stack.rb:68:in `pop'
/usr/local/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:125:in `checkout'
/usr/local/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:107:in `block in with'
/usr/local/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
/usr/local/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-pro-7.3.4/lib/sidekiq/pro/metrics.rb:129:in `batch'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-gusto-12.3.4/lib/sidekiq-gusto/stats/client_middleware.rb:31:in `call'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-pro-7.3.4/lib/sidekiq/pro/expiry.rb:24:in `call'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/contrib/sidekiq/client_tracer.rb:49:in `block in call'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/trace_operation.rb:226:in `block in measure'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/span_operation.rb:150:in `measure'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/trace_operation.rb:226:in `measure'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/tracer.rb:403:in `start_span'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/tracer.rb:158:in `block in trace'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/context.rb:45:in `activate!'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/tracer.rb:157:in `trace'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing.rb:30:in `trace'
/usr/local/bundle/ruby/3.3.0/gems/datadog-2.7.1/lib/datadog/tracing/contrib/sidekiq/client_tracer.rb:26:in `call'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-pro-7.3.4/lib/sidekiq/batch/middleware.rb:18:in `call'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-ent-7.3.4/lib/sidekiq-ent/unique.rb:163:in `call'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/middleware/chain.rb:173:in `invoke'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/client.rb:105:in `push'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/transaction_aware_client.rb:23:in `block in push'
/usr/local/bundle/ruby/3.3.0/gems/after_commit_everywhere-1.5.0/lib/after_commit_everywhere.rb:117:in `register_callback'
/usr/local/bundle/ruby/3.3.0/gems/after_commit_everywhere-1.5.0/lib/after_commit_everywhere.rb:47:in `after_commit'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/transaction_aware_client.rb:23:in `push'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/job.rb:372:in `client_push'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/job.rb:209:in `perform_async'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-ent-7.3.4/lib/sidekiq-ent/periodic/manager.rb:173:in `enqueue_job'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-ent-7.3.4/lib/sidekiq-ent/periodic/manager.rb:126:in `process'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-ent-7.3.4/lib/sidekiq-ent/periodic/manager.rb:79:in `block in cycle'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/rails.rb:16:in `block in call'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-c5c170501e81/activesupport/lib/active_support/reloader.rb:77:in `block in wrap'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-c5c170501e81/activesupport/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-c5c170501e81/activesupport/lib/active_support/reloader.rb:74:in `wrap'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/rails.rb:15:in `call'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-ent-7.3.4/lib/sidekiq-ent/periodic/manager.rb:78:in `cycle'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/component.rb:10:in `watchdog'
/usr/local/bundle/ruby/3.3.0/gems/sidekiq-7.3.7/lib/sidekiq/component.rb:19:in `block in safe_thread'
```

I came across a couple similar threads (https://github.com/sidekiq/sidekiq/issues/5685, https://github.com/sidekiq/sidekiq/issues/5684, https://github.com/sidekiq/sidekiq/issues/5752, https://github.com/sidekiq/sidekiq/issues/5702) but wasn't able to resolve this issue. Any advice or suggestions would be greatly appreciated!

### Additional Questions
1. Where is the `1` from `ConnectionPool::TimeoutError: Waited 5 sec, 0/1 available` come from? Is this the capsule concurrency? Is there a configuration to increase the pool size without increasing the capsule concurrency of the process?
2. We have a thread of our own that makes calls to redis using `Sidekiq.redis` for stats reporting, could this be exacerbating the issue?

Thank you and please let me know if there's additional context I can provide!

**Comment by mperham** [comment]
Yes, if that thread holds the connection for a while, it can starve other parts of Sidekiq of connections. Can you share the code? In general, don't hold the connection while yielding a (potentially) long-running block.

**Comment by mperham** [comment]
That said, because the periodic manager is not associated with any one capsule, it should use the internal connection pool which allows up to (I think) 10 connections. Odd, maybe there is a bug.

**Comment by calvincchen** [comment]
We're trying to collect stats on the queue and morgue sizes. 
```rb 
def collect_stats
   queues = Sidekiq::Queue.all
   dead_set = Sidekiq::DeadSet.new.each
   collect_queue_stats(queues)
   collect_morgue_stats(queues)
end

def collect_queue_stats(queues)
   queues.map do |queue|
      { size: queue.size, latency: queue.latency, name: queue.name }
   end
end

def collect_morgue_stats(queues)
    morgue_sizes_by_queue = queues.map { |queue| [queue.name, 0] }.to_h
    Sidekiq::DeadSet.new.each do |job|
      morgue_sizes_by_queue[job.queue] = morgue_sizes_by_queue.fetch(job.queue, 0) + 1
    end
end
```

**Comment by mperham** [comment]
Use Enterprise's historical metrics as much as possible. It's optimized and can handle the items in `collect_queue_stats` I think.

`collect_morgue_stats` is going to run extremely slow, it's a bad idea to iterate through the entire thing every N seconds. What if your dead set is many thousands of items? I would collect this outside of Sidekiq and maybe every few minutes at most.

**Comment by ngan** [comment]
We use Sidekiq Swarm with `SIDEKIQ_COUNT=5` and `--concurrency 1`. So each sidekiq process only has 1 worker thread. This is the only place where I can imagine `1` is coming from:
https://github.com/sidekiq/sidekiq/blob/591adc6fcf13fd93c72df9cf8d65d2425c1ff398/lib/sidekiq/capsule.rb#L96-L100

My guess is that somehow, the periodic manager eventually swaps over to using this pool instead of the `internal` pool.

**Comment by mperham** [comment]
Your stack trace implies that the starved connection pool is actually Pro's metrics pool of datadog connections. It looks like you are calling `batch` in `sidekiq-gusto-12.3.4/lib/sidekiq-gusto/stats/client_middleware.rb:31`. Make sure you aren't holding a datadog connection while yielding.

Wrong:

```ruby
metrics.batch do |m|
  c = yield
  m.count("some.count", c)
end
```

Right:

```ruby
c = yield
metrics.batch do |m|
  m.count("some.count", c)
end
```

**Comment by mperham** [comment]
It's an easy mistake to make, see second item here:

https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md#734

Oops!

**Comment by calvincchen** [comment]
This is the relevant client_middleware code:
```rb
```

**Comment by mperham** [comment]
I think this could be an issue in Pro:

```diff
--- a/lib/sidekiq/pro/metrics.rb
+++ b/lib/sidekiq/pro/metrics.rb
@@ -66,7 +66,7 @@ module Sidekiq
         def initialize(config, statsd)
           @config = config
           @statsd = if statsd.is_a?(::Proc)
-            ::ConnectionPool.new(size: config[:concurrency], &statsd)
+            ::ConnectionPool.new(size: config.total_concurrency + 2, &statsd)
 ```

If you're running `concurrency: 1`, other threads can contend for metrics connections.

**Comment by mperham** [comment]
You might monkeypatch that and see if it helps.

**Comment by calvincchen** [comment]
Giving it a shot, will update. Thanks!

**Comment by ngan** [comment]
We're going to try this:
```ruby
Sidekiq.configure_server do |config|
  config.dogstatsd = ConnectionPool.new(size: Sidekiq.default_configuration.concurrency + 2) do
    Rails.configuration.metrics
  end
```

`Rails.configuration.metrics` is our global instance of StatsD. Datadog Statsd prefers that you use just a single instance of their client:
https://github.com/DataDog/dogstatsd-ruby#migrating-from-v4x-to-v5x
> Using a singleton instance of the DogStatsD client instead of creating a new instance whenever you need one; this will let the buffering mechanism flush metrics regularly

**Comment by ngan** [comment]
Reading it again, I'm not sure if we've been interpreting this right. Does this mean that DogStatsD is suggesting we use 1 singleton client across _all_ threads? Or 1 singleton client per thread?

**Comment by mperham** [comment]
Ok, FYI `Sidekiq.default_configuration.concurrency` will not account for any configured Capsules beyond the default which is why I used `total_concurrency`.

That's kind of crazy, I didn't know they prefer a global instance but I suppose it doesn't matter as much since they are buffering internally and could use their own pool of sockets. Would you open an issue? That would be a nice update for Pro 8.0. Thanks for the tip.

**Comment by ngan** [comment]
https://github.com/DataDog/dogstatsd-ruby#thread-safety

> By default, instances of Datadog::Statsd are thread-safe and we recommend that a single instance be reused by all application threads (even in applications that employ forking). The sole exception is the #close method — this method is not yet thread-safe (work in progress here https://github.com/DataDog/dogstatsd-ruby/pull/209).

Looks like they're totally fine with using 1 global singleton instance of Statsd across all threads and recommends it. Feels like Sidekiq should be able to just take the client directly instead of managing a connection pool.

**Comment by ngan** [comment]
@mperham setting `dogstatsd` ourselves with our own connection pool worked. We're no longer seeing `ConnectionPool::TimeoutError` -- thank!

We're still seeing `Periodic subsystem skipped tick, is Redis slow?` though. So the two issues are separate. Investigation continues...

**Comment by ngan** [comment]
So turns out our workers were CPU-saturated. Bumping CPU helped.

Is there a way to make certain workers _not_ be leaders, ever? Like a `--no-leader` option on sidekiq cli? We have some instances that have spiky CPU behavior and would want to opt those workers out of ever becoming a leader.

**Comment by mperham** [comment]
There's no way to prevent a process from becoming leader explicitly. The only thing you could do is during a deploy, put a slight pause in the start of the slower machines so that the quicker machines boot first and one of them will become leader naturally.

**Comment by calvincchen** [comment]
Closing this as we've stopped seeing the issue after
1. Increased pool size for server `config.dogstatsd`
2. Bumped CPU limits in our pods

Thanks for the help debugging!
