### ISSUE TITLE
Sidekiq 7 unable to find database.yml??

### ISSUE THREAD

**Issue by RailsCod3rFuture** [sidekiq/sidekiq#6566]
Ruby version: 3.2.4
Rails version: 7.1.3.3
Sidekiq / Pro / Enterprise version(s): 7.3.7

```
2024-12-30 17:07:58.907316 I [160004:sidekiq.default/processor] {jid: 42c790ed637ee60d2adfbca7, queue: default} SendNotificationJob -- Start #perform
2024-12-30 17:07:58.972151 E [160004:sidekiq.default/processor processor.rb:133] {jid: 42c790ed6373560d2adfbca7, queue: default} (64.8ms) SendNotificationJob -- Completed #perform -- Exception: RuntimeError: Cannot load database configuration:
Could not load database configuration. No such file - ["config/database.yml"]
/var/www/app/shared/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.3/lib/rails/application/configuration.rb:465:in `database_configuration'
/var/www/app/shared/vendor/bundle/ruby/3.2.0/gems/custom_auth0-0.3.4.1.pre/app/models/base_auth0/main_base.rb:7:in `<class:MainBase>'
/var/www/app/shared/vendor/bundle/ruby/3.2.0/gems/custom_auth0-0.3.4.1.pre/app/models/base_auth0/main_base.rb:5:in `<module:MainBase>'
/var/www/app/shared/vendor/bundle/ruby/3.2.0/gems/custom_auth0-0.3.4.1.pre/app/models/base_auth0/main_base.rb:3:in `<main>'
<internal:/usr/local/rvm/rubies/ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/rvm/rubies/ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/var/www/app/shared/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
```

We use the config below for our model. Not entirely sure why this works for rails 6, but not 7
```
class MainBase < ApplicationRecord
  self.abstract_class = true
  establish_connection Rails.configuration.database_configuration[name.gsub('Base', '').downcase][Rails.env] unless Rails.env.test?
end
```
sidekiq.rb
```
Sidekiq.configure_server do |config|
  config.queues = ['default']
  config.redis = Rails.application.config.redis_config
  config.server_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
  end
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end
end

Sidekiq.configure_client do |config|
  config.redis = Rails.application.config.redis_config
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end
end
```

Typical job
```
class SendNotificationJob < ApplicationJob
  # Set the Queue as Default
  queue_as :default

  def perform(id)
   notify_person = Notification.find(id)
    return if notify_person.blank?

    to_email = notify_person.target_email_address
    bcc_email = notify_person.other_email_address
    bcc_self = notify_person.bcc_self
    subject = notify_person.subject
    content = notify_person.content
    mailer = SendNotificationMailer.send_notifier(to_email: to_email, bcc_email: bcc_email, subject: subject, content: content, bcc_self: bcc_self)
    mailer.deliver_now
  end
end
```

**Comment by RailsCod3rFuture** [comment]
Somehow -- 2 instances of sidekiq were created. I think that its no longer happening
